<?php $title = "Aktuelles";
 $menu['current'] = "aktuelles"; ?>
   <?php require("_header.inc.php"); ?>

   <h2>Leichtathletik-Elite bei der Sparkassen Gala – Harrer sagt „Goodbye“</h2>
   <p><strong>Highlightvideo von TVA Ostbayern (5:13 min)</strong></p>
     <p>Regensburg, 03. Juni 2018 (TVA Ostbayern) – Leichtathletik der Spitzenklasse gabs am Wochenende in Regensburg. Im Sportstadion der Uni Regensburg kam die Leichtathletikelite für die Sparkassen Gala zusammen. Für viele Athleten ging es um die Norm für die EM in Berlin. Eine Athletin, die das Event lange Zeit mitgeprägt hatte, stand dabei im Mittelpunkt – und das obwohl sie gar nicht angetreten war. <a target="_blank" href="https://www.tvaktuell.com/mediathek/video/regensburg-leichtathletik-elite-bei-der-sparkassen-gala-harrer-sagt-goodbye/">&raquo; Highlightvideo bei TVA Ostbayern</a> ...
   </p>
   
   <h2>DLV-Sprinterinnen setzen Ausrufungszeichen in Richtung Berlin</h2>
   <p><strong>Sprintstaffel mit europäischer Jahresbestleistung</strong></p>
     <p><img class="float_left" title="Erfolgreiche Sprintstaffel (Kiefner-Foto)" alt="Erfolgreiche Sprintstaffel (Kiefner-Foto)" src="https://www.leichtathletik.de/fileadmin/_processed_/csm_staffel_kwadwo_pinto_haase_lueckenkemper_regensburg18_foto_kiefner_233345c59d.jpg" width="270">Regensburg, 03. Juni 2018 (leichtathletik.de) – Es bleibt dabei: Wer Normen oder Top-Zeiten braucht, der kommt an der Sparkassen-Gala in Regensburg nicht vorbei. Insgesamt neun Mal erfüllten deutsche Athletinnen und Athleten am Sonntag im Uni-Stadion, das für seine schnelle Bahn und die perfekten Rahmenbedingungen bekannt ist, den geforderten Richtwert für die Heim-EM in Berlin (6. bis 12. August). Trotz wechselhafter Winde setzen einmal mehr die Sprinter die Akzente.<br />Zwei Mal Gegenwind und dennoch zwei Top-Läufe: Tatjana Pinto (LC Paderborn) ist in bestechender Form. 11,11 Sekunden im Vorlauf (-0,1 m/sec) und 11,14 Sekunden im Finale (-0,4 m/sec), das die 26-Jährige vor der Britin Imani-Lara Lansiquot (11,24 sec) und Rebekka Haase (LV 90 Erzgebirge; 11,39 sec) gewann, lassen für die kommenden Wochen Einiges erwarten. <a target="_blank" href="https://www.leichtathletik.de/news/news/detail/dlv-sprinterinnen-setzen-ausrufungszeichen-in-richtung-berlin/">&raquo; Weiterlesen bei leichtathletik.de</a> ...
   </p>
   
   <h2>Nachwuchs-Langsprinter läuten mit schnellen Zeiten die Gala in Regensburg ein</h2>
   <p><strong>Joshua Hartmann ist der erste deutsche 400-Meter-Sprinter mit U20-WM-Norm</strong></p>
     <p>Regensburg, 03. Juni 2018 (leichtathletik.de/Bernhart) - Der Vorabend der Sparkassen-Gala in Regensburg gehört mit der "Langen Laufnacht" traditionell den Bahn-Wettbewerben. Am Samstag überzeugten dabei besonders die Nachwuchs-Langsprinter, die sich mit zahlreichen schnellen Zeiten fit präsentierten für die internationalen Saison-Höhepunkte in Györ und Tampere.<br />53,90 Sekunden: So schnell war über 400 Meter seit 2010 keine deutsche U18-Athletin mehr. Eben diese Zeit bescherte am Samstag bei der Laufnacht in Regensburg Marie Scheppan vom LC Cottbus Rang drei in einem starken Nachwuchs-Feld und Rang eins in der U18. In 54,88 Sekunden unterbot dazu auch Mona Mayer (MTV 1881 Ingolstadt) die Norm für die U18-EM in Györ (Ungarn; 5. bis 8. Juli). <a target="_blank" href="https://www.leichtathletik.de/news/news/detail/nachwuchs-langsprinter-laeuten-mit-schnellen-zeiten-die-gala-in-regensburg-ein/">&raquo; Weiterlesen bei leichtathletik.de</a> ...
   </p>
   
   <h2>Marie-Jossie Graumann und Tobias Potye wollen echte Highlights setzen</h2>
   <p><strong>Beide sind echte Kandidaten für die Heim-Europameisterschaften</strong></p>
     <p><img class="float_left" title="Tocias Potye (Kiefner-Foto)" alt="Tocias Potye (Kiefner-Foto)" src="http://lg-telis-finanz.de/images/stories/2018/PotyeTobias1_Hoch_Kiefnerfoto.jpg" width="267" height="175">Regensburg, 30. Mai 2018 (orv) – Der Hochsprung bei der Sparkassen Gala hat sich gemausert. Was vor Jahren noch unmöglich schien, ist inzwischen durchaus machbar: Man kann hier in Regensburg internationale Limits angreifen. Am Gala-Sonntag wollen dies bei den Frauen Jossie-Marie Graumann von der LG Nord Berlin und der Münchner Tobias Potye tun. Potye sprang vor einem Jahr an gleicher Stelle mit 2,25m nur einen Zentimeter weniger als die jetzt geforderten 2,26m und die Berlinerin überquerte 2017 bereits schon mal 1,92m. Das sind zwei Zentimeter mehr als die EM-Norm von 1,90m. Potyes Teamkollege Lucas Mihota (LG Stadtwerke München) gehört noch der Jugendklasse U20 an, ist mit seiner Bestleistung von 2,24m ein heißer Anwärter für die U20-WM und hat sich wohl schon mal im Geheimen auch mit den 2,26 auseinander gesetzt. Unmöglich ist nichts, schon gleich nicht im Hochsprung. <a target="_blank" href="http://lg-telis-finanz.de/50-aktuelles/7840-marie-jossie-graumann-und-tobias-potye-wollen-echte-highlights-setzen">&raquo; Weiterlesen</a> ...
   </p>
   
   <h2>Viel Lokalkolorit auf den Mittelstrecken</h2>
   <p><strong>Die LG Telis Finanz präsentiert ihre Goldstücke im Galaprogramm</strong></p>
     <p><img class="float_left" title="Benedikt Huber in Aktion (Kiefner-Foto)" alt="Benedikt Huber in Aktion (Kiefner-Foto)" src="http://lg-telis-finanz.de/images/stories/2017/Huber1_soundtrack-Tuebingen17_Kiefnerfoto.jpg" width="226" height="150">Regensburg, 30. Mai 2018 (orv) – Wenn Coco Harrer bei der Sparkassen Gala die Laufbahn des Uni-Stadions betrat, war das immer etwas Besonderes. Nun hat die Olympiahalbfinalistin von 2012 genauso wie ihre Teamkollegin Maren Orth, vielen noch besser bekannt unter dem Mädchennamen Kock, den schnellen Runden tschüss gesagt und die Sparkassen Gala ist eine Attraktion ärmer. Zeit also, dass regional einige andere in deren Fußstapfen treten, national, wie auch international. Benedikt Huber, den alle in Regensburg nur Beni rufen, der Urbayer aus dem kleinen Palling am Chiemsee, ist so einer. Seit er ins Telis-Trikot geschlüpft ist, zeigt seine Formkurve steil nach oben. In den letzten beiden Jahren hieß der Deutsche Meister über die zwei Stadionrunden immer Benedikt Huber und bei den Europameisterschaften 2016 in Amsterdam hat er als Zehnter nur hauchdünn das Finale verpasst. Der Winter war für ihn zum Abgewöhnen. Jetzt ist er wieder da. Bei der Sparkassen Gala trifft er mit Christoph Kessler (LG Region Karlsruhe), Denis Bäuerle (LG farbtex Nordschwarzwald), Constantin Schulz (LC Cottbus), den beiden Südafrikanern Henco Uys und David Salomon, sowie dem Österreicher Nikolaus Franzmair auf harte Konkurrenz. <a target="_blank" href="http://lg-telis-finanz.de/50-aktuelles/7839-viel-lokalkolorit-auf-den-mittelstrecken">&raquo; Weiterlesen</a> ...
   </p>
   
   <h2>Deutschlands Viertelmeiler schwören auf die schnelle Uni-Bahn</h2>
   <p><strong>Sowohl flach als auch über die Hürden hofft man auf weitere EM-Normen</strong></p>
     <p><img class="float_left" title="Patrick Schneider (Kiefner-Foto)" alt="Patrick Schneider (Kiefner-Foto)" src="http://lg-telis-finanz.de/images/stories/2018/SchneiderPatrick1_400_Kiefnerfoto.jpg" width="132" height="201">Regensburg, 30. Mai 2018 (orv) – 400m-Läufe bei der Sparkassen Gala haben einen Mythos. Die Bahnrunde scheint hier besonders schnell zu gehen. Eigentlich sollten Deutschlands beste Viertelmeiler gar nicht in Regensburg an den Start gehen. Die waren aber in der Mehrzahl mit dieser Entscheidung gar nicht einverstanden. Eine Normerfüllung von 46,00sec für die Europameisterschaften heißt das verlockende Ziel. Johannes Trefz von der LG Stadtwerke München ist schon einmal mit 45,81sec in den vergangenen Jahren schneller gewesen, Patrick Schneider vom LAC Quelle Fürth hat die Marke mit seinen 46,02 bereits gestreift. Nun wollen sich beide bei der Sparkassen Gala unter 46sec treiben. Kann das auch Marc Koch von der LG Nord Berlin? Sein Hausrekord steht bei 46,18sec. Mit ihnen gehen sechs weitere Langsprinter der 46er-Klasse an den Start. <a target="_blank" href="http://lg-telis-finanz.de/50-aktuelles/7838-deutschlands-viertelmeiler-schwoeren-auf-die-schnelle-uni-bahn">&raquo; Weiterlesen</a> ...
   </p>
   
   <h2>Kaiserwetter für Deutschlands schnellste Sprinter/Innen</h2>
   <p><strong>Lückenkemper, Reus und co können am Sonntag im Uni-Stadion beste Bedingungen erwarten</strong></p>
     <p><img class="float_left" title="Gina Lückenkemper (Kiefner-Foto)" alt="Gina Lückenkemper (Kiefner-Foto)" src="http://lg-telis-finanz.de/images/stories/2018/LueckenkemperGina2_100_Kiefnerfoto.jpg" width="266" height="175">Regensburg, 29. Mai 2018 (orv) – Allein schon wegen der Sprinterinnen und Sprinter lohnt sich am Sonntag der Besuch der diesjährigen Sparkassen Gala. Bei den 100m trifft dabei die gesamte deutsche Spitze mit Gina Lückenkemper, Rebekka Haase, Lisa Mayer, Tatjana Pinto und Sina Mayer auf die Britin Imani-Lara Lansiquot und die Südafrikanerin Tebogo Mamathu. Zeiten unter 11 Sekunden sind so durchaus möglich, Gina Lückenkemper hat dies schon im Vorjahr mit ihrer Bestzeit von 1,95sec vorgemacht. Bei den Männern treffen Deutschlands Beste mit Julian Reus, Aleixo Platini Menga und Michael Pohl auf ein Briten-Trio mit Richard Kilty, Andrew Robertson und Tony Ramdan, alle ausgestattet mit Bestzeiten unter 10,29sec. Ein Sprint in Richtung Deutscher Rekord – gehalten von Julian Reus mit 10,01sec aus dem letzten Jahr – ist also durchaus drin. Die Wetteraussichten, prognostiziert von wetter.de, sind zur Zeit der Vorläufe (13.00 Uhr Frauen/13.30 Uhr Männer) und Finals (14.15 Uhr Frauen/14.30 Uhr Männer) ganz ausgezeichnete: strahlender Sonnenschein bei 25 Grad, mit einer leichten Brise (7 km/h) aus West mit mäßigen Böen (23 km/h) – Also erneut Kaiserwetter bei der Sparkassen Gala. Der Wind scheint diesmal von der richtigen Seite zu kommen, es muss also wahrscheinlich nicht die Laufrichtung gedreht werden. <a target="_blank" href="http://lg-telis-finanz.de/50-aktuelles/7837-kaiserwetter-fuer-deutschlands-schnellste-sprinter-innen">&raquo; Weiterlesen</a> ...
   </p>
   
   <h2>Video Vorschau von TVA Ostbayern</h2>
     <p>Regensburg, 29. Mai 2018 (TVA) - Ein Vorschauvideo der Sparkassengala vom Regionalsender TVA Ostbayern ist hier zu finden. <a target="_blank" href="https://www.tvaktuell.com/mediathek/video/regensburg-leichtathletik-der-extraklasse-bei-der-sparkassen-gala/">&raquo; Ansehen</a> auf den Seiten von TVA ...
   </p>
   
   <h2>Auch die schnelle Gina kommt</h2>
   <p><strong>Deutschlands schnellste Sprinter/Innen bei der Sparkassen Gala dabei</strong></p>
     <p><img class="float_left" title="Otto Prinzing, Franzi Reng, Norbert Lieske, Kurt Ring und Dr. Markus Witt stellen bei der PK die Sparkassen Gala 2018 vor (Wotruba-Foto)" alt="Otto Prinzing, Franzi Reng, Norbert Lieske, Kurt Ring und Dr. Markus Witt stellen bei der PK die Sparkassen Gala 2018 vor (Wotruba-Foto)" src="http://lg-telis-finanz.de/images/stories/2018/Sparkassengala_PK2018_wotrubafoto.jpg" width="225" height="135">Regensburg, 25. Mai 2018 (MZ/Wotruba) - Sie ist eine Institution, die Leichtathletik-Gala. „Wenn ich höre, dass sie jetzt zum 21. Mal ausgetragen wird, dann ist sie ja genauso alt wie ich“, sagt Franziska Reng über den jährlichen Regensburger Höhepunkt ihres Vereins LG Telis Finanz. Und der steht zweigeteilt in Laufnacht und Sparkassen-Gala am 2. Juni (14.30 bis 22 Uhr) und 3. Juni (Hauptprogramm ab 14 Uhr) im Regensburger Universitätsstadion mit rund 850 Athleten aus 17 Nationen vor der Tür. „Die Gala hat viele Stufen durchgemacht und viele Generationen gesehen“, sagt Reng bei der Pressekonferenz. Erneut dabei bei der Sparkassen Gala sind Deutschlands schnellste Sprinter/Innen mit Gina Lückenkemper und Julian Reus an der Spitze. <a target="_blank" href="https://www.mittelbayerische.de/sport-nachrichten/auch-die-schnelle-gina-kommt-21510-art1652008.html">&raquo; Weiterlesen</a> auf den Seiten der Mittelbayerischen Zeitung ...
   </p>
   
   <h2>Laufeinteilungen für Laufnacht und Sparkassen Gala</h2>
   <p><strong>Wichtige Mitteilungen für die Disziplinen 200m bis 5.000m</strong></p>
     <p>Regensburg, 25. Mai 2018 (Ring) - Nach Meldeschluss ergeben sich für die am 02. und 03. Juni stattfindende Laufnacht und Sparkassen Gala folgende Laufeinteilungen. Bei kurzfristigen Startabsagen bitten wir um eine kurze Mail an Kurt Ring (<a href="mailto:ring@athletics-sport.com">ring@athletics-sport.com</a>). <a href="news/05-25_laufeinteilungen.php">&raquo; Hier</a> geht's zu den detaillierten Einteilungen ...
   </p>
   
   <h2>Dreisprung in der Laufnacht</h2>
   <p><strong>Richard Kicks Bitte wird prompt erfüllt</strong></p>
     <p>Regensburg, 25. Mai 2018 (Ring) - Richard Kick ist ein Regensburger, auch wenn er schon einige Jahrzehnte in München lebt. So hat der Deutsche Dreisprungmeister von 1972, jetzt Coach der Münchner Dreisprungtruppe, immer noch beste Verbindungen in die Domstadt. Die nützte er jetzt für eine spontane Bitte. Nachdem er für seine Jungs in den nächsten drei Wochen keinen Wettbewerb fand, fiel ihm Regensburg ein. "Selbstverständlich geht das", sagte ihm Meeting-Direktor Kurt Ring, auch einer aus der 70er-Generation, am Telefon. So findet jetzt am Samstag, 2. Juni in der Laufnacht um 15.30 Uhr ein Dreisprung für Männer und Frauen statt. Dazu sind Spätentschlossene durchaus noch willkommen.
   </p>

<?php require("_footer.inc.php"); ?>
