<?php $title = "Aktuelles";
 $menu['current'] = "aktuelles"; ?>
   <?php require("_header.inc.php"); ?>

   <h2>Bericht über die Sparkassen Gala im BR</h2>
     <p>Regensburg, 12. Juni 2017 - Ein 2-minütiges Video über die Sparkassen Gala ist auf den Seiten von Blickpunkt Sport zu sehen. <a target="_blank" href="http://www.br.de/mediathek/video/sendungen/blickpunkt-sport-regional/regensburg-leichtathletik-gala-100.html">&raquo; Weiter</a> bei Blickpunkt Sport ...
   </p>
   
   <h2>Die schönste Laufnacht aller Zeiten</h2>
   <p><strong>Jonas Koller läuft unter 14 Minuten. Miriam Dattke legt ihr 9:30-Trauma ad acta und Corinna Schwab glänzt schon nachmittags</strong></p>
     <p><img class="float_left" title="Glückwünsche der 'Hasen' an Jonas Koller (Brüssel-Foto)" alt="Glückwünsche der 'Hasen' an Jonas Koller (Brüssel-Foto)" src="http://www.lg-telis-finanz.de/images/stories/2017/Koller1_Gala17_Bruesselfoto.jpg" width="228" height="137">Regensburg, 12. Juni 2017 (MZ/Wotruba) - Die Laufnacht war schon am späten Samstagnachmittag gerettet. Wenigstens aus Oberpfälzer Sicht. Es war noch nicht mal fünf Uhr, da war Corinna Schwab der verletzten Vereinskollegin Katrin Fehm im Ziel um den Hals gefallen. Bei 53,55 Sekunden war nach 400 Metern für Schwab die Uhr stehengeblieben: Die vor ein paar Tagen gerade erst in München aufgestellte Bestzeit noch einmal um eine halbe Sekunde gedrückt, die Europameisterschaft der U 20 in Grosseto im Juli wird greifbarer und greifbarer. „Ich wusste schon in München, das ist längst nicht alles und kann locker unter 54 gehen. Vielleicht kann ich bald noch schneller, nah an die 53“, sieht die 18-Jährige vom TV Amberg ihr Potenzial längst nicht ausgereizt. <a target="_blank" href="http://www.mittelbayerische.de/sport-nachrichten/die-schoenste-laufnacht-aller-zeiten-21510-art1528875.html">&raquo; Weiterlesen</a> auf den Seiten der Mittelbayerischen Zeitung ...
   </p>
   
   <h2>Franziska Hofmann unter 13 Sekunden</h2>
     <p><img class="float_left" title="Franziska Hofmann (Kiefner-Foto)" alt="Franziska Hofmann (Kiefner-Foto)" src="/2015/images/inhalt/100m-Huerden-Frauen_Hofmann_Franziska_Kiefnerfoto.jpg" width="250">Regensburg, 11. Juni 2017 (leichtathletik.de) - Die Chemnitzer Hürdensprinterin Franziska Hofmann lieferte am Sonntagnachmittag bei der Sparkassen-Gala in Regensburg mit einer exakt erfüllten WM-Norm die wertvollste Leistung ab. Sie ist damit die bereits fünfte DLV-Athletin, die diese Vorgabe in diesem Sommer abgehakt hat. Franziska Hofmann nutzte die guten Bedingungen im Regensburger Uni-Stadion, um die WM-Norm von 12,98 Sekunden exakt zu erfüllen. Die blonde Hürdensprinterin ist die fünfte deutsche Hürdensprinterin, die diese Vorgabe erbracht hat. Die Mannheimerin Ricarda Lobe stürzte in diesem Finallauf bereits an der ersten Hürde. „Es war in den letzten Rennen ein harter Kampf, unter 13 Sekunden zu laufen, jetzt hat es endlich geklappt“, sagte Franziska Hofmann, „die Bedingungen waren top. Ich hatte schon in den letzten Wochen gemerkt, dass ich Wettkämpfe brauche. Langsam kommt das Gefühl.“  <a target="_blank" href="http://www.leichtathletik.de/news/news/detail/franziska-hofmann-unter-13-sekunden/">&raquo; Weiterlesen</a> auf den Seiten von leichtathletik.de ...
   </p>

   <h2>Phillip Pflieger im O-Ton zur Laufgala in Regensburg (larasch.de)</h2>
   <br>
   <p><iframe width="560" height="315" src="https://www.youtube.com/embed/xbtKsxM3Fl8" frameborder="0" allowfullscreen></iframe></p>

   <h2>Lisa Oed bringt sich für Grosseto in Position</h2>
   <p><strong>Miriam Dattke läuft auch über 3000m EM-Norm</strong></p>
   	<p><img class="float_left" title="Maren Orth führt Joana Staub zur EM-Norm (Kiefner-Foto)" alt="Maren Orth führt Joana Staub zur EM-Norm (Kiefner-Foto)" src="http://lg-telis-finanz.de/images/stories/2017/OrthMaren-Staub_Gala19_Kiefnerfoto.jpg" width="118" height="177">Regensburg, 10. Juni 2017 (leichtathletik.de) - Die Regensburger Laufnacht bot am Samstag beste Bedingungen und das nicht nur am Abend auf den längeren Strecken. Die U20-Nachwuchstalente, die bei den meisten Rennen im Mittelpunkt standen, konnten das mit mehreren bemerkenswerten Leistungssteigerungen und einer Reihe von Normerfüllungen für die U20-EM in Grosseto (Italien) nutzen. Lisa Oed, im Winter Deutsche Hallenmeisterin über 3.000 Meter, gehörte an diesem Tag zu den glücklichsten Athletinnen. Die U20-EM-Norm über die Hindernisse hatte sie bereits Ende Mai abgehakt (10:27,40 min). In Regensburg packte sie bei idealen Bedingungen noch etwas drauf. Die Athletin vom SSC Hanau-Rodenbach lief sich einen deutlichen Vorsprung auf die Konkurrenz heraus und steigerte in 10:19,62 Minuten ihre Bestzeit um knapp acht Sekunden. Die Regensburger Laufnacht bot am Samstag beste Bedingungen und das nicht nur am Abend auf den längeren Strecken. Die U20-Nachwuchstalente, die bei den meisten Rennen im Mittelpunkt standen, konnten das mit mehreren bemerkenswerten Leistungssteigerungen und einer Reihe von Normerfüllungen für die U20-EM in Grosseto (Italien) nutzen. <a target="_blank" href="http://www.leichtathletik.de/news/news/detail/lisa-oed-bringt-sich-fuer-grosseto-in-position/">&raquo; Weiterlesen</a> auf den Seiten von leichtathletik.de ...
	</p>

   <h2>1000 Starter und ein Heimspiel für drei</h2>
   <p><strong>Benedikt Huber schielt auf die WM und läuft vorher in Montbeliard 1:47,36min</strong></p>
   	<p><img class="float_left" title="Brüssel Foto" alt="Brüssel Foto" src="http://lg-telis-finanz.de/images/stories/2017/Fehm-4x100-Gala16_Bruessel-Foto.jpg" width="222" height="133">Regensburg, 10. Juni 2017 (M/Wotruba/orv) - Es ist eine Herausforderung und alle Jahre Anfang Juni ein Kraftakt für die Organisatoren. 1000 Starter aus rund 20 Nationen, eine Mixtur aus nationalen Top-Leichtathleten und hoffnungsvollem Nachwuchs auf dem Sprung zu internationalen Meisterschaften, suchen im Universitätsstadion den Vergleich – bei einem Läuferklub wie der LG Telis Finanz Regensburg stets mit einem Schwerpunkt in den Laufdisziplinen. Für das beste Opening hat gleich mal Lokalmatador Benedikt Huber gesorgt. Quasi als Gala-Einstieg ist am Freitagabend in Montbeliard als Fünfter über 800m 1:47,36min gelaufen. "Da ist noch weit mehr drin, Regensburg kann kommen", teilte er noch am späten Abend seinem Coach Kurt Ring mit. <a target="_blank" href="http://www.mittelbayerische.de/sport-nachrichten/1000-starter-und-ein-heimspiel-fuer-drei-21510-art1528681.html">&raquo; Weiterlesen</a> auf den Seiten der Mittelbayerischen Zeitung ...
	</p>

   <h2>Ein alter Hase und zwei junge Laufhelden</h2>
   <p><strong>Philipp Pflieger macht Tempo. Miriam Dattke will einen Makel tilgen. Simon Boch ist Regensburgs Aufsteiger der Saison</strong></p>
   	<p><img class="float_left" title="Pflieger (Brüssel Foto)" alt="Pflieger (Brüssel Foto)" src="http://lg-telis-finanz.de/images/stories/2017/Pflieger_Sparkassengala17_bruesselfoto.jpg" width="212" height="127">Regensburg, 09. Juni 2017 (MZ/Wotruba) - Bevor es losging, schritt Philipp Pflieger noch einmal die Startlinie ab und schärfte allen ein, weswegen er denn nun in diesem Rennen mitmischt. „Wir machen das Tempo schon so, dass es passt.“ Pflieger ist ein Läufer, den man eben kennt – und gerne einmal besiegt. Der jetzt bald 30-Jährige reagierte nur auf seine Erfahrungen. „Im Jahr davor wurde ich übelst geract.“ Soll heißen: Die Mitläufer im Rennen hatten nicht so recht mitbekommen, dass der schon bei Europameisterschaften und 2016 bei Olympia international aktive Pflieger Gutes für seine Konkurrenten ausschließlich Gutes im Sinn hatte – nämlich das Tempo zu machen. <a target="_blank" href="http://www.mittelbayerische.de/sport-nachrichten/ein-alter-hase-und-zwei-junge-laufhelden-21510-art1528219.html">&raquo; Weiterlesen</a> auf den Seiten der Mittelbayerischen Zeitung ...
	</p>

   <h2>Wichtiger organisatorischer Hinweis</h2>
   <p><strong>Abholung der Startnummern nur vereinsweise möglich</strong></p>
   	<p>Regensburg, 08. Juni 2017 - Die Abholung der Startnummern bei der Laufnacht der LG Telis Finanz und der Sparkassen Gala ist nur vereinsweise gegen Bezahlung des Gesamtbetrages möglich. Die Startnummern beider Veranstaltungen werden gemeinsam ausgegeben. Es besteht aber die Möglichkeit, die Unterlagen nach Abholung einzelner Nummern am Stellplatz/Startnummernausgabe für später kommende Vereinsmitglieder zu hinterlegen. Alle Änderungen von Meldezeiten wurden bis gestern, 7. Juni ins Programm eingepflegt und erscheinen auch im Internet. Es kann aber durchaus vorkommen, dass dies bei dem im Vereinskuvert befindlichen Stellplatzkarten nicht der Fall ist, weil die schon frühzeitig gedruckt wurden. <br /><br />
	Um Sie und auch unsere Startunterlagenausgabe ein wenig zu entlasten, teilen wir Ihnen mit dieser Veröffentlichung gleich mal den Betrag für die Startgebühren ihres Vereins mit. <a target="_blank" href="download/Gala_Meldegebuehren.pdf">&raquo; Auflistung</a>
	</p>

   <h2>Erste Laufeinteilung 800m, 1500m, 5000m für die Laufnacht</h2>
   <p><strong>Bei Rennverzicht wären wir um eine Nachricht dankbar</strong></p>
   	<p>Regensburg, 07. Juni 2017 (Ring) – Die Laufnacht platzt geradezu vor lauter Läufen. Um einen reibungslosen Ablauf gewähren zu können, bitten wir alle Trainer/Innen, Vereinsbetreuer/Innen oder auch die betroffenen Athleten/Innen sich bei uns per Mail an <a href="mailto:ring@athletics-sport.com">ring@athletics-sport.com</a> zu melden, wenn ein Startverzicht ansteht, weil dann eventuell Läufe zusammengelegt werden können, beziehungsweise man in einen schnelleren Lauf aufrücken kann. Wir werden uns bemühen, den absolut straffen Zeitplan einzuhalten. Die folgende Laufeinteilung betrifft alle Laufdisziplinen mit 2 oder mehr Zeitläufen (800m, 1500m, 5000m - hier nur Männer). Bitten teilen Sie uns auch mit, ob im 5.000m Rennen der Frauen jemand dabei ist, der ein reines Frauenrennen zwecks internationaler Qualifikation braucht. Sollte dies nicht sein, werden wir einige Herren des Männer B-Laufs (21.45 Uhr ins Frauenfeld integrieren, um den letzten 5.000m Lauf ein wenig zu entlasten. Hier folgt die Laufeinteilung 800m, 1500m und 5000m (nur Männer) <a target="_blank" href="http://lg-telis-finanz.de/50-aktuelles/7565-erste-laufeinteilung-800m-1500m-5000m-fuer-die-laufnacht">&raquo; weiterlesen</a>
	</p>

   <h2>Die Sparkassen Gala glänzt wieder mit einer tollen Besetzung</h2>
   <p><strong>Wer schafft in Regensburg den Sprung zu den Weltmeisterschaften nach London?</strong></p>
   	<p><img class="float_left" title="Huber, Ludolph (Kiefner Foto)" alt="Huber, Ludolph (Kiefner Foto)" src="http://lg-telis-finanz.de/images/stories/2016/Huber-Ludolph_Gala16_Kiefner-Foto.jpg" width="162" height="164">Regensburg, 07. Juni 2017 (orv) –  Das Regensburger Uni-Stadion ist nicht nur bei deutschen Top-Athleten/Innen ein Geheimtipp für gute Leistungen. Auch am kommenden Sonntag wollen wieder viele nationale Spitzenleute, darunter etliche, die sich die Qualifikation für die Weltmeisterschaften in London zutrauen, ihre gesteigerte Leistungsfähigkeit unter Beweis stellen und treffen dabei auf Konkurrenz aus 22 Nationen. Große Namen sind darunter wie der deutsche Rekordhalter im Sprint Julian Reus (TV Wattenscheid 01), der deutsche Meister und EM-Zehnte über 800m Benedikt Huber vom Ausrichter LG Telis Finanz, die Olympiateilnehmerin über 200m Nadine Gonska (MTG Mannheim) mit einem Hausrekord von 22,79sec, die deutsche 400m Hürdenmeisterin Jackie Baumann (LAV Stadtwerke Tübingen), die beiden deutschen 400m-Asse Ruth Sophia Spelmeyer (VfL Oldenburg) und Laura Müller (LC Rehlingen), beide mit Bestzeiten deutlich unter 52 Sekunden, und last not least die 1500m-EM-Sechste Maren Orth von der heimischen LG Telis Finanz. Internationalen Flair ins Uni-Stadion bringen Sprinter Anaso Jobodwana aus Südafrika mit 10,10 und 19,87sec über 100 und 200m gemeldet, 400m Hürdenmann Milud Rhamani (Algerien), dessen Hausrekord bei 49.64 Sekunden steht, die beiden kuweitischen Hürdensprinter Abdulaziz Al Mandeel und Yaqoub Al Youha, mit ausgezeichneten 13,39 und 13,48 Sekunden notiert, die Britin Bianca Williams, ebenso schon unter 23 Sekunden über 200m gelaufen, die 1:58,63-Läuferin Winnie Nayondo aus Uganda und die 6,49-Weitspringerin Ivona Dadic aus Österreich. <a href="news/06-07_vorschau-gala.php">&raquo; weiterlesen</a>
	</p>

   <h2>Telis-Asse sollen DLV-Nachwuchs zur EM führen</h2>
   <p><strong>Die Laufnacht der LG Telis Finanz verspricht tollen Nachwuchssport und nicht nur diesen</strong></p>
   	<p><img class="float_left" title="Miri Dattke (Kiefner Foto)" alt="Miri Dattke (Kiefner Foto)" src="http://www.lg-telis-finanz.de/images/stories/2017/DattkeMiriam1_Berlin-5000m-2017_Kiefnerfoto.jpg" width="107" height="163">Regensburg, 07. Juni 2017 (orv) –  Deutschlands Nachwuchselite im Bereich Lauf kommt gerne zur Laufnacht der LG Telis Finanz ins Regensburger Uni-Stadion. Dem trägt auch der Deutsche Leichtathletik-Verband Rechnung. Er hat bei der Veranstaltung am kommenden Samstag im Regensburger Uni-Stadion die letzte entscheidende Ausscheidung für seine Jungtalente in Richtung U20-Europameisterschaften vom 20.-23. Juli im italienische Grosseto angesetzt. Danach geht nichts mehr. Schon die Sonntagswettbewerbe der Sparkassen Gala werden dann nicht mehr für die Nominierung berücksichtigt. Die perfekte Organisation, das stets zu dieser Zeit ideale Laufwetter und nicht zuletzt die mustergültigen Tempi der Pacemaker, in diesem Falle gestellt von der gesamten Laufelite der LG Telis Finanz, sorgen für Rahmenbedingungen, die Bestzeiten en masse fast schon garantieren. Den Abschluss werden erneut die 5000m-Läufe der Frauen und Männer mit einer feinen internationalen Besetzung von 21 bis 22 Uhr bilden. <a href="news/06-07_vorschau.php">&raquo; weiterlesen</a>
	</p>

   <h2>Wichtiger Hinweis für alle Nach- und Ummelder für die Sparkassen Gala und Laufnacht</h2>
   <p><strong>Die Organisatoren der Gala und Laufnacht erreichen organisatorisch jetzt die rote Zone</strong></p>
   	<p>Regensburg, 06. Juni 2017 (Ring) - Die Meldelisten stehen nun schon seit einigen Tagen auf unserer Homepage. Trotzdem erreichen uns täglich eine zweistellige  Anzahl von Wünschen zur Um- und Nachmeldung von Athleten/Innen. Das erfordert bei unserer Meldestelle enorm erhöhten Arbeitsaufwand. Deshalb betrachten wir ab sofort jede Ummeldung als Nachmeldung, also als zusätzliche Meldung, für die eine weitere Meldegbühr plus der Nachmeldegebühr erhoben wird. Nachmeldungen werden nur mehr in ganz besonderen Fällen vom Meeting-Direktor bearbeitet ohne Garantie auf einen positiven Bescheid. Dem Wunsch nach Unterbringungsvermittlungen können wir ab sofort nicht mehr nachkommen, da wir bereits alle freien Hotelbetten an unsere Partnerhotels zurückgegeben haben. Organisationschef Jochen Schweitzer hatte bereits im erweiterten Vorfeld alle Bundestrainer hingewiesen, dass dies so sein würde. Wir bitten um Verständnis für diese Maßnahmen.<br /><br />Kurt Ring<br />Meeting-Direktor der Sparkassen Gala und Laufnacht der LG Telis Finanz Regensburg
	</p>

   <h2>Erste Teilnehmerliste ist online</h2>
   	<p>Regensburg, 02. Juni 2017 - Wir haben eine erste Teilnehmerliste hochgeladen. Hieraus sind auch die Einteilungen Vor-/ Hauptprogramm ersichtlich. Durch eventuelle Absagen kann es aber noch leichte Verschiebungen geben, wir werden die nächsten Tage noch Updates veröffentlichen. <a href="teilnehmer.php">&raquo; Teilnehmer</a>
	</p>

	<h2>Erste Meldelisten für die Sparkassen Gala und Laufnacht sind da</h2>
   <p><strong>Die Liste mit den 170 ausländischen Athleten/Innen fehlt noch</strong></p>
   	<p>Regensburg, 01. Juni 2017 - An die 900 Athleten/Innen aus Deutschland und weiteren 22 Nationen werden am 10. Juni bei der Laufnacht der LG Telis Finanz und am 11. Juni bei der Sparkassen Gala im Regensburger Uni-Stadion teilnehmen. Nach Meldeschluss Mittwoch, 31. Mai 2017, 23.59 Uhr liegt das erste Meldeprotokoll von LADV vor. Es erfasst aber nur die deutschen Teilnehmer/Innen, weil ausländische Gäste über LADV nicht melden können. Unsere Meldestelle mit ihrem Leiter Thomas Stockmeier wird sich nun allergrößte Mühe geben die Gesamtmeldeliste mit weiteren fast 200 ausländischen Sportler/Innen bis zum Wochenende zu erstellen, damit wir sie veröffentlichen können. Bitte haben Sie also noch ein wenig Geduld. Wir werden uns auch bemühen, den Zeitplan an beiden Tagen den tatsächlichen Gegebenheiten anzupassen. Schließlich wollen wir Ihnen reibungslose und flotte Abläufe bieten. Auch das kann ein paar Tage noch dauern. Bitte schauen Sie also am Anfang nächster Woche noch einmal auf unsere Seite, ob sich ihre ganz spezielle Startzeit geändert hat. <a href="teilnehmer.php">&raquo; Hier</a> geht's zum Meldeverzeichnis ...
	</p>

   <h2>Rechtzeitige Meldungen für Laufnacht und Sparkassen Gala</h2>
   <p><strong>Bitte beachten: Meldeschluss Mittwoch, 31. Mai, 23.59 Uhr</strong></p>
	<p>Regensburg, 29. Mai 2017 (Ring) - Aus der Erfahrung der letzten Jahre möchte ich nochmals drauf hinweisen, dass der Meldeschluss für die Sparkassen Gala und Laufnacht in Regensburg am Samstag/Sonntag, 10./11. Juni 2017 online bereits über LADV am kommenden Mittwoch, 31. Mai 2017, 23.59 Uhr ist. Bitte ersparen Sie uns häufige Nachmeldungen. Uns kosten sie Mehrarbeit und Ihnen verursachen sie mehr Kosten. Wir freuen uns schon auf Ihren Besuch.
	<br />Kurt Ring, Meeting-Direktor</p>

   <h2>Wer macht in Regensburg die Pace?</h2>
   <p><strong>Telis-Laufelite stellt sich zu Hause in Diensten der Nation</strong></p>
	<p><img class="float_left" title="Huber Ludolph Gala16 Kiefner Foto" alt="Huber Ludolph Gala16 Kiefner Foto" src="http://lg-telis-finanz.de/images/stories/2016/Huber-Ludolph_Gala16_Kiefner-Foto.jpg" width="162" height="164">Regensburg, 28. Mai 2017 (orv) –  Zum 20. Mal findet am 11. Juni im Regensburger Uni-Stadion die Leichtathletik Gala statt. Die einen Tag vorher ablaufende „Laufnacht“ gehört inzwischen schon fast traditionell dazu. Anfangs hieß das Sportfest Bayern Gala, später dann Domspitzmilch Gala und ab 2008 „Sparkassen Gala“. 2006, als der damalige Cheftrainer Jürgen Mallow fast die gesamte deutsche Ausscheidung für die Team-EM nach Regensburg verlegte, weil kein anderer nationaler Ausrichter wegen den hierzulande stattfindenden Fußball-Weltmeisterschaften sie veranstalten wollte, schaffte das Sportfest seinen Durchbruch. Inzwischen ist das Meeting recht lauf- und sprintlastig, meist mit tollen Hochsprüngen garniert. Da stellt sich natürlich in Zeiten der ewigen Normenhatz stets die Frage: Wer macht das Tempo in den einzelnen Läufen? Es ist schon längst kein Geheimnis mehr, dass diese Spezies der sportlichen Dienstleister mitunter die teuersten Athleten/Innen eines Meetings sind. Da man in Regensburg nicht erst seit gestern jeden Cent umdrehen muss, hat man aus der Not eine Tugend gemacht. Die gewiss nicht schlechte Läuferschar übernimmt einfach diese Aufgabe. <a href="news/05-28_tempomacher.php">&raquo; weiterlesen</a></p>

   <h2>Erster Zeitplan ist online</h2>
	<p>Regensburg, 07. Mai 2017 - Ein erster Zeitplan zur Laufnacht und Sparkassen Gala 2017 ist online. Bitte beachten Sie, dass es bis zur Veranstaltung noch leichte Anpassungen geben kann.<a href="zeitplan.php">&raquo; Zeitplan</a></p>

   <h2>Die Sparkassen Gala lebt</h2>
	<p><strong>Regensburger Traditionsmeeting nur mit kleinen Abstrichen</strong></p>
	<p><img class="float_left" title="Corinna Harrer (Brüssel-Foto)" alt="Corinna Harrer Gala16 Brüsselfoto" src="http://lg-telis-finanz.de/images/stories/2016/Harrer-Kock1_Gala16_Bruesselfoto.jpg" width="223" height="134">Regensburg, 11. April 2017 (orv/lgr) -  Den Regensburger Meetingmachern ist es trotz aller dunkler Vorzeichen gelungen, die Sparkassen Gala 2017 auf solide Beine zu stellen. Dass dies so ohne Weiteres möglich sein wird, war in den vergangenen Wochen und Monaten nicht unbedingt ersichtlich. „Die ein oder anderen Abstriche müssen wir natürlich beim Gesamtevent machen, was aber kaum zu Lasten der sportlichen Qualität gehen wird,“ so Jochen Schweitzer, Cheforganisator der Sparkassen Gala. Worauf Leichtathletikfans in diesem Jahr in Regensburg  verzichten müssen, ist der seit Jahren zur Verfügung gestellte Live-Stream. Ebenso fiel der VIP-Bereich für die Ehrengäste zum Opfer des Rotstiftes, den das Organisationsteam ansetzen musste. Dennoch können die Zuschauer, Gäste und Athleten sich auf aus nationaler Sicht leichtathletischen Hochgenuss freuen, der am 10. Juni mit der Laufnacht beginnt und am 11.06 mit der Sparkassen Gala als Höhepunkt ausklingt. <a href="news/04-11_gala-lebt.php">&raquo; Hier</a> geht's weiter ...</p>

<?php require("_footer.inc.php"); ?>
