<?php $title = "Die große Sparkassen Gala Vorschau - Frauen";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2>Die große Sparkassen Gala Vorschau</h2>
<strong>Die LG Telis Finanz präsentiert die Frauen-Wettbewerbe</strong><br /><br />
<p>
<img src="../photos/vorschau/Einfuehrungstext_Harrer_gala13_int.jpg" class="float_left" width="198px">Regensburg, 01. Juni 2013 (orv) –  Die Startnummer 1000 wurde genau am Tag des offiziellen Meldeschlusses der Sparkassen Gala 2013 vergeben. Bei 1229 Nennungen sind Spitzenreiter die 100m mit 288 Teilnehmer/Innen, gefolgt von den 800m mit 222 Teilnehmer/Innen aus 281 Vereinen und 17 Nationen. Das Beste spielt sich im eigentlichen Gala-Programm zwischen 16 und 19.30 Uhr ab. Liebhaber des Laufs sehen die ganze Palette des Disziplinblocks von 19.30 bis 22 Uhr mit hochwertigen Wettbewerben. Ab 9.30 Uhr läuft ein umfangreiches Vorprogramm. Die Sparkassen Gala wird von 15 bis 22 Uhr im Internet gestreamt (<a href="../live-stream.php">Livestream</a>).<br/><br/>
<strong>Hier die Gala-Wettbewerbe der Frauen:</strong><br/><br/>
<img src="../photos/vorschau/100m-Frauen_Gala13_Onuora,Anyika1_int.jpg" class="float_left"><strong>100m (VL 14.00 Uhr/EL 16.30 Uhr)</strong><br/>
Mit Tatjana Pinto (LG Ratio Münster – 11,22) kommt Deutschlands Sprint-Zukunft nach Regensburg. Sie trifft hier auf harte ausländische Konkurrenz: Katerina Cechova (Tschechien - 11,32), Jodie Williams (Großbritannien – 11,32) und Globine Mayova (Namibia – 11,34) sitzen ihr dicht im Nacken. Auch die Mannheimerin Yasmin Kwadwo ist nicht zu unterschätzen (11,42). Ina Weit (11,43), Ida Mayer (11,47) und Altmeisterin Cathleen Tschirch (11,49) liegen in Lauerstellung.<br/><br/>
<img src="../photos/vorschau/200m-Frauen_Haack,Christina4_int.jpg" class="float_left" height="180px"><strong>200m (ZEL 18.30 Uhr)</strong><br/>
Mit der Britin Jodie Williams (22,79) und der Leverkusenerin Cathleen Tschirch (22,97) haben zwei Athletinnen Hausrekorde unter 23 Sekunden aufzuweisen. Sie treffen auf die Deutsche Meisterin von 2012 Ina Weit (23,08) und Maike Dix vom TV Wattenscheid 01 (23,39). Dahinter tummeln sich mit den beiden Sprinterinnen aus Namibia Tjipekapora Herunga und Globine Mayova, sowie der Slowenin Kristina Zumer Athletinnen aus dem 23,50er Bereich.<br/><br/><br/><br/><br/>
<img src="../photos/vorschau/800m-Frauen_Gala13_Makhanya,Mapaseka2_int.jpg" class="float_left" height="180px"><strong>800m (A-/B-EL 17.30 Uhr)</strong><br/>
Die 800m der Frauen waren in Regensburg immer ein Highlight. Verantwortlich dafür zeigte sich in den letzten Jahren Lokalmatadorin Corinna Harrer, die 2012 hier mit 2:01,60 eine Zeit setzte, die im letzten Jahr außer ihr selbst keine Deutsche übertraf. Eigentlich ist die Regensburger Olympia-Halbfinalistin und Vize-Hallen-Europameisterin mit ihrer Bestzeit von 2:00,34 auf dem Sprung zu einer Zeit unter zwei Minuten. Eigentlich war alles dafür hergerichtet, bis sie sich vierzehn Tage vor der Sparkassen Gala eine Lebensmittelvergiftung zuzog. Ob Regensburgs Lauffloh überhaupt antreten kann, wird sich erst in den letzten Tagen vor der Gala zeigen. Konkurrenz für einen Lauf unter zwei Minuten wäre mit der Polin Anna Rostkowska (1:58,72) und der Tschechin Lenka Masna (1:59,72) da. Aus deutscher Sicht versuchen Fabienne Kohlmann (pB 2:00,72) und Annette Horna (pB 2:02,29) an ihre persönlichen Bestleistungen heranzukommen. Mit im Rennen ist auch Deutschlands neuer Shootingstar Sonja Mosler (2:02,93), die sich im Winter den nationalen Hallentitel holte.<br/><br/>
<img src="../photos/vorschau/1500m-Frauen_gala13_Duerrenmatt,Sibylle2_int.jpg" class="float_left" height="180px"><strong>1500m (A-/B-EL 19.00 Uhr)</strong><br/>
Der 1500m Lauf hat trotz einer Deutschen Meisterin aus den Telis-Reihen nicht die Bedeutung der kürzeren Mittelstrecke. Hier sollen vor allem die U20, U23 und U18 Talente Isabelle Teegen (4:22,53), Maria Dietz (4:23,45) und Alina Reh (4:26,00) um die internationalen EM-Nachwuchsnormen kämpfen. Erst vor acht Tagen hat sich auch U23-Telis-Talent Thea Heim mit ihrer 4:22,22 in den Vordergrund gelaufen. Der Sieg aber wird über die Schwedin Charlotte Schönbeck laufen, die immerhin schon eine 4:09,70 stehen hat. Hindernisläuferin Sanaa Koubaa (LG Stadtwerke Hilden) will wieder an ihre Bestzeit des Vorjahrs anknüpfen (4:18,46).<br/><br/><br/>
<img src="../photos/vorschau/5000m-Frauen_Gala13_Kock,Maren1_int.jpg" class="float_left" height="180px"><strong>5000m (Endlauf  21.55 Uhr)</strong><br/>
Über 5000m geht es für zwei Hand voll deutscher Athletinnen um 16er Zeiten und damit um die Qualifikation für die Deutschen Meisterschaften in Ulm. Auch fünf LG Telis Finanz Läuferinnen sind mit Steffi Perfler, Carolin Aehling, Steffi Volke, Susanne Schulze und Julia Galuschka darunter, von denen die drei Erstgenannten die Norm bereits haben, in persona Carolin Aehling an einem guten Tag sogar Siegchancen bestehen. Ärgste Konkurrentinnen dafür sind die Österreicherin Anita Baierl (16:24,20) und die Kölnerin Ursula Gatzweiler (16:38,91). <br/><br/><br/><br/>
<img src="../photos/vorschau/100mHuerden-Frauen_Spindler-Roleder_gala13_int.jpg" class="float_left" width="198px"><strong>100m Hürden (VL 15.00 Uhr/ EL 16.00 Uhr)</strong><br/>
Die Jagd nach den 12er Zeiten hat begonnen, speziell jene nach der WM-Norm von 12,92. Sowohl Nadine Hildebrand (12,94) als auch Cindy Roleder (12,91) haben das drauf. Namhafte Konkurrenz kommt mit der in Leipzig lebenden Amina Ferguen (13,04) und den beiden Finninnen Nooralotta Neziri (13,10) bzw. Elisa Leinonen (13,29) aus dem Ausland. Auch Antonia Werner sollte man mit ihren 13,31 nicht unterschätzen. Alexandra Burghardt (U20) will sich hier für die Nachwuchs-EM qualifizieren.<br/><br/>
<strong>400m Hürden (EL 17.10 Uhr)</strong><br/>
Gespannt sein darf man hier auf das Debüt der 51,97-Flachsprinterin Janin Lindenberg. Schafft sie den Umstieg auf die Runde mit Hürden reibungslos? Claudia Wehrsen, Christiane Klopsch, Frederike Hohgrebe und Anna Raukuc, alles versierte Langhürdlerinnen bis zum 56er-Bereich werden die Magdeburgerin auf ihre Tauglichkeit testen.<br/><br/>
<img src="../photos/vorschau/3000mHindernisFrauen_Gala13_int.jpg" class="float_left"><strong>3000m Hindernis (EL 21.10 Uhr)</strong><br/>
Die auch hier als Bayerische Meisterschaften ausgeschriebenen 3000m Hindernis haben mit der Tschechin Eva Krchova eine 9:54-Frau als Favoritin. Dahinter wird die Schweizerin Arlette Meier-Hunger Deutschlands Nachwuchsläuferinnen und einige Altgediente auf ihre Tauglichkeit über die 76cm hohen Balken testen. Den Landestitel sollten die in Regensburg bestens bekannten Susi Lutz (LG Bamberg) und Julia Hiller (LAC Quelle Fürth) unter sich ausmachen, nachdem U23-Ass Jannika John nach ihren 10:05 von Rehlingen und der damit erfüllten Norm für die Junioren-EM in Tampere nur für die 1500m gemeldet hat. Die Jugendliche Johanna Schulz braucht eine Zeit unter 10:35 um bei der U20-EM dabei sein zu dürfen.<br/><br/>
<img src="../photos/vorschau/Weit-Frauen_Gala13_Weitzel,Michelle15_int.jpg" class="float_left"><strong>Weitsprung (VE 18.15 Uhr)</strong><br/>
Der Weitsprung der Frauen ist auch immer ein Regensburger Wettbewerb. Michelle Weitzel (SWC Regensburg), Bestleistung 6,64 und 2011 Deutsche Freiluft- und Hallenmeisterin will hier im Uni-Stadion zeigen, dass sie die kürzlich in Weinheim mit unerlaubten Rückenwind erzielten 6,67 auch regulär drauf hat. So weit kann allerdings auch Lena Malkus (SC Preußen Münster) springen. Der Hausrekord der erst Zwanzigjährigen steht seit dem letzten Jahr immerhin bei 6,72 und auch in diesem Jahr ist sie schon im 6,60er Bereich gelandet. Die Österreicherin Marina Kraushofer (6,35) und die Berlinerin Urszula Westhoff (6,33) würden sich schon über Sätze nahe der sechseinhalb Meter freuen.<br/><br/>
<img src="../photos/vorschau/Hoch-Frauen_Gala13_int.jpg" class="float_left" width="198px"><strong>Hochsprung (E 15.15 Uhr)</strong><br/>
Die Sparkassen Gala kann mit Marie-Laurence Jungfleisch schon eine WM-Qualifikantin begrüßen. Kurz vor der Gala hat sie die 1,95 abgehakt und will sie nun in Regensburg bestätigen. Geht es vielleicht sogar Richtung zwei Meter? Das hat schon lange keine Deutsche außer Ariane Friedrich mehr geschafft. Immerhin die 1,90 haben im Vorfeld schon die in Österreich lebende Russin Ekaterina Kuntsevich (1,90) und Nadja Kampschulte vom TV Wattenscheid 01 (1,91) gepackt. Vielleicht gelingt dies auch erstmals der Jugendlichen Alexandra Plaza (1,88 bisher).<br/><br/>
<img src="../photos/vorschau/Stabhoch-Frauen_Gala13_Schnitzerling,Lilli2_int.jpg" class="float_left" height="180px"><strong>Stabhochsprung  (E 17.00 Uhr)</strong><br/>
Mit der Vize-Weltmeisterin von 2011 Martina Strutz präsentiert die LG Telis Finanz Regensburg bei ihrer Sparkassen Gala ein ganz besonderes Schmankerl. Nach durchwachsener letzter Saison und lediglich 4,60 bei den Europameisterschaften in Helsinki, die aber immerhin Silber einbrachten, möchte sich die Neubrandenburgerin wieder in alte Regionen Richtung 4,90 bewegen. Regensburg soll dafür ein Beginn sein. Härteste Konkurrentin um den Sieg wird die finnische 4,60-Springerin Minna Nikkanen sein. Dahinter sollten Annika Roloff (4,40) und Katie Byres (Großbritannien – 4,35) die 4,50m attackieren.
</p>
<?php require("../_footer.dir1.inc.php"); ?>
