<?php $title = "News";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2>Sparkassen Gala in Regensburg in trockenen Tüchern</h2>
<strong>Sponsoring auf sehr gutem Weg</strong>
<br />
<br />

<p>  <img src="http://www.sparkassen-gala.de/2010/photos/briten_gala10_jungfoto.jpg" width="147" height="169" class="float_left" />Regensburg, 02. Januar 2011 (orv) - Heimlich still und leise hat sich das süddeutsche Top-Meeting, die Sparkassen Gala in Regensburg unter den Top-Veranstaltungen Deutschlands weit nach vorne gearbeitet. Anfangs als Sportfest für alle mit einigen Top-Wettbewerben konzipiert, rangiert Regensburg nach der internationalen Punktewertung inzwischen hinter dem ISTAF in Berlin und der Wattenscheider DLV-Gala an dritter Stelle der deutschen Meetings. Dabei hat Meetingdirektor Kurt Ring nie versucht, auf Biegen und Brechen ganz nach oben zu kommen. &quot;Ein Fest für alle soll die Gala in erster Linie sein mit einem üppigen Vorprogramm, einer knackigen Gala selbst und zwecks der dann guten Rahmenbedingungen jetzt auch noch mit einer Laufnacht.</p>
<p>Weit mehr als 900 Teilnehmer wollten in   den letzten Jahren jeweils teilnehmen. Sehr zu unserem Bedauern mussten wir jedes Mal schon Tage vor dem offiziellen Nachmeldeschluss die Schotten dicht machen. Der Erfolg gibt unserem Konzept damit recht,&quot; so Kurt Ring zum Credo der Sparkassen Gala,&quot; und es ist alles andere als leicht, jedes Jahr den Haufen Geld einzusammeln, den man für ein solches Event braucht.&quot; Bereits jetzt, am Anfang des Jahres können sich die Regensburger schon recht entspannt zurücklehnen. Das Sponsoring lief gut, die Gala ist im Großen und Ganzen gesichert und auch die   verschiedenen DLV-Bundeskader haben bereits wieder ihr Kommen avisiert.</p>
<p>Besonders erfreulich ist, dass es in den Staffelentscheidungen über 4x100 m fast zu einer kleinen EM kommt. Die Briten haben schon angefragt, die Österreicher bringen gleich das gesamte Nationalteam mit, die Finnen wollen vorbeischauen und auch die Franzosen zeigen Interesse, zumal die Ergebnisse wahrscheinlich bereits für eine Qualifikation Richtung London 2012 eingebracht werden können. Vor allem auf die Nachbarn aus Österreich freut man sich besonders, weil dort derzeit der in Bayern viele Jahre lang als leitender Landestrainer tätige Jürgen Mallow inzwischen als Sportdirektor das Zepter schwingt. Er war es, der der Regensburger Gala mit der fast gesamten Europacup-Ausscheidung 2006 damals den entscheidenden Schub gab. In der Domstadt freut man sich auch auf den Schweizer Laufkader um Fritz Schmocker, mit dem die Telis-Läufer/Innen schon in einigen Trainingslagern gut zusammenarbeiten konnten. So steht dem nichts im Wege, damit der 4. Juni wieder ein Fest der ganzen Leichtathletikfamilie wird.</p>
<p class="textnote">Foto: Geschlagene Britische Staffelläufer bei der Gala 2010 (Jung-Foto) </p>
<?php require("../_footer.dir1.inc.php"); ?>