<?php $title = "News - Die große Gala Vorschau – Frauen";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2> Die Sparkassen Gala im Schnelldurchlauf - Frauen </h2>
<strong>Die große Gala Vorschau – Frauen</strong>
<br />
<br />

<p>  <img src="../photos/sailerverena2-int-kiefner.jpg" alt="Verena Sailer" width="113" height="170" class="float_left" />Regensburg, 2. Juni 2010 - Alle Vorbereitungen für die Sparkassen Gala am 5. Juni im Regensburger Uni-Stadion sind abgeschlossen. Der Wetterbericht sagt nur Gutes - nun kann's also los gehen:</p>
<p><strong>100 m</strong></p>
<p>Verena Sailer schickt sich immer mehr an, europäische Spitze zu werden. Die 11,30 von Rehlingen am Pfingstmontag waren ein erster Fingerzeig. In Regensburg trifft sie auf ehemalige Weltklasse in persona der Französin Muriel Hurtis. Die hat die magischen 11 Sekunden bereits geknackt (PB 10,96) und sollte immer noch stark genug sein, um der Deutschen einigermaßen Paroli bieten zu können. Nicht zu unterschätzen sind die beiden Britinnen Laura Turner und Emma Ania, die immerhin eine 11,19 und 11,21 mitbringen.</p>
<p><strong>200 m</strong></p>
<p>Da stehen sie also, die 22,31 in der Nennliste der Sparkassen Gala 2010. Dahinter steht der Name Muriel Hurtis. Diese Zeit ist die Französin zwar schon länger nicht mehr gelaufen, die Qualität, der deutschen Spitze eine adäquate Gegnerin zu sein, hat sie aber immer noch. Vielleicht ist das für Cathleen Tschirch genau der richtige Ansporn, um knapp unter 23 Sekunden zu bleiben. Bisher hat das in Regensburg nur Birgit Rockmeier geschafft.</p>
<p><strong><img src="../photos/nwachukwusorina2-int-kiefner.jpg" alt="Sorina Nwachukwu" width="113" height="170" class="float_right" />400 m</strong></p>
<p>Sorina Nwachukwu heißt die junge Dame aus Leverkusen, an der in Deutschland im letzten Jahr keine vorbei gekommen ist. Ihre ungestüme Art anzulaufen, hat sie inzwischen ein wenig gezähmt. Die Zeiten liegen bei ihr konstant im 51er-Bereich. Diese 51 Sekunden vor dem Komma will auch die derzeitige Überfliegerin im Langsprint, Fabienne Kohlmann aufleuchten sehen. Die EM-Norm in ihrer Spezialdisziplin hat sie beim ersten Mal nur um ein Hundertstel verfehlt, jene auf der Überdistanz 800 m mit ihrem Parforceritt von Dessau (2:00,72) auf Anhieb unterboten. Jetzt sind erstmals die 400 m flach dran.</p>
<p><strong>800 m</strong></p>
<p>Cottbus-Siegerin Zahra Bouras ist mit ihren dort gelaufenen 2:01 klare Favoritin. Ob die heuer stark verbesserte Annette Horna nun ihre Spezialdisziplin 800 m oder eben die 1500 m läuft, wird erst ganz spät entschieden. Die zweite deutsche Reihe hat ihre Karten noch nicht aufgedeckt. Nicht vergessen sollte man die erst 17-jährige Schweizerin Andrina Schläpfer, die sich vor 14 Tagen als Zweite der europäischen Ausscheidung in Moskau für die 1. Olympischen Spiele der Jugend qualifiziert hat.</p>
<p><strong><img src="../photos/harrer_krebs_sussmann1-int-kiefner.jpg" alt="Harrer-Krebs-Sußmann" width="113" height="170" class="float_left" />1500 m</strong></p>
<p>Ein Wettbewerb mit starkem Lokalkollorid: Die beiden Telis-Asse Christiane Danner und Corinna Harrer wollen sich als letztjährige DM-Vierte bzw. –Zweite mit der gesamten deutschen Spitze messen. Mit im Wettbewerb sind auch Barbara Maveau, eine 4:09-Läuferin aus Belgien und die beiden 4:15-Läuferinnen Marcela Lustigova und Tereza Capkova aus Tschechien, die Lettin Agatha Strausa (4:16), sowie die Schweizerin Valerie Lehmann (4:15). Die Deutsche Meisterin Denis Krebs ist also gefordert, mit ihr natürlich auch die Dritte und Sechste der U20-EM des letzten Jahres, die Zwillinge Elina und Diana Sujew. Alle wollen sie Richtung 4:10 laufen.</p>
<p><strong>100 m Hürden</strong></p>
<p>Nadine Hildebrand gegen Anne-Kathrin Elbe und Cindy Roleder heißt der Dreikampf auf den 100 m Hürden. Alle drei liebäugelten mit der EM-Norm von 13,00. Ausgerechnet die im Vorfeld als Schwächste des Trios, Cindy Rolder aus Leipzig. hat nun die Schallmauer in Baunatal mit einer 12,97 schon durchbrochen.  Die Voraussetzungen, warmes Wetter und vielleich günstiger Schiebewind könnten am Samstag noch mehr möglich machen. Chancen dazu gibt es im Vor- und Endlauf. Außerdem ist in Regensburg noch nie eine Hürdenläuferin unter 13 Sekunden gelaufen. Es wird also Zeit dafür. Lokalmatdorin Pamela Spindler möchte dahinter einen guten Saisoneinstieg im Bereich von 13,40-50 abliefern.</p>
<p><strong><img src="../photos/lutzsusi6-int-kiefner.jpg" alt="Susi Lutz" width="113" height="170" class="float_right" />3000 m Hindernis</strong></p>
<p>„Das Thema Mannschaftseuropameisterschaften in Bergen ist noch nicht abgeschlossen“, so Bundestrainer Werner Klein im Vorfeld zum Regensburger Rennen. Favoritin für den heißbegehrten Platz ist Vorjahressiegerin Verena Dreier. Telis-Ass Susi Lutz hatte schon im Vorjahr einen Angriff auf die Siegerländerin gestartet. Zu gönnen wäre es der quirrligen Regensburgerin nach endlich überstandener Erkältung einfach im heimischen Stadion mal zu zeigen, zu was sie in der Lage ist. Es muss nicht immer nur in Kaunas passieren. Dort holte sie zweimal EM-Bronze. 10:01 hat sie stehen, die 9er-Zeit ist längst überfällig. Arlette Meier-Hunger, die österreichische Rekordhalterin Andrea Mayr und Birte Schütz aus Wattenscheid gehören auch in diese Liga.</p>
<p><strong>Weit</strong></p>
<p>An sich ein eher weniger interessanter Wettbewerb, wäre da nicht eine Michelle Weitzel von der LG Telis Finanz. Die springt seit länger Zeit weit, sogar sehr weit. So weit, dass sie in der Halle mit 6,50 bereits in der Nähe der EM-Norm gelandet ist. Mal sehen, was in Regensburg herauskommt? Eine weitere Sechs-Meter-Springerin ist die Jugendliche Lisa Kurschilgen aus Leverkusen mit einer Bestleistung von 6,11 m.</p>
<p><strong><img src="../photos/weitzlemichele1-int-kiefner.jpg" alt="Michelle Weitzel" width="113" height="170" class="float_left" />Hoch</strong></p>
<p>In Abwesenheit der verletzten Überfliegerin Maike Kröger und der WM-Dritten Ariane Friedrich wird sich im Uni-Stadion ein heißer Kampf um die Rangfolge dahinter entwickeln. Die 1,90 haben in ihrer Karriere bereits Annett Engel (1,93 m) und Melanie Bauschke (1,90 m) gepackt, die sich damit Silber bei der U20-EM in Novi Sad holte. Desweiteren gehen noch einmal sieben Athletinnen mit Bestleistungen über 1,80 an den Start.</p>
<p><strong>Stabhoch</strong></p>
<p>Ein Wettbewerb, der in Regensburg schon immer gut war. Qualifikationsnormen wurden im Uni-Stadion stets in Serie gesprungen. Heuer werden dies Lisa Ryzih, mit der besten Vorleistung von 4,60 anreisend, Carolin Hingst, Joana Kraft und Anna Battke versuchen. Dabei muss die Latte mindestens bei 4,50 oben bleiben. 11 Athletinnen zeigen ihre Kunst mit Hausrekorden von 4,64 bis 4,16 m.</p>
<p class="textnote">Bildmaterial: Theo Kiefner</p>
<?php require("../_footer.dir1.inc.php"); ?>