<?php require("_header.inc.php"); ?>
			<table width="100%" border="0" cellspacing="0" cellpadding="0">
				<tr>
		  			<td><img src="images/kreis.gif" height="20" alt="" /></td>
		  			<td width="99%" class="newsTitle">
                    Anfahrt</td>
                  <td><img src="images/kreis-rechts.gif" height="20" alt="" /></td>
                </tr>
                <tr> 
                  <td colspan="3" class="news">
				    <p align="center">
					<br>
					<!-- Code generated by Map24 Codegenerator -->
				      <iframe src="http://www.map24.com/?q=m24cpnlFR7MvZGFXtjEplcjF9orDdqISm54HLxaX4G2F9Ri8PjghnLQCIFE2u0RMo6wA6HMlLzmhdxWpOaJedd85aIEWhv/uDoRhIm6sdn/A4MPgUp2i4Cor8RwVcq9u1a2KW4/A6PotRQTq0LFfocemEc_ePo78" width="200" height="216" scrolling="no" frameborder="0"></iframe>
				      <!-- Code generated by Map24 Codegenerator -->
			        </p>
				    <p><img src="images/anfahrt_klein.jpg" width="397" height="236" border="0"><br />
</p>
                    <p>BAB Nürnberg-Passau, Ausfahrt Klinikum, Richtung Zentrum, 
                      direkt hinter der Ausfahrt nach links abbiegen in die Josef-Engert-Straße, 
                      ca. 500 m bis zum Stadionparkplatz.<br>
                      <br>
                      Aus Richtung Weiden oder München auf der BAB Weiden-München 
                      bis zum Regensburger Kreuz, dort auf die BAB Nürnberg-Passau, 
                      Richtung Passau, Ausfahrt Klinikum (weiter s.o.)</p>
                    
                    <table cellspacing="0" cellpadding="0" width="100%">
                      <tr> 
                        <td valign="top" width="99%"> Sie erreichen Regensburg 
                          schnell und bequem mit ICE, EC, IC und IR-Zügen im direkten 
                          Verkehr auf den internationalen Achsen:<br /> <b>Amsterdam 
                          / Brüssel-Wien-Budapest</b><br /> <b>Zürich / Paris-Prag</b><br /> 
                          <br />
                          Auf den nationalen Direktlinien aus Richtung:<br /> 
                          <b>Berlin / Dresden, Hamburg / Hannover,</b><br /> <b>Dortmund 
                          / Köln, Frankfurt</b><br /> <b>Karlsruhe / Stuttgart 
                          und München</b> </td>
                        <td align="right" width="200"><a href="images/maps/db_large.gif" target="_blank"><img src="images/maps/db.gif" alt="zum Vergr&ouml;&szlig;ern klicken" border="0" /></a></td>
                      </tr>
                    </table>
                    <p>&nbsp;</p>
                  <p>&nbsp;</p></td>
                </tr>
                <tr height="20"> 
                  <td><img src="images/kreis.gif" height="20" alt=""></td>
                  <td class="newsTitle">Internationale Flughäfen</td>
                  <td><img src="images/kreis-rechts.gif" height="20" alt=""></td>
                </tr>
                <tr height="20"> 
                  <td colspan="3" class="news"><br>
                    <table cellspacing="0" cellpadding="0" width="100%">
                      <tr> 
                        <td width="99%" valign="top"> <b>Anfahrt: Flughafen Frankfurt/Main</b><br />
                          Pkw Anfahrt: 335km<br />
                          Eisenbahn / Bus: ca. 3,5 Stunden<br />
                          Direktverbindung Flughafen - Regensburg Hauptbahnhof<br /> 
                          <br /> <b>Anfahrt: Flughafen N&uuml;rnberg</b><br />
                          Pkw Anfahrt: 110km<br />
                          Eisenbahn / Bus: ca. 1 Stunden<br />
                          Bus/U-Bahn/Bahn<br /> <br /> <b>Anfahrt: Flughafen M&uuml;nchen/Erding</b><br />
                          Pkw Anfahrt: 85km<br />
                          Eisenbahn / Bus: ca. 1 Stunde Linienbus/Bahn<br />
                          oder direkte Busverbindung "Airport-Sprinter"<br /> 
                          <br /> </td>
                        <td align="center" width="200"><a href="images/maps/flughaefen_large.gif" target="_blank"><img src="images/maps/flughaefen.gif" alt="zum Vergr&ouml;&szlig;ern klicken" border="0" /></a></td>
                      </tr>
                    </table>                  </td>
                </tr>
              </table>		
<?php require("_footer.inc.php"); ?>