<?php require("_header.inc.php"); ?>
              <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr> 
                  <td><img src="images/kreis.gif" height="20" alt="" /></td>
                  
    <td width="83%" class="newsTitle">Elf deutsche Jahresbestleistungen bei Domspitzmilch Gala</td>
                  <td width="17%" class="newsDate">10. Juni 2007</td>
                  <td><img src="images/kreis-rechts.gif" height="20" alt="" /></td>
                </tr>
                <tr> 
                  <td colspan="4" class="news"><b>Zufriedene Gesichter bei den Offiziellen aber auch beim Ausrichter</b><br /> 
                    <p><font face="Arial, Helvetica, sans-serif" size="2"><img src="http://www.lg-regensburg.de/photos/Blum1_gala07-kiefnerfoto.jpg" width="182" height="272" hspace="6" vspace="2" align="left" />Regensburg, 10. Juni 2007 (orv) &ndash;  Elf deutsche Jahresbestleistungen konnten am Ende einer durchaus interessanten Domspitzmilch Gala am Samstag im Regensburger Uni-Stadion notiert werden. Nachdem zun&auml;chst heftiger Gegenwind die erhoffte Gro&szlig;tat von Sprintjungstar Christian Blum beim &uuml;berlegenen 100 m Sieg in 10,46 (VL 10,33) verhinderte, liefen die deutschen Sprinter/Innen wenig sp&auml;ter doch noch zur Hochform auf. Tobias Unger war mit seinem 200 m Sieg in 20,48 so stark wie vor zwei Jahren, Cathleen Tschirch n&auml;hert sich mit ihren 23,21 der WM-Norm (23,10), Langsprinterin Claudia Hofmann wiederholte ihren Vorjahressieg mit 52,45 und die beiden DLV-Sprintstaffeln buchten mit 38,77 und 43,47 ihr Ticket f&uuml;r Osaka, beide drei Hundertstel unter dem geforderten Richtwert des Verbandes. Annette Funck steigerte sich bei den Kurzh&uuml;rden auf 13,25, Langh&uuml;rdler Thomas Goller streifte mit 50,37 seit langer Zeit wieder einmal die 50-Sekunden-Schallmauer. Kollegin Tina Kron kann sich in der gleichen Disziplin mit 56,19 durchaus schon Gedanken &uuml;ber eine m&ouml;gliche WM-Qualifikation machen. Einen Zentimeter h&ouml;her als die Siegerin im letzten Jahr sprang Carolin Hingst mit 4,61 im Stabhochsprung, so hoch wie noch keine Deutsche in diesem Jahr. In seinem letzten Versuch machte Favorit Nils Winter eine Punktlandung auf genau acht Meter. So sah man denn am Ende durchaus zufriedene Gesichter bei den zahlreich vertretenen Verbandsoberen, unter ihnen auch der leitende Bundestrainer J&uuml;rgen Mallow und DLV Pr&auml;sident Dr. Clemens Prokop. Dies galt auch f&uuml;r den Ausrichter LG Domspitzmilch, dem bei fast tausend Teilnehmern erneut eine von allen Seiten gelobte Veranstaltung gelungen war.<br />
                        <br />
                        <img src="http://www.lg-regensburg.de/photos/Hingst1_gala07-kiefnerfoto.jpg" width="167" height="250" hspace="6" vspace="2" align="right" />Von den Jahrhundertbedingungen des Vorjahres war am Anfang der Domspitzmilch Gala wenig zu sp&uuml;ren. Das schon seit Tagen andauernde Hoch blies strammen Ostwind ins Stadion, sehr zum Nachteil der dagegen ank&auml;mpfenden Sprinter/Innen. Wenig beeindruckt zeigte sich davon Deutschlands derzeit schnellster Mann Christian Blum. &bdquo;Man muss auch bei Gegenwind schnell laufen k&ouml;nnen&ldquo;, forderte bereits in der Pressekonferenz sein Trainer Ewald Kaufmann, was der M&uuml;nchner zumindest im Vorlauf mit piksauberen 10,33 umsetzte. Im Fokus der noch recht ungewohnten ARD-Kameras tat sich die Gala anfangs doch recht schwer, so richtig in die G&auml;nge zu kommen. Als der Wind aber am sp&auml;ten Nachmittag etwas einschlief, erwachte Bayerns derzeit gr&ouml;&szlig;tes Meeting pl&ouml;tzlich, erst recht dann, als Schwabenpfeil Tobias Unger in unnachahmlicher Manier durch die Kurve flitzte und &uuml;ber 200 m mit gl&auml;nzenden 20,48 keinem anderen auch nur den Hauch einer Chance lie&szlig;. Stadionrekord, deutsche Jahresbestleistung und erste offizielle WM-Normerf&uuml;llung zugleich.<br />
                        <br />
Ab da flutschte es dann pl&ouml;tzlich auch wieder im organisatorischen Bereich. Eine in Regensburg ungew&ouml;hliche Zeitplan&uuml;berziehung von zwanzig Minuten wurde wett gemacht, die erneut fast zweitausend fachkundigen Zuschauer bekamen von da ab richtig gute Leichtathletik geboten und spendierten daf&uuml;r, stets angepeitscht vom guten Moderatoren-Qartett Andreas M&ouml;ckel, Konstantin Krause, Flo Weber und Mike Krispin, wohltuenden Beifall. Schade, dass am Ende nur noch die Insider den Kampf auf den langen 25 Runden der selten ausgetragenen 10.000 m mit erlebten, dann schon im glei&szlig;enden Licht der Scheinwerfer des Flutlichts. So bekamen auch die meisten nicht mehr mit, dass Lokalmatadorin Kaufmann als Zweite des abschlie&szlig;enden Rennens mit 35:53,46 einen neuen deutschen Rekord in der W45 aufstellte und damit ihr zweitbestes Ergebnis ihrer inzwischen 15-j&auml;hrigen Karriere ablieferte.<br />
<br />
<img src="http://www.lg-regensburg.de/photos/Unger1_gala07-kiefnerfoto.jpg" width="178" height="266" hspace="6" vspace="2" align="left" />Regensburger Siege sind bei der hohen Wertigkeit der Domspitzmilch Gala naturgem&auml;&szlig; ein Seltenheitsprodukt. Unmittelbar vor der Siebenkampf WM-Quali in Ratingen brachte Karin Ertl dieses Kunstst&uuml;ck im Weitsprung mit 6,18 m fertig. Ein weiterer, f&uuml;r den dies m&ouml;glich gewesen w&auml;re, stand traurig am Rand der Bahn herum. Jason Stewart, Ass auf den zwei Stadionrunden, hatte sich in Kassel verletzt und musste so bei seinem Heimspiel zuschauen. Triumph und Tragik k&ouml;nnen oft sehr nahe beieinander liegen. Diese Erkenntnis musste Hindernisl&auml;uferin Susi Lutz gewinnen. Nicht einmal zwei Sekunden fehlten der Domspitzmilch-Athletin am Ende bei erneuter Normerf&uuml;llung von 10:07,18 f&uuml;r eine sichere Qualifikation zur U23-EM in Debrecen. Direktkonkurrentin Carolin Lang, die in Dommelhof noch kr&auml;ftig von der Tempoarbeit der Regensburgerin profitiert hatte, zog diesmal wohl auf Grund der etwas schlechteren Bedingungen ihren Start zur&uuml;ck. Der direkte Vergleich fehlte.<br />
<br />
F&uuml;r viele wird die Gala 07 aber in guter Erinnerung bleiben, die hoffentlich 2008 zu einem Wiedersehen f&uuml;hrt, wenn es dann wahrscheinlich am 7. Juni hei&szlig;t, sich erneut zu bew&auml;hren. Regensburg hat durchaus bewiesen, dass die wahre Leichtathletik trotz vieler Marktspringen und laufender Massen auf den Stra&szlig;en, im Stadion stattfindet.<br />
<br />
                    </font><font size="1" face="Arial, Helvetica, sans-serif" class="note">Fotos:  Christian Blum, Tobias Unger und Carolin Hingst   bei der Gala 07 (Kiefner-Fotos)</font></p>                  </td>
                </tr>
              </table>
              <?php require("_footer.inc.php"); ?>