<?php require("_header.inc.php"); ?>
              <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr> 
                  <td><img src="images/kreis.gif" height="20" alt="" /></td>
                  
    <td width="83%" class="newsTitle">Regensburger Leichtathletik Gala lockt  deutsche Elite</td>
                  <td width="17%" class="newsDate">04. Juni 2007</td>
                  <td><img src="images/kreis-rechts.gif" height="20" alt="" /></td>
                </tr>
                <tr> 
                  <td colspan="4" class="news"><b>Meeting am 9. Juni im Regensburger Uni-Stadion leichtathletisches Highlight des Jahres</b><br /> 
                    <p><font face="Arial, Helvetica, sans-serif" size="2"><img src="photos/Ostwald,Ronny1_int.jpg" width="217" height="151" hspace="6" vspace="2" align="left" />Regensburg, 04. Juni 2007 (orv) &ndash;  Der 17. Juni des letztes Jahres war f&uuml;r das Regensburger Leichtathletikmeeting der absolute Wendepunkt. Nachdem der DLV fast die gesamte Europacup-Ausscheidung nach Regensburg vergeben hatte, lie&szlig; sich der Gro&szlig;teil der anwesenden deutschen Elite nicht lumpen und schoss ein sportliches Feuerwerk ab, das die Domstadt bis dato noch nicht erlebt hatte. Dreitausend Zuschauer sahen nicht weniger als letztendlich 14 deutsche Jahresbestleistungen, genauso viele wie deutsche Athleten/Innen bei der EM in G&ouml;teborg erzielten und erheblich mehr als bei jedem anderen deutschen Meeting einschlie&szlig;lich der Deutschen Meisterschaften in Ulm. Die Organisatoren nahmen daher das Angeot der deutschen Top-Veranstalter Serie &bdquo;german meeting&ldquo; gerne an, in Zukunft dem Verbund anzugeh&ouml;ren.</font></p>
                    <p>2007 geht nun die Gala in die zweite Auflage und wieder ist das Sportfest, die letzte Gelegenheit, sich f&uuml;r den Heim-Europacup in M&uuml;nchen zu qualifizieren. Anders, als im Jahr zuvor, k&ouml;nnen die daf&uuml;r in Frage kommenden Athleten/Innen sich aber auch schon bei einigen davor liegenden Meetings empfehlen. Nichts desto trotz wird die Gala in Richtung Europacup erneut eine zentrale Rolle spielen. Deutschlands Leichtathletik-Fachzeitschrift &bdquo;Leichtathletik&ldquo; schreibt dazu in ihrer Ausgabe vom 22. Mai dazu: &bdquo;Die Nominierung des Teams f&uuml;r den Europacup in M&uuml;nchen erfolgt am 11. Juni. Grundlage der Nominierung sind die bis dahin erbrachten Leistungen bei den festgelegten WM-Normwettk&auml;mpfen (Anmerkung: dazu z&auml;hlt Regensburg als german meeting automatisch seit 2007). Das bedeutet zum Beispiel f&uuml;r den 100 m Lauf, dass die Ergebnisse der Meetings von Rehlingen (28.5.), Dessau (1.6.), Zeulenroda (3.6.) und Regensburg (9.6.) z&auml;hlen. Da wahrscheinlich die sp&auml;teren Ergebnisse die leistungsst&auml;rkeren sein werden und auch n&auml;her zum EC-Termin liegen, werden sie besondere Bedeutung haben. Dies ist f&uuml;r 11 M&auml;nner- und 10 Frauenwettbewerbe in Regensburg der Fall.&ldquo;</p>
                    <p>Nachdem der DLV nun auf mehrere Meetings setzt, m&uuml;ssen die Veranstalter selbst f&uuml;r die Kosten der Athleten/Innen aufkommen, keine leichte Aufgabe f&uuml;r das kleinste german meeting in Regensburg und nur machbar mit Hilfe von gro&szlig;z&uuml;gigen Sponsoren. Mit gro&szlig;er Freude und Dankbarkeit sehen wir daher auch das Engagement der Sparkasse Regensburg als Hauptsponsor. Mit einem relativ schmalen Budget sinnvoll umzugehen, ist uns auch in diesem Jahr wieder gelungen.</p>
                    <p><font face="Arial, Helvetica, sans-serif" size="2"><img src="photos/Unger,Tobias1_200m-maenner_int.jpg" width="148" height="210" hspace="6" vspace="2" align="right" /></font>Auf Grund der hervorragenden Umst&auml;nde beim letzten Meeting haben einige Disziplinbl&ouml;cke des DLV voll auf Regensburg gesetzt. So auch der Bereich Sprint, der mit Bundestrainer Kaufmann immer wieder gerne nach Regensburg kommt und dessen besonderer Sch&uuml;tzling Christian Blum genau am 9. Juni in Regensburg zu Deutschlands schnellsten Mann aufsteigen will. Die gesamte etablierte Sprintkonkurrenz mit dem EM-Achten und letztj&auml;hrigen Gala-Gewinner Ronny Ostwald wird nat&uuml;rlich versuchen, dies zu verhindern.</p>
                    <p>Einige klangvolle Namen kann man schon jetzt pr&auml;sentieren, darunter der Schwabenpfeil Tobias Unger, in Fachkreisen als bester wei&szlig;er 200 m Mann bezeichnet. Oder auch Glamourgirl Sina Schielke, die nach langer Verletzungspause wieder an alte Sprintzeiten ankn&uuml;pfen k&ouml;nnte. Ren&eacute; Herms, der deutsche 800 m Meister ist dabei, ebenso Bastian Swillims, in Birmingham Vizeeuropameister in der Halle &uuml;ber die 400 m. Deutschlands einziger Achtmeterspringer des letzten Jahres Oliver K&ouml;nig will im Weitsprung versuchen, erneut &uuml;ber die magische Grenze zu kommen.</p>
                    <p>Nat&uuml;rlich ist auch die lokale Prominenz am Start. Hindernisl&auml;uferin Susi Lutz braucht auf ihrer Spezialdisziplin eine 10:08, um bei der U23 EM in Debrecen dabei sein zu k&ouml;nnen. Und 800 m Mann Jason Stewart ben&ouml;tigt eine Zeit unter 1:46,00, um sich erneut seinen WM-Traum in Osaka erf&uuml;llen zu k&ouml;nnen. Der Domspitzmilch-Mittelstreckler w&uuml;rde sich dann f&uuml;r das neuseel&auml;ndische Team qualifizieren. Stabhochsprungtrainer Herbert Czingon schickt fast die ganze deutsche Frauen-Elite ins Rennen. F&uuml;r diese hochwertige Crew k&ouml;nnte sich Regensburg besonders lohnen. Die ausgelobte Pr&auml;mie f&uuml;r eine erf&uuml;llte WM-Norm betr&auml;gt immerhin 500.- Euro und eine Handvoll der Springerinnen k&ouml;nnen das leisten.<br />
                        <br />
                        <font size="1" face="Arial, Helvetica, sans-serif" class="note">Fotos: Ronny Ostwald und Tobias Unger bei der Gala 06 (Kiefner-Fotos)</font></p>
                  </td>
                </tr>
              </table>
              <?php require("_footer.inc.php"); ?>