<?php require("_header.inc.php"); ?>
              <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr> 
                  <td><img src="images/kreis.gif" height="20" alt="" /></td>
                  
    <td width="83%" class="newsTitle">Tobias Unger: Von Regensburg nach Regensburg</td>
                  <td width="17%" class="newsDate">09. Mai 2007</td>
                  <td><img src="images/kreis-rechts.gif" height="20" alt="" /></td>
                </tr>
                <tr> 
                  <td colspan="4" class="news"><b>Nach einj&auml;hriger Verletzungspause beginnt Deutschlands Ausnahmesprinter dort, wo er im letzten Jahr aufgeh&ouml;rt hat</b><br /> 
                    <p><font face="Arial, Helvetica, sans-serif" size="2"><img src="http://www.lg-regensburg.de/photos/Unger,Tobias1-Gala06-kiefner.jpg" width="197" height="280" hspace="6" vspace="2" align="left" />Regensburg, 09. Mai 2007 (orv) &ndash;  Alle Zeichen standen Richtung EM, damals bei der Europacupausscheidung an jenem 17. Juni im Regensburger Uni Stadion. Alles schien f&uuml;r Deutschlands Ausnahmesprinter Tobias Unger glatt zu laufen. Trotz leichtem Gegenwind machte er &uuml;ber 200 m mit 20,65 eine Punktlandung mit einer hundertstelgenauen Normerf&uuml;llung. Alles schien gerichtet, doch Tobias Ungers K&ouml;rper sagte nein. Eine langwierige Verletzung zwang ihn zur einj&auml;hrigen Pause. Aus der Traum vom Europameistertitel. </font></p>
                    <p><font face="Arial, Helvetica, sans-serif" size="2">Tobias Unger ist nun wieder fit. Eine Stippvisite bei den Penn Relays Ende April in den USA, wo er mit der deutschen Staffel gleich einmal 39,65 auf das Tartanoval brachte, lie&szlig;en letzte Zweifel verfliegen. Mit ihm ist wieder zu rechnen. Schon im erweiterten Vorfeld hat er seine Pl&auml;ne preis gegeben. Dort, wo im letzten Jahr alles endete, will er wieder zu neuen Taten ansetzen, gleich einmal in Regensburg die WM-Norm von 20,59 packen.</font></p>
                    <p><font face="Arial, Helvetica, sans-serif" size="2">Sein Trainer Micky Corucle, ein ganz genauer seiner Branche, treibt f&uuml;r solch hohe Ans&auml;tze stets ganz genaue Ortsrecherchen. &bdquo;Das Stadion, seine Lage und die geographische Einbindung schaue ich mir immer auf google earth an&ldquo;. Und trotzdem, irgendwie bleibt er meist ein wenig skeptisch. &bdquo;Selbst wenn alle L&auml;ufe R&uuml;ckenwind haben, ist es bei Tobias oft wie verhext&ldquo;, unkte er schon vor der letztj&auml;hrigen Gala. Recht hatte er. An einem Tag mit traumhaften Windverh&auml;ltnissen f&uuml;r alle Sprints, einschlie&szlig;lich der 200 m L&auml;ufe, war Tobias Ungers Lauf der einzige mit 0,1 m/sec Gegenwind. Zugegeben, ein Hauch, aber es h&auml;tten auch 1,5 m/sec R&uuml;ckenwind sein k&ouml;nnen. Dann w&auml;ren es sicher statt der 20,65 vielleicht eine 20,49 oder mehr geworden. </font></p>
                    <p><font face="Arial, Helvetica, sans-serif" size="2">Dar&uuml;ber, dass der Kornwestheimer das kann, besteht &uuml;berhaupt kein Zweifel. 2005, in seinem bisher besten Jahr, lief er eine 10,16 &uuml;ber die 100 m und auf seiner Hausstrecke, den 200 m, stellte er mit einer 20,20 einen deutschen Rekord auf. Bei der WM in Helsinki reichte es immerhin wieder zum Endlauf, wo er erneut wie schon bei Olympia 2004 Platz sieben belegte. Zuvor schon hatte er sich bei den Hallen-Europameisterschaften in Madrid seinen ganz pers&ouml;nlichen Goldtraum erf&uuml;llt. Zum letzten Mal stand seine Paradedisziplin bei internationalen Indoor-Meisterschaften auf dem Programm und Tobias Unger nutzte die Chance, letzter Hallen-Europameister &uuml;ber die 200 m zu werden. </font></p>
                    <p><font face="Arial, Helvetica, sans-serif" size="2">Regensburg ist nun ein Neubeginn. Von Regensburg bis Regensburg dauerte die lange Leidenszeit, von Regensburg aus soll es nun via Europacup M&uuml;nchen direkt nach Osaka zur WM gehen, m&ouml;glichst gleich mit einem ganz schnellen Einstand unter den von der IAAF geforderten 20,59. Sicher gibt es dann noch einen weiteren ganz gro&szlig;en Traum in Tobi Ungers Sprinterleben. 19,99 ist eine magische Zahl f&uuml;r wei&szlig;e Sprinter. Im Hinterkopf wird er diese Zahl sicher immer haben, zumal dann, wenn er an Olympia 2008 denkt. </font><br />
                        <br />
                        <font size="1" face="Arial, Helvetica, sans-serif" class="note">Foto: Tobias Unger bei der Domspitzmilch Gala 2006 (Kiefner-Foto) </font></p></td>
                </tr>
              </table>
              <?php require("_footer.inc.php"); ?>