<?php require("_header.inc.php"); ?>
              <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr> 
                  <td><img src="images/kreis.gif" height="20" alt="" /></td>
                  
    <td width="83%" class="newsTitle">Vom Zauberlehrling zum Meister</td>
                  <td width="17%" class="newsDate">10. Mai 2007</td>
                  <td><img src="images/kreis-rechts.gif" height="20" alt="" /></td>
                </tr>
                <tr> 
                  <td colspan="4" class="news"><b>Kann Christian Blum die Vorherrschaft im deutschen Sprint &uuml;bernehmen?</b><br /> 
                    <p><font face="Arial, Helvetica, sans-serif" size="2"><img src="http://www.lg-regensburg.de/photos/Blum1_watter06-lutzfoto.jpg" width="276" height="165" hspace="6" vspace="2" align="left" />Regensburg, 10. Mai 2007 (orv) &ndash;  Regensburg ist f&uuml;r den Neubrandenburger Christian Blum, der vor drei Jahren nach M&uuml;nchen umgesiedelt ist, keine fremde Stadt. Nicht nur, dass er hier viel und gerne seine Sprintwettbewerbe l&auml;uft, sondern auch ganz privat. Seit Kaunas 2005, als er dort mit der deutschen U20-Sprintstaffel Junioreneuropameister wurde, ist er mit seiner Susi verbandelt, die dort im Baltischen auf ihrer Spezialdisziplin, den 3000 m Hindernis, die Bronzemedaille holte. Un die ist nun mal auch aus Regensburg. </font></p>
                    <p><font face="Arial, Helvetica, sans-serif" size="2"><img src="http://www.lg-regensburg.de/photos/Blum,Christian1_dm-halle07.jpg" width="162" height="230" hspace="6" vspace="2" align="right" />Regensburg hat aber heuer am 9. Juni, wenn just Deutschlands beste Sprinter ihre Vertreter f&uuml;r den heimischen Europacup in M&uuml;nchen suchen, eine ganz besondere Bedeutung f&uuml;r ihn. Sein Heimtrainer Ewald Kaufmann hat den Jungspunt behutsam aufgebaut. In der Halle muckte Christian Blum schon einmal m&auml;chtig. Zum ersten Mal probte er so richtig den Aufstand der Jungen. Zeiten um die 6,60 &uuml;ber die ultrakurzen 60 m lie&szlig;en hohes Talent erkennen, f&uuml;r Deutschlands etablierte Sprintgarde in diesem Winter einfach zu schnell, auch f&uuml;r Ronny Ostwald den Altmeister. Die logische Folge: Schon im ersten Juniorenjahr wurde Christian Blum deutscher Meister in der M&auml;nnerklasse. </font></p>
                    <p><font face="Arial, Helvetica, sans-serif" size="2"><img src="http://www.lg-regensburg.de/photos/Ostwald,Ronny7_gala06.jpg" width="219" height="146" hspace="6" vspace="2" align="left" />Ronny Ostwald jubelte noch im Jahr zuvor im Uni-Stadion wie kein anderer. 10,24 war er noch nie gelaufen, die Endlaufteilnahme in G&ouml;teborg folgte. Regensburg im Juni 2007 hat auch er fest im Plan. Was in der Halle galt, muss nicht auch im Sommer sein. Der gro&szlig;e Herausforderer in diesem Jahr hei&szlig;t Christian Blum. Der Kronprinz greift nach der Krone. Diesmal ist die Strecke hundert Meter lang. Welche Rolle spielen die Alteingesessenen Marc Blume, Marius Broening und Alexander Kosenkow? Welche die weiteren Jungstars mit Julian Reus und Martin Keller?</font></p>
                    <p><font face="Arial, Helvetica, sans-serif" size="2"> Derweil Christians Prinzessin wenig Zeit haben wird an jenem 9. Juni. Sie muss n&auml;mlich ebenfalls ran. Die U23-EM-Norm &uuml;ber 3000 m Hindernis ist zu knacken. Na ja, ein bisschen wird sie ihm trotzdem die Daumen halten. Drei Stunden sp&auml;ter, beim hei&szlig;en Ritt &uuml;ber die B&ouml;cke wird wohl ein recht nerv&ouml;ser Sprinter am Rand ganz toll mitzittern. Damit sie wieder zu zweit durch die Stra&szlig;en von Debrecen schlendern k&ouml;nnen, dann, wenn im Juli abermals Junioreneuropameisterschaften anstehen. </font></p>
                    <p><font face="Arial, Helvetica, sans-serif" size="2">Nach Japan, Ende August, wird der M&uuml;nchner dann alleine fliegen m&uuml;ssen. Sein Platz in der 4x100 m Staffel sollte kein Thema sein. Auch hier wird in Regensburg flei&szlig;ig geprobt. Ob der Normwert bereits in der Domstadt gelaufen wird, bleibt offen. Osaka ist f&uuml;r Christian Blum nicht nur ein Wunschtraum, Osaka ist durchaus ein &auml;u&szlig;erst realistisches Ziel. F&uuml;r sein Regensburger M&auml;del weniger. Eine 9:48 ist in diesem Jahr wohl kaum machbar und den Vorteil einer leichten R&uuml;ckenwindbrise gibt es &uuml;ber die beschwerlichen siebeneinhalb Runden nicht. Eines hat sie ihrem Christian aber dennoch voraus. Ihr Abitur baute sie bereits im letzten Jahr, da muss er heuer auch noch durch. </font><font face="Arial, Helvetica, sans-serif" size="2"></font><br />
                        <br />
                        <font size="1" face="Arial, Helvetica, sans-serif" class="note">Fotos: Christian Blum enteilt dem Feld, mit der Goldmedaille von der Hallen-DM 07 - Ronny Ostwald jubelt &uuml;ber eine 10,24 bei der Gala 06 (Kiefner-Foto)</font></p></td>
                </tr>
              </table>
              <?php require("_footer.inc.php"); ?>