<?php $title = "Die Sparkassen Gala lebt";
 $menu['current'] = "news"; ?>
  <?php require("../_header.dir1.inc.php"); ?>

	<h2>Die Sparkassen Gala lebt</h2>

  <p><strong>Regensburger Traditionsmeeting nur mit kleinen Abstrichen</strong></p>

  <p><img class="float_left" title="Corinna Harrer (Brüssel-Foto)" alt="Corinna Harrer Gala16 Brüsselfoto" src="http://lg-telis-finanz.de/images/stories/2016/Harrer-Kock1_Gala16_Bruesselfoto.jpg" width="223" height="134">Regensburg, 11. April 2017 (orv/lgr) -  Den Regensburger Meetingmachern ist es trotz aller dunkler Vorzeichen gelungen, die Sparkassen Gala 2017 auf solide Beine zu stellen. Dass dies so ohne Weiteres möglich sein wird, war in den vergangenen Wochen und Monaten nicht unbedingt ersichtlich. „Die ein oder anderen Abstriche müssen wir natürlich beim Gesamtevent machen, was aber kaum zu Lasten der sportlichen Qualität gehen wird,“ so Jochen Schweitzer, Cheforganisator der Sparkassen Gala. Worauf Leichtathletikfans in diesem Jahr in Regensburg  verzichten müssen, ist der seit Jahren zur Verfügung gestellte Live-Stream. Ebenso fiel der VIP-Bereich für die Ehrengäste zum Opfer des Rotstiftes, den das Organisationsteam ansetzen musste. Dennoch können die Zuschauer, Gäste und Athleten sich auf aus nationaler Sicht leichtathletischen Hochgenuss freuen, der am 10. Juni mit der Laufnacht beginnt und am 11.06 mit der Sparkassen Gala als Höhepunkt ausklingt.<br /><br />
  Dabei geht es natürlich wieder in vielen Disziplinen im Aktiven- und Nachwuchsbereich um die begehrten Plätze zur Team-EM sowie um die Normen für die Höhepunkte der Saison, die Leichtathletik WM in London oder auch eine der diversen internationalen Nachwuchsmeisterschaften der EAA oder IAAF. Dass Veranstaltungen dieses Formats für die deutsche Leichtathletik und hier insbesondere für den Nachwuchs besonders wichtig sind, ist sich Jochen Schweitzer, der auch als Präsident des Süddeutschen Leichtathletikverbandes sowie Bezirksvorsitzender Oberbayerns fungiert,  sicher. Große Hoffnung setzt er deswegen auf ein Treffen zwischen einem von ihm initiierten Treffen der German Meetings, einem Zusammenschluss der wichtigsten deutschen Leichtathletikveranstaltungen, und Vertretern des DLV. Hier will man besprechen, wie man in Zukunft den Meeting- bzw. Veranstaltungsstandort Deutschland sichern und in eine bessere Zukunft führen kann, denn eines ist klar: Das Meetingsterben, das seit nunmehr 10 Jahren  unaufhörlich voranschreitet, muss gestoppt werden.</p>
    <?php require("../_footer.dir1.inc.php"); ?>
