<?php $title = "Wer macht in Regensburg die Pace?";
 $menu['current'] = "news"; ?>
  <?php require("../_header.dir1.inc.php"); ?>

	<h2>Wer macht in Regensburg die Pace?</h2>
  <p><strong>Telis-Laufelite stellt sich zu Hause in Diensten der Nation</strong></p>

  <p><img class="float_left" title="Huber Ludolph Gala16 Kiefner Foto" alt="Huber Ludolph Gala16 Kiefner Foto" src="http://lg-telis-finanz.de/images/stories/2016/Huber-Ludolph_Gala16_Kiefner-Foto.jpg" width="162" height="164">Regensburg, 28. Mai 2017 (orv) –  Zum 20. Mal findet am 11. Juni im Regensburger Uni-Stadion die Leichtathletik Gala statt. Die einen Tag vorher ablaufende „Laufnacht“ gehört inzwischen schon fast traditionell dazu. Anfangs hieß das Sportfest Bayern Gala, später dann Domspitzmilch Gala und ab 2008 „Sparkassen Gala“. 2006, als der damalige Cheftrainer Jürgen Mallow fast die gesamte deutsche Ausscheidung für die Team-EM nach Regensburg verlegte, weil kein anderer nationaler Ausrichter wegen den hierzulande stattfindenden Fußball-Weltmeisterschaften sie veranstalten wollte, schaffte das Sportfest seinen Durchbruch. Inzwischen ist das Meeting recht lauf- und sprintlastig, meist mit tollen Hochsprüngen garniert. Da stellt sich natürlich in Zeiten der ewigen Normenhatz stets die Frage: Wer macht das Tempo in den einzelnen Läufen? Es ist schon längst kein Geheimnis mehr, dass diese Spezies der sportlichen Dienstleister mitunter die teuersten Athleten/Innen eines Meetings sind. Da man in Regensburg nicht erst seit gestern jeden Cent umdrehen muss, hat man aus der Not eine Tugend gemacht. Die gewiss nicht schlechte Läuferschar übernimmt einfach diese Aufgabe.<br /><br />
  Vor allem in der Laufnacht will man Deutschlands Talente wieder zu schnellen Zeiten verhelfen. Über 1500m wird kein Geringerer als der Deutsche 10.000m Meister Simon Boch ein Tempo für 3:45min einschlagen. Vielleicht, ja vielleicht, wenn er bis dorthin seinen hartnäckigen grippalen Infekt auskuriert hat und nicht nach Hengelo fährt, hilft dazu auch Olympiastarter Florian Orth. Die 3000m führt Felix Plinke Richtung 8:15min, bei den Mädchen wird‘s Richtung 9:25 Minuten gehen und über 5000m stellen sich Olympia-Marathoni Philipp Pflieger und Jonas Koller in den Dienst der Läufer für eine Richtzeit knapp unter 14 Minuten. Bei den Mädels wird Hindernisläuferin Cornelia Griesche nach ihren dann hoffentlich erfolgreichen Start sechs Tage vorher in Prag ebenso im 1500m Lauf zur Verfügung stehen. <br /><br />
  Am Sonntag bei der Sparkassen Gala soll der 800m Lauf Richtung WM-Norm gehen. Holger Körner wird wie schon im Vorjahr dazu passend anlaufen. Über 1500m wird die Pace Richtung 3:42-40 Minuten gehen, bei den Frauen Richtung 4:13 Minuten schon im eigenen Interesse der regionalen Topleute gehen. Lediglich über 800m der Frauen müssen noch Gespräche geführt werden. „Natürlich wissen wir im Süden der Republik, dass Regensburg für die Leute aus dem Ruhrpott verdammt weit im Süden liegt und Oordegem, Heusden oder Nijmwegen fast vor der Haustür, aber wo bekommt man schon die Möglichkeit auf einen Doppelstart hoher Qualität am Samstag und Sonntag“, sagt Meeting-Direktor Kurt Ring dazu, „im Zeichen der Normen- und Bestzeitenhatz wird bisweilen vergessen, dass sich bei Meisterschaften oft eine ganz andere Rennsituation schon allein mit Vorlauf und Endlauf - und das ohne Pacemaker - darstellt.“ In Regensburg ist jedenfalls wieder alles hergerichtet für schnelle Zeiten, tolle Fights Frau gegen Frau und Mann gegen Mann und an adäquater internationaler Konkurrenz fehlt es auch nicht.
  </p>
      <?php require("../_footer.dir1.inc.php"); ?>
