<?php $title = "Die Sparkassen Gala glänzt wieder mit einer tollen Besetzung";
 $menu['current'] = "news"; ?>
  <?php require("../_header.dir1.inc.php"); ?>

	<h2>Die Sparkassen Gala glänzt wieder mit einer tollen Besetzung</h2>
  <p><strong>Wer schafft in Regensburg den Sprung zu den Weltmeisterschaften nach London?</strong></p>

  <p><img class="float_left" title="Huber, Ludolph (Kiefner Foto)" alt="Huber, Ludolph (Kiefner Foto)" src="http://lg-telis-finanz.de/images/stories/2016/Huber-Ludolph_Gala16_Kiefner-Foto.jpg" width="162" height="164">Regensburg, 07. Juni 2017 (orv) –  Das Regensburger Uni-Stadion ist nicht nur bei deutschen Top-Athleten/Innen ein Geheimtipp für gute Leistungen. Auch am kommenden Sonntag wollen wieder viele nationale Spitzenleute, darunter etliche, die sich die Qualifikation für die Weltmeisterschaften in London zutrauen, ihre gesteigerte Leistungsfähigkeit unter Beweis stellen und treffen dabei auf Konkurrenz aus 22 Nationen. Große Namen sind darunter wie der deutsche Rekordhalter im Sprint Julian Reus (TV Wattenscheid 01), der deutsche Meister und EM-Zehnte über 800m Benedikt Huber vom Ausrichter LG Telis Finanz, die Olympiateilnehmerin über 200m Nadine Gonska (MTG Mannheim) mit einem Hausrekord von 22,79sec, die deutsche 400m Hürdenmeisterin Jackie Baumann (LAV Stadtwerke Tübingen), die beiden deutschen 400m-Asse Ruth Sophia Spelmeyer (VfL Oldenburg) und Laura Müller (LC Rehlingen), beide mit Bestzeiten deutlich unter 52 Sekunden, und last not least die 1500m-EM-Sechste Maren Orth von der heimischen LG Telis Finanz. Internationalen Flair ins Uni-Stadion bringen Sprinter Anaso Jobodwana aus Südafrika mit 10,10 und 19,87sec über 100 und 200m gemeldet, 400m Hürdenmann Milud Rhamani (Algerien), dessen Hausrekord bei 49.64 Sekunden steht, die beiden kuweitischen Hürdensprinter Abdulaziz Al Mandeel und Yaqoub Al Youha, mit ausgezeichneten 13,39 und 13,48 Sekunden notiert, die Britin Bianca Williams, ebenso schon unter 23 Sekunden über 200m gelaufen, die 1:58,63-Läuferin Winnie Nayondo aus Uganda und die 6,49-Weitspringerin Ivona Dadic aus Österreich.<br /><br />
  <strong>Die Sprintentscheidungen mit garantiertem Rückenwind über die 100m</strong><br />
  <img class="float_left" title="Reus (Kiefner Foto)" alt="Reus (Kiefner Foto)" src="http://lg-telis-finanz.de/images/stories/2017/Reus_Sparkassen-Gala16_KiefnerFoto_internet.jpg" width="197" height="130">Sehr schnell könnte es zumindest bei den Herren über 100m werden, weil man eben in Regensburg immer die Laufrichtung wählt, die Rückenwind garantiert. Der deutsche Meister Julian Reus will natürlich wie schon im letzten Jahr eine Zeit jenseits der internationalen Norm abgeben, Dabei muss er schneller als 10,12 Sekunden sein. Er trifft auf harte Konkurrenz mit Anaso Jobodwana aus Südafrika.  Auch die deutschen Sprint-Asse Aleixo Platini Menga, Lucas Jakubczyk, Alexander Kosenkow, Jens Knipphals, sowie der Brite Andrew Robertson wollen mitmischen wenn es um Zeiten unter 10,20 Sekunden geht. Alle Asse wollen am Ende des Meetings auch noch die 200m in Angriff nehmen, wo  Anaso Jobodwana durchaus in der Lage sein sollte, den Uralt-Stadionrekord von Tobias Unger (20,48sec) anzugreifen. Bei den Frauen ist die Leistungsdichte zumindest auf den 100m nicht so groß. Unter 11,30 Sekunden heißt das Ziel für Anna-Lena Freese, Josefine Elsler und Nadine Gonska. Konkurrenz kommt Monae Taylor Evans aus Südafrika. Über 200m sollte die Südafrikanerin mit einem Hausrekord von 23,15sec ebenso wie Nadine Gonska und Bianca Williams an der 22er-Zeit kratzen können. Aus deutscher Sicht ist man gespannt, ob das auch Josefina Elsler (pB 23,16) und Lara Matheis (pB 23,19sec) können. Auch die deutschen Sprint-Nationalstaffeln wollen wieder testen.<br /><br />
  <strong>Die Regensburger Stadionrunde, immer mal gut für unter 46 und unter 52 Sekunden</strong><br />
  <img class="float_left" title="Spelmeyer (Kiefner Foto)" alt="Spelmeyer (Kiefner Foto)" src="http://lg-telis-finanz.de/images/stories/2017/Spelmeyer_400m-Frauen_KiefnerFoto.jpg" width="137" height="209">Die beiden bayerischen Läufer Johannes Trefz (LG SW München – pB 46,02sec) und Patrick Schneider (LAC Quelle Fürth – pB 46,07sec) sind besonders scharf drauf, endlich vor dem Komma die „45“ aufleuchten zu sehen mit der Garantie, dann fast einen bombensicheren Staffelplatz bei den in 14 Tagen in Lille stattfindenden Team-Europameisterschaften ergattert zu haben. Wer dann von den deutschen Männern noch in der deutschen 4x400m Staffel stehen wird, entscheidet sich ebenfalls im Uni-Stadion. Bei den Frauen könnte es zumindest bei Ruth Sophia Spelmeyer nicht nur um eine 51er-Zeit gehen, sondern vielleicht auch schon um einen Startplatz für London. Nach dem Rehlinger Pfingstauftritt von Laura Müller mit 53,27sec sollte man so einen Doppelschlag von ihr noch nicht erwarten. Starke Konkurrenz kommt mit Victoria Ohuruogu (pB 52,71sec) aus Großbritannien und Lara Hofmann, der deutschen Hallenmeisterin (pB 52,87sec), aus Köln. Auch hier geht es um die Plätze für die 4x400m-Staffel in Richtung Team-EM.<br /><br />
  <strong>Kurzhürden der Damen in der Domstadt von je her gut besetzt</strong><br />
  Neben den beiden Kuweitis Abdulaziz Al Mandeel und Yaqoub Al Youha stehen über 110m Hürden (110m Hürden Entscheidung bereits um 12.30 Uhr) auch zwei Athleten aus Saudi Arabien an der Startlinie. Ahmen Al-Moualed und Mahdi Abdullah Al-Othman bringen persönliche Bestleistungen von 13,68 und 13,78 Sekunden mit. Rene Jonathan Mählmann vom SV Schlau.com Saar 05 Saarbrücken wird sich mit seinem Hausrekord von 13,79 Sekunden strecken müssen, um da mitzukommen. Bei den Frauen über 100m Hürden kann man den beiden deutschen Topläuferinnen Ricarda Lobe (MTG Mannheim) und Franziska Hofmann (LAC Erdgas Chemnitz) den Sieg zutrauen. Im letzten Jahr blieb die Mannheimerin immerhin mit 12,89 Sekunden deutlich unter der diesjährigen WM-Norm, was bei der Güte der derzeitigen deutschen Spitze im Frauen-Hürdensprint aber noch gar nicht für London reichen würde. Schärfste Konkurrentinnen der beiden sind die Österreicherin Stephanie Bendrat (pB 13,11sec) und Monika Zapalska (TV Wattenscheid 01 – pB 13,21sec), Auch über 100m Hürden gibt es den garantierten Rückenwind.<br /><br />
  <strong>Schafft Jackie Baumann hier in Regensburg das Ticket für London?</strong><br />
  „Olympia 2.0“ hat Jackie Baumann, Tochter von Dieter Baumann als 400m Hürden-Teilnehmerin in Rio bereits für die Familie Baumann klar gemacht. In Rehlingen ist sie an Pfingsten an den für die WM geforderten 56,00 Sekunden mit 56,05sec nur hauchdünn gescheitert. Folgt nun in Regensburg der große Coup? Eilen Demes vom TV 1861 Neu-Isenburg (pB 57,13) und Djamila Böhm vom ART Düsseldorf sollen sie dorthin treiben. Auch Laura Gläsner (VfL Eintracht Hannover) und Christine Saltenberg (LT DSHS Köln) haben Hausrekorde unter 58 Sekunden stehen. Deutschlands Langhürdler haben schon bessere Zeiten gesehen. Viele Verletzungen verhinderten in letzter Zeit bei Georg Fleíschhauer (LG Eintracht Frankfurt) und Felix Franz (LG Neckar-Enz), wieder an alte Zeiten mit 49er Zeiten anschließen zu können. Mit 48,96 Sekunden blieb der Schwabe 2014 als EM-Fünfter in Zürich sogar schon mal unter 49 Sekunden. Der Weg zum Sieg führt aber über die beiden Algerier Milud Rhamani (pB 49,64sec) und Saber Boukemouche (pB 50,01sec).<br /><br />
  <strong>Auf den Mittelstrecken mischen auch die heimischen „Blauhemden“ mit</strong><br />
  <img class="float_left" title="Orth (Kiefner Foto)" alt="Orth (Kiefner Foto)" src="http://lg-telis-finanz.de/images/stories/2017/KockMaren1_1500m-Frauen_KiefnerFoto_internet.jpg" width="130" height="198">Unvergessen werden in der Geschichte der Regensburger Gala stets die großen Auftritte der einheimischen Läuferinnen und Läufer stehen. Corinna Harrer, Maren Orth, unter ihrem Mädchennamen Kock dem Publikum noch besser bekannt, sowie Florian Orth sorgten in den letzten Jahren für Spitzenleistungen und so manch unerwarteten Sieg. In diesem Jahr überstrahlt zwar die Vorleistung von 800m Läuferin Winnie Nanyondo aus Uganda mit 1:58,63 Minuten alles übrige, doch auch aus nationaler Sicht wird es ganz interessant, weil sich Sarah Schmidt (TSV Bayer Leverkusen) in einem schnellen Rennen nahe ihrer bisherigen Bestleistung von 2:01,80min für die U23-EM empfehlen könnte. In gleicher Region können die Slowakin Alexandra Stukova (pB 2:02,91) und Emily Dudgeon Aus Großbritannien (pB 2:03,00) eingeordnet werden. Aus Regensburger Sicht ist natürlich das Rennen der Männer mit dem Deutschen Meister und EM-Zehnten Benedikt Huber von der LG Telis Finanz von noch größerem Interesse. Im letzten Jahr ist er seine Jahresbestleistung hier bei der Sparkassen Gala gelaufen. In diesem Jahr will er natürlich noch schneller als 1:46,57min laufen. Sein Traum heißt 1:45,90 Minuten. Es wäre die Norm für die WM. Für den nötigen Druck sollen der derzeitige deutsche Jahresbeste Christoph Kessler (LG Region Karlsruhe – 1:46,72min), der Schweizer Hugo Santacruz (pB 1:46,68min) und das österreichische Nachwuchstalent Nikolaus Franzmair (pB 1:46,78) sorgen. Die beiden 1500m Rennen werden in diesem Jahr nicht ganz so schnell. Bei den Damen stehen die beiden Telis-Läuferinnen Maren Orth und Julia Kick, beide 2017 schon 4:14er Zeiten gelaufen an der Spitze des Meldefeldes, zusammen mit der Berlinerin Caterina Granz (LG Nord), die eine persönliche Bestleistung von 4:13,22 Minuten mitbringt. Internationalen Touch bringt die Dänin Line Schulz (pB 4:14,66min) ins Rennen. Bei den Herren werden sich der Schwede Elmar Engholm, der Pole Piore Drobnik sowie die beiden Deutschen Tim Hoenig (Hamburg Running) und Stefan Hettich (TSV Gormaringen) im Dunstkreis von 3:40 Minuten um den Sieg streiten. Hecht im Karpfenteich sollte Telis-Senkrechtstarter Simon Boch sein.<br /><br />
  <strong>Erneut hochwertige Hochsprünge im Uni-Stadion</strong><br />
  <img class="float_left" title="Gröll (Kiefner Foto)" alt="Gröll (Kiefner Foto)" src="http://lg-telis-finanz.de/images/stories/2017/GroellLaura1_Hoch-Frauen_KiefnerFoto_internet.jpg" width="216" height="143">Geht’s im Uni-Stadion im Hochsprung wirklich um die WM-Norm von 2,30m? Durchaus dazu in der Lage wäre an einem guten Tag der Leverkusener Mateusz Przybylko, der 2015 diese Höhe schon mal überwunden hat, aus dem letzten Jahr 2,29m mitbringt und Ende Mai in Weinheim eine 2,26 angeboten hat. Bayerns Nachwuchstalent Lucas Mihota (SB DJK Rosenheim) will auf dem Weg zur U20-EM seine 2,23m sicherlich noch ausbauen. Weitere drei 2,20-Springer sind mit Tim Schenker (LAC Erdgas Chemnitz), Tobias Potye (LG SW München), zudem Kandidat für die U23-EM und Martin Günther (VfB Stuttgart) am Start. Bei den Frauen sollte Marie-Jossie Graumann (LG Nord Berlin, pB 1,92m) in der Lage sein, Höhen über 1,90m anzubieten. Für die Bayerin Laura Gröll (LG Eckental) sind solche Höhen mit einer Vorjahresleistung von 1,88m durchaus ein greifbares Ziel. Als Athletin des Jahrganges 1998 geht die Zielsetzung Richtung U20-EM in Grosseto. In den beiden Weitsprüngen führen die Österreicherin Ivona Dadic und der Passauer Maximilian Entholzner (1. FC) mit 6,47m und 7,92m die Meldeliste an.
  </p>
      <?php require("../_footer.dir1.inc.php"); ?>
