<?php $title = "Telis-Asse sollen DLV-Nachwuchs zur EM führen";
 $menu['current'] = "news"; ?>
  <?php require("../_header.dir1.inc.php"); ?>

	<h2>Telis-Asse sollen DLV-Nachwuchs zur EM führen</h2>
  <p><strong>Die Laufnacht der LG Telis Finanz verspricht tollen Nachwuchssport und nicht nur diesen</strong></p>

  <p><img class="float_left" title="Miri Dattke (Kiefner Foto)" alt="Miri Dattke (Kiefner Foto)" src="http://www.lg-telis-finanz.de/images/stories/2017/DattkeMiriam1_Berlin-5000m-2017_Kiefnerfoto.jpg" width="107" height="163">Regensburg, 07. Juni 2017 (orv) –  Deutschlands Nachwuchselite im Bereich Lauf kommt gerne zur Laufnacht der LG Telis Finanz ins Regensburger Uni-Stadion. Dem trägt auch der Deutsche Leichtathletik-Verband Rechnung. Er hat bei der Veranstaltung am kommenden Samstag im Regensburger Uni-Stadion die letzte entscheidende Ausscheidung für seine Jungtalente in Richtung U20-Europameisterschaften vom 20.-23. Juli im italienische Grosseto angesetzt. Danach geht nichts mehr. Schon die Sonntagswettbewerbe der Sparkassen Gala werden dann nicht mehr für die Nominierung berücksichtigt. Die perfekte Organisation, das stets zu dieser Zeit ideale Laufwetter und nicht zuletzt die mustergültigen Tempi der Pacemaker, in diesem Falle gestellt von der gesamten Laufelite der LG Telis Finanz, sorgen für Rahmenbedingungen, die Bestzeiten en masse fast schon garantieren. Den Abschluss werden erneut die 5000m-Läufe der Frauen und Männer mit einer feinen internationalen Besetzung von 21 bis 22 Uhr bilden.<br /><br />
  „Wer als Läufer nicht nach Regensburg kommt, ist selbst schuld  und hat echt etwas verpasst“, sagte vor Jahren schon der Nachwuchstrainer für die Hindernisstrecken Enrico Aßmuss. Gesagt, getan. So werden über 800m der U20 Pascal Kleyer (LG Region Karlsruhe – pB 1:47,85min), der Cottbuser Constantin Schulz (1:50,01min) und der Gießener Niklas Harsy (1:50,84min) um die Fahrkarten nach Grosseto kämpfen, garniert mit Tilen Simenko Lalic aus Slowenien und Paul Seyringer aus Österreich und geführt vom Telis-Ass Simon Boch in Richtung neuer Rekordzeiten. Bei den Mädchen hat die Karlsruherin Jana Reinert mit ihrer diesjährigen Bestleistung von 2:04,66min eigentlich den EM-Startplatz schon sicher, 2016 ist aber ihre direkte Konkurrentin Alina Ammann (Tus Esingen) mit 2:03,57min schon mal schneller gelaufen. Die Pace wird keine Geringere als die mehrfache deutsche 1500m-Meisterin Maren Orth machen. <br /><br />
  Über 1500m sorgt „Mister Zeitgefühl“ Felix Plinke von der LG Telis Finanz für die richtige Fahrt Richtung 3:46-47 Minuten. Aspiranten dafür sind der Dortmunder Mohamed Muhamed und der Tübinger Robert Baumann, Sohn des 5.000m-Olympiasieger von 1992 Dieter Baumann. Über 1500m werden Patricia de Graat, Joana Staub (LC Rehlingen) und die Schweizerin Lara Alemanni (TV Oerlikon) einen harten Kampf möglichst nahe an der 4:20er Grenze führen. Highlight aus Regensburger Sicht wird natürlich das 3000m-Rennen der Mädchen sein, weil hier Lokalmatadorin Miriam Dattke nach ihren souveränen Auftritten über 5.000m nun auch über die kürzere Strecke den Richtwert für Grosseto (9:30,00min) unterbieten will. Über 5.000m sucht die Darmstädterin Lisa Tertsch im Lauf mit den Frauen ihre letzte Chance die vom DLV geforderten 16:37,50min zu unterbieten. Auch die Österreicherin Lena Millonig will nach Italien. Den Ton auf den zwölfeinhalb Runden werden allerdings zwei Damen aus Uganda angeben. Mercyline Chelangat und Stella Chesang haben bisher fabelhafte 15:09,45 und 15:10,45min in ihrem Läuferinnenprofil stehen. Thea Heim (LG Telis Finanz Regensburg) und Nada Ina Pauer (VfB LC Friedrichshafen) wollen an der 16-Minuten-Grenze kratzen.<br /><br />
  Über 5.000m der Männer sorgt kein Geringerer als Olympiastarter Philipp Pflieger für die Pace. Tobias Gröbl (LG Zusam), Simon Stützel (ART Düsseldorf), die beiden Spanier Rodrigo Ruiz de la Cuesta und Ivan Pacual sowie der Düsseldorfer Maximilian Thorwirth möchten die Jagd nach einer 13er Zeit aufnehmen. Vielleicht entscheidet sich auch Telis-Mann Jonas Koller im letzten Moment dazu. Die erst 16jährige Polin Klaudia Pawlus ist mit einer Meldezeit von 10:10,00min Favoritin über die 3000m Hindernis. Die beiden Deutschen U20-Läuferinnen  Lisa Tertsch und Lisa Oed (SSC Hanau-Rodenbach) haben den Richtwert für Grosseto schon erfüllt, sollten aber bei idealen Voraussetzungen noch schneller als 10:22,76 und 10:27,40 Minuten laufen können, wenn sie denn nicht die 5.000m laufen. Bei den Jungs ist Nic Ihlow (SC DHfK Leipzig) mit einer Vorleistung von 8:48,73min ein Kandidat für die U23-EM in Bydgoszcz.<br /><br />
  Die 400m der weiblichen U20 sind vor allem aus Oberpfälzer Sicht im Fokus des Interesses, weil die Ambergerin Corinna Schwab (TV 1861) auf der Schwelle zu ihrem ersten Lauf unter 54 Sekunden und damit eine der sichersten Grosseto-Anwärterinnen ist. Neben  Lea Ahrens (LAV 07 Bad Harzburg – pB 54,83sec) wird auch die Ingolstädterin Alica Schmidt (pB 55,07sec) ein Wörtchen mitreden. Natürlich hat sie auch einen Staffelplatz für die deutsche 4x400m im Visier.
  </p>
      <?php require("../_footer.dir1.inc.php"); ?>
