<?php $title = "Sparkassen Gala und Laufnacht mit einigen Superlativen";
 $menu['current'] = "news"; ?>
  <?php require("../_header.dir1.inc.php"); ?>

	<h2>Sparkassen Gala und Laufnacht mit einigen Superlativen</h2>

  <p><strong>Regensburg wird am kommenden Wochenende zum Mittelpunkt Leichtathletik-Deutschlands</strong></p>

  <p><img class="float_left" title="Tatjana Pinto (Kiefner-Foto)" alt="PintoTatjana1 Gala15 Kiefnerfoto" src="http://lg-telis-finanz.de/images/stories/2016/PintoTatjana1_Gala15_Kiefnerfoto.jpg" width="174" height="177">Regensburg, 30. Mai 2016 (orv) – Rechtzeitig, wenn Deutschlands Leichtathleten wieder in Fahrt kommen, wird erneut angerichtet sein im Regensburger Uni-Stadion, am kommenden Wochenende, wenn bei der Laufnacht der LG Telis Finanz (Samstag) und der Sparkassen Gala (Sonntag) ein Highlight das andere jagen wird. „In vielen Disziplinen ist die gesamte deutsche Spitze da. Sie trifft auf internationale Konkurrenz aus über 20 Nationen. Es geht um die begehrten Tickets für die in Amsterdam stattfindenden Europameisterschaften (6-10. Juli) und jene zu den Olympischen Spielen nach Rio (12.-21. August – Leichtathletikwettbewerbe). Masse und Klasse trifft in der in diesen Landen einmaligen Ausführung beim zahlenstärksten Meeting überhaupt aufeinander. Wir verzeichnen ein Teilnehmerplus von über 50 Prozent und sind momentan bei der Startnummer 1200 angelangt“, berichtet Meeting-Direktor Kurt Ring. Selbstverständlich wird die LG Telis Finanz im eigenen Wohnzimmer auch ihre bisher drei für Olympia qualifizierten Athleten Anja Scherl, Philipp Pflieger (beide Marathon) und Florian Orth (5000m) vorstellen. Neben den Dreien haben sich von den „Blauen“ auch Franziska Reng (Halbmarathon) und Maren Kock (5000m) für die Europameisterschaften qualifiziert und sie werden alle da sein. </p>

  <p>Wie immer ist der Sprint einer der ersten Höhepunkte der Sparkassen Gala. Mit dem vielfachen Deutschen Meister und Rio-Fahrer Julian Reus, Vorjahresdominator Jens Knipphals, Sydney Siame und Brian Kasinda aus Sambia, sowie dem Briten Deji Tobais sind schon fünf Athleten aus der Nennliste unter 10,20sec gelaufen. Dazu kommt über 200m der deutsche Olympia-Qualifikant Menga Aleixo Platini (20,27sec) der dort auf den gleich starken Briten Danny Talbot trifft. Deutschlands Sprinterinnen haben inzwischen auch ein Luxusproblem. Mehr als Drei haben schon die Rio-Norm über 100m und 200m geknackt. Nun muss gesiebt werden und das beginnt in Regensburg für Tatjana Pinto, Rebecca Haase Lisa Mayer Jasmin Kwadwo, Gina Lückenkemper und Alexandra Burghardt.</p>

  <p>Das gilt auch für Deutschlands 400m-Läufer/Innen, die noch ohne Einzelnormen für Amsterdam und Rio sind, am Samstag die Stadionrunde zunächst einzeln laufen und dann speziell bei den Damen in der 4x400m Staffel des Sonntags gegen die Britinnen versuchen werden, einen der 16 Weltrangplätze zu ergattern, der Rio erst möglich macht. Die harte Konkurrenz kommt aus dem Ausland. Bei den Frauen sind das die 50,22sec Sprinterin Kabange Mupopo aus Sambia, bei den Männern Jon Seeliger (45,85sec) aus Südafrika, der vor allem Alexander Gladitz aus Hannover zur Zeit unter 46 Sekunden treiben soll.</p>

  <p>Die beste Hürdendisziplin im Galaprogramm sind die 100m Hürden der Frauen. Mit Franziska Hofmann, Nadine Hildebrand, Ricarda Lobe und Pamela Dutkiewicz sind schon vier Starterinnen unter den bedeutsamen 13,00sec gelaufen. Bei den Männern will Erik Balnuweit näher an die EM- und Olympianorm ran. Wer knackt aus dem deutschen 400m Hürden Quintett mit Varg Königsmark, Tobias Giehl, Georg Fleischhauer, Christian Heimann und Felix Franz die 50-Sekunden-Barriere und ist dann zumindest in Amsterdam dabei? Bei den Damen messen sich Anna Raucuc und Christine Salterberg mit der tschechischen Weltklassefrau Denisa Rosolova, die eine 55,15 stehen hat.</p>

  <p>Die Mittelstrecken über 800m und 1500m standen von je her im besonderen Interesse der Hausherren von der LG Telis Finanz. Unvergessen dabei die großartigen Läufe von Corinna Harrer und auch von Maren Kock. Erstere wird man nach ihrem Wiedereinstieg nach langer Verletzungspause nur als Tempomacherin sehen können. „Es tut mir für meine Regensburger Fans leid, aber ich bin noch nicht so weit“, entschuldigt sich die Olympiahalbfinalistin von London. Letztere kämpft um ihre Rio-Chance. „Wir werden pro Athletin entscheiden, ihr dazu die besten Möglichkeiten einräumen und wenn dann am Samstag irgendwo ein besseres Rennen stattfindet, stehen wir Maren nicht im Wege. Da sein wird sie am Sonntag auf alle Fälle und sei es als Zweitstart“, sagt Telis-Teamchef Kurt Ring dazu. Florian Orth kann sein 1500m Ding jetzt ganz entspannt angehen. Er braucht es nicht mehr. „Ich werde mich wohl jetzt bei EM und Olympia auf die 5.000m vorbereiten und die Sparkassen Gala über 1500m einfach mal ohne Druck nur genießen“, freut sich Regensburgs dritter Olympionike 2016 auf das Wochenende. So bleibt denn über 800m die Spannung bei Telis-Mann Benedikt Huber hängen, der unbedingt die 1:46er Zeit will, die Form dazu hat und sogar ein ganz klein wenig Richtung EM-Norm (1:46,50min) schielt. Konkurrenz dafür ist auf jedem Fall hier. Aus deutscher Sicht schaut man über 800m auf Jungstar Konstanze Klosterhalfen, sowie Sören Ludolph, Andreas Lange und Christoph Kessler bei den Männern. Über 1500m hofft Denis Krebs auf die Erfüllung der EM-Norm, bei den Männern haben dies Sebastian Keiner und Marius Probst im Fokus. Rio-Starter Richard Ringer startet hier auch.</p>

  <p>Im Bereich Sprung hat sich Eike Onnen bereits für Olympia qualifiziert. In Regensburg ist eine Höhe jenseits der 2,30m sein Ziel. Bei den Frauen gehen mit Katharina Mögenburg, der Tochter des 1984 Olympiasiegers Ditmar Mögenburg, Elizabeth Lamp aus Neuseeland und der Österreicherin Ekaterina Kuntcevich drei 1,90m-Springerinnen in den Wettkampf, dahinter die versammelte deutsche Hochsprungspitze. Im Weitsprung der Männer sticht der Kuwaiti Saleh Al-Hadda mit einem Hausrekord von 8,02m heraus. Während die 3000m Hindernis und 5000m der Frauen eher Aspirantinnen für die DM-Qualifikation dienen sollten und dies auch über 5000m der Männer gilt, entwickelt sich das 3000m Hindernis Rennen der Männer immer mehr zur letzten Chance der deutschen Asse Richtung Rio und Amsterdam mit der geforderten Leistung von 8:30min für beide Events. Vor allem dem Deutschen Meister Martin Grau in harter Konkurrenz mit den beiden Südafrikanern Dikotsi Lekopa und Tumisang Monnatlala ist dies zuzutrauen.</p>	</section>

    <?php require("../_footer.dir1.inc.php"); ?>
