<?php $title = "Die Sparkassen Gala 2014 wird wieder ein Leichtathletik-Festival";
 $menu['current'] = "news"; ?>
  <?php require("../_header.dir1.inc.php"); ?>

    <h2>Die Sparkassen Gala 2014 wird wieder ein Leichtathletik-Festival</h2>

    <p>
      <strong>Opening bereits am Freitag, ab 17.30 Uhr mit der Laufnacht</strong>
    </p>

    <p>
      <img class="float_left" src="http://www.lg-telis-finanz.de//images/stories/2013/Harrer_c_dm12_foto_kiefner.jpg" alt="Harrer c dm12 foto kiefner" width="130" />Regensburg, 2. Juni 2014 (orv) –  Alle Jahre wieder … kann man Anfang Juni im Regensburger Uni-Stadion absolute Top-Leichtathletik bewundern. In diesem Jahr findet die Sparkassen Gala der LG Telis Finanz Regensburg am kommenden Samstag, ab 16 Uhr statt. Neu dabei ist, dass die Langstrecken mit den Hindernisentscheidungen und den offenen Mittelstreckenrennen bereits am Freitag, ab 17.30 Uhr vorgeschaltet werden. Am Gala-Tag selbst stimmt ein breitgefächertes Vorprogramm für alle Leichtathleten/Innen, die später auch einmal ganz nach oben wollen statt. In der Sparkassen Gala selbst können die Zuschauer und Fans der olympischen Kernsportart Nummer eins wieder ein Feuerwerk von Highlights erwarten.</p>

    <p>Über die klassischen 100m treffen die deutschen Spitzenläufer Sven Knipphals (diesjährige Bestleistung 10.20sec) und Alexander Kosenkow (pB 10,28sec) auf Ramon Gittens (Barbados, pB 10,02sec), Adam Zavacky (Slowakei, pB 10,21sec) sowie auf die beiden Briten Tobias Deji (10,27sec) und Aidan Syers (10,32sec) Bei den Frauen fordern die Williams Zwillinge Bianca und Jodie (pB 11,18sec) Tatjana Pintoaus Münster (pB 11,22sec) und Leena Günter aus Köln (pB 11,33sec) heraus. Damit es besonders schnelle Zeiten gibt, wird bei entsprechendem Wind die Laufrichtung sogar zum ersten Mal in Deutschland auf der Zielgeraden umgekehrt. Eine neue Regel macht‘s möglich. Noch stärker besetzt ist der 200m Lauf der Männer: Hier gibt sich Julian Reus (TV Wattenscheid) mit einer Bestleistung von 20,36sec die Ehre, Aleixo Platini Menga (TSV Bayer 04 Leverkusen – 20,43sec) und Ramon Gittens (pB 20,44sec) stehen ihm aber kaum nach in der Vorleistung. Kann bei den Frauen die Deutsche Meisterin Inna Weit (LC Paderborn – 23,08sec) den beiden Williams-Schwestern Paroli bieten und vielleicht sogar unter 23 Sekunden bleiben? Ein besonderes Schmankerl wird sicher das Rennen über 4x100m werden. Wen auch immer die Bundestrainer in die deutsche Staffel stellen werden – sie ist in den letzten Jahren bei den Männern immer eine 38er Zeit gelaufen. Da einige der deutschen Sprintasse noch in Amerika sind, sollte man aber nicht gleich einen deutschen Rekord erwarten.</p>

    <p>
      <img class="float_right" src="http://www.lg-telis-finanz.de//images/stories/2013/Saur1_BLV2013_Kiefnerfoto.jpg" alt="Saur1 BLV2013 Kiefnerfoto" width="130" />Auf den Kurzhürden gehen Erik Balnuweit (LAZ Leipzig – pB 13,44sec) und Matthias Bühler (LG Offenburg – pB 13,45sec) auf Bestzeitenjagd und haben mit den Briten David King einen ganz starken Gegner. Deutschlands Langhürdler schwören auf die Regensburger Bahn und waren in diesem Jahr mit 49er-Zeiten von Silvio Schirrmeister und Varg Königsmark schon früh in Form. Beide werden auch bei der Sparkassen Gala am Start sein. Georg Fleischhauer ist auch schon mal unter den magischen 50 Sekunden geblieben. Das können auch der Schweizer Kariem Hussein und der Österreicher Michael Greslehner vorweisen. Bei den Frauen trifft  über 100m Hürden Cindy Roleder (LAZ Leipzig – pB 13,04sec)auf die gleich starke Norwegerin Isabelle Pedersen. Über die Langhürden hofft Christiane Klopsch aus Friedberg-Fauerbach auf die EM-Norm. Natürlich geht’s auch flach um’s Stadion-Oval. Im letzten Jahr lieferten Deutschlands 400m Läufer 45er Zeiten ab. David Gollnow, Eric Krüger, Thomas Schneider und Jonas Plass wollen auch 2014 dieses Kunststück wiederholen, dazwischen der starke Brite Jamie Bowie. Bei den Frauen gehen Janin Lindenberg, Lena Schmidt und Ruth Sophia Spelmeyer auf die Jagd nach 51er Zeiten.</p>

    <p>
      <img class="float_left" src="http://www.lg-telis-finanz.de//images/stories/2013/Orth1_DM2013_Kiefnerfoto.jpg" alt="Orth1 DM2013 Kiefnerfoto" width="130" />Die Mittelstrecken stehen ganz im Zeichen der „local heroes“. Bei den Frauen trifft über 800m das starke Telis-Trio Corinna Harrer (pB 2:00,34sec), Thea Heim (pB 2:03,20sec) und Maren Kock (pB 2:05,81sec) auf Deutschlands versammelte 800m-Spitze mit der Deutschen Meisterin Fabienne Kohlmann (pB 2:00,72sec), der Hallen-Vizemeisterin Christina Hering (pB 2:03,11) und Christine Gess (pB 2:04,22sec), sowie auf die Österreicherin Pamela Märzendorfer (pB 2:03,57sec). Die Regensburgerinnen, allesamt auch auf der Langstrecke hoch dekoriert, wollen dabei in ihrem Wohnzimmer die Spezialistinnen ein wenig ärgern. Bei den Männern steht natürlich der 1500m Lauf mit Florian Orth im Fokus. Der Regensburger 3:34-Mann hat mit dem Deutschen 5000m-Meister Arne Gabius und dem Neuseeländer Zane Robertson veritable Gegner und auch der Slowene Mitja Krevs und der Tscheche Petr Vitner wollen da noch mitmischen bei einer Zeit möglichst unter 3:40min. Über 800m treffen der Österreicher Andreas Vojta und der Südtiroler Lukas Rifesser mit dem 1:44,94 Mann Josef Repcik (Slowakei) auf einen ganz dicken Brocken. Schade ist hier, dass die fast gesamte deutsche Elite nach einem großartigen Rennen im letzten Jahr mit den einzigen 1:45er Zeiten deutscher Läufer in der zurückliegenden Saison Regensburg links liegen lässt.</p>

    <p>Die Sprünge glänzen bereits mit zwei Wettbewerben im Vorprogramm. Sowohl der Hochsprung der Männer als auch der Stabhochsprung der Frauen sollte in Bereiche von 2,25 bezeigungsweise 450m gehen. Im eigentlichen Gala-Programm werden die Männer den Stab in die Hand nehmen und wohl Höhen bis 5,50m mit Florian Gaul, dem Briten Gregor McLean und Michael Frauen aud Leverkusen. Im Hochsprung der Frauen werden die beiden Österreicherinnen Monika Gollner und Ekaterina Kuntsevich (beide pB 1,90m) mit den beiden deutschen 1,88m-Springerinnen Alexandra Plaza und Nadja Kampschulten sowie Melina Brenner (pB 1,87m) und der Lettin Madara Ouzane (pB 1,87m) Akzente setzen. „Local heroe“ Michelle Weitzel, am zurückliegenden Wochenende 6,66m gesprungen, trifft im Weitsprung auf Junioren-Europameisterin Lena Malkus (pB 6,76m).</p>

    <?php require("../_footer.dir1.inc.php"); ?>
