<?php $title = "Spezialistinnen gegen Allrounderinnen";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2>Spezialistinnen gegen Allrounderinnen</h2>

<p><strong>800m Frauenrennen bei der Sparkassen Gala mit Brisanz</strong></p>

<p><img class="float_left" title="Mittelstrecke in action (Kosmider-Foto)" src="http://www.lg-telis-finanz.de/images/stories/2013/Harrer7_DM2013_Kosmiderfoto.jpg" alt="Harrer7 DM2013 Kosmiderfoto" width="197" />Regensburg, 4. Juni 2014 (orv) –&nbsp; Die 800m der Frauen waren bei der Sparkassen Gala von jeher ein Highlight. Schließlich ist es das Wohnzimmer der Corinna Harrer. Jener Läuferin, die in den letzten Jahren mit 2:00,34 Minuten die schnellste deutsche Zeit erzielt hat. Sozusagen im Vorübergehen, weil die 800m nicht unbedingt ihre Spezialstrecke sind. Das heißt aber nicht, dass sie auf den zwei Stadionrunden nicht auch schon erfolgreich gewesen wäre. Der zweite Platz bei der U20-EM 2009 in Novisad und zwei nationale Titel im Nachwuchsbereich können sich durchaus sehen lassen. Ansonsten sammelt die Regensburgerin auf vielen Strecken Titel genauso wie ihre kaum schwächeren Teamkolleginnen Maren Kock und Thea Heim. Die können inzwischen auch passabel 800m laufen, was Thea Heim eindrucksvoll letzte Woche mit ihren von niemand erwarteten 2:03,20min bewiesen hat.</p>
 
<p>Ganz im Gegensatz dazu hat Deutschlands 800m Spitze der Frauen hauptsächlich die zwei Runden im Kopf, inklusive der Zubringerstrecke 400m. Dort sind Fabienne Kohlmann, Christina Hering und auch die anderen Spezialistinnen der kurzen Mittelstrecke besonders stark. 10.000m, wie sie alle drei Regensburgerinnen erfolgreich laufen, sind für sie unvorstellbar. Sie sind Spezialistinnen und wollen über den Umweg Regensburg direkt zur EM nach Zürich. Der Weg dorthin ist zeitenmäßig eigentlich für die „Allrounderinnen“ Harrer und Kock durch die Erfüllung der EM-Normen über 10.000m und 5.000m ein sehr veritabler Traum geworden. Im Falle Harrer schon definitiv sicher, weil sie die Deutschen Meisterschaften über die 25 Runden heuer gewonnen hat und dabei unter der geforderten Normzeit blieb. Das tat auch Maren Kock über 5.000m, leider aber unter „nicht genehmigten“ Bedingungen.</p>

<p>Jene für Zürich geforderten 2:00,50min haben die drei Telis-Läuferinnen nicht im Kopf. „Dazu haben wir auf den Mittelstrecken noch zu wenig getan“, meint Teamchef Kurt Ring dazu. „Fabienne Kohlmann mag mich vielleicht am Samstag in meinem Wohnzimmer schlagen, aber die erste Deutsche, die wieder einmal unter zwei Minuten bleibt, wollte eigentlich ich sein. Nicht jetzt im Juni, aber vielleicht Mitte Juli. Da hätte ich große Lust dazu“, sagt Corinna Harrer dazu.</p>

<p>So sind denn momentan die Spezialistinnen noch im Vorteil – zumindest auf der 800m Strecke. Erstaunlich ist es aber trotzdem, dass sich die Erste, Dritte und Fünfte der Deutschen 10.000m Meisterschaften diesen Jahres mit ihnen messen können und nicht gänzlich chancenlos sind. Die Konstellation ist jedenfalls hoch interessant, zumal es kein Fernvergleich, sondern ein Wettkampf Frau gegen Frau ist, der so in Deutschland seit den Zeiten einer Brigitte Kraus in den 80er Jahren des letzten Jahrhunderts nicht mehr stattgefunden hat.</p>

<p>Ein richtungsweisender Methodenstreit ist es sowieso nicht. „10.000m und 800m zur gleichen Zeit schnell laufen ist sowieso nur bedingt möglich“, meint dazu Harrer-Coach Kurt Ring, „aber wenn man international auf der Mittelstrecke erfolgreich sein will, zumindest auf den 1500m, muss man auch eine 10.000m-Zeit können, die derzeit zum nationalen Titel reicht. International über die beiden Stadionrunden erfolgreich zu sein, hieße, eine 1:57 unter idealen Bedingungen auspacken zu können. Und dazu sind meine Mädels zu langsam.“</p>

<p>Es wird also am Samstag gegen 18 Uhr im Regensburger Uni-Stadion knistern, wenn es heißt: Die amtierende Deutsche 800m Meisterin Fabienne Kohlmann und ihre Vize Christina Hering gegen die Erste, Dritte und Fünfte der Deutschen 10.000m-Meisterschaften Coco Harrer, Maren Kock und Thea Heim. Allein deshalb lohnt sich schon der Besuch bei der Sparkassen Gala 2014.</p>
	
<?php require("../_footer.dir1.inc.php"); ?>