<?php $title = "Plötzlich ist im Weitsprung der Teufel los";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2>Plötzlich ist im Weitsprung der Teufel los</h2>

<p><strong>Absage von Wesel besorgt Sparkassen Gala einen Weitsprung-Boom</strong></p>

<p><img class="float_left" title="Mittelstrecke in action (Kosmider-Foto)" src="http://lg-telis-finanz.de/images/stories/2012/ZieglerManuel_BLVU23U16_Kiefnerfoto.jpg" alt="Ziegler (Kiefnerfoto)" width="130" />Regensburg, 6. Juni 2014 (orv) –  Es war nur eine dürre Meldung, die so mancher übersah. Die Regensburger von der LG Telis Finanz waren da schon näher am Ball. Ihr Top-Dreispringer Manuel Ziegler kann bei der Team-EM-Ausscheidung in Wesel nicht springen, weil das Meeting vom DLV aus hier nicht näher erläuterten Gründen plötzlich keine Genehmigung erfuhr. Der Dreisprung hängt noch immer in der Luft, für den Weitsprung hat sich eine Alternative gefunden, die Sparkassen Gala in Regensburg. So können am Samstag nun neben der derzeit Führenden in der Deutschen Bestenliste Lena Malkus (6,88m) und Lokalmatadorin Michelle Weitzel (6,66m) gleich mit Malaika Mihambo (6,81m), Nadja Käther (6,57m), Marysa Luzolo (6,45m), Xenia Achkinaze (6,44m) und Lisa Kurschilgen (6,42m) fünf weitere Top-Springerinnen bewundert werden. Bei den Männern hat es den 8,71m-Hallen-Europarekordler Sebastian Bayer hereingeschneit, der auch schon im Freien 8,49m gesprungen ist.</p>
 
<p>Im Dreisprung wird noch verhandelt. Nachdem die Dreispringer in Regensburg im Sektor beim Wassergraben springen müssen und deren Anlauf sehr lang ist, würden sie im Hauptprogramm ständig die Sprintgerade kreuzen. „Wenn überhaupt, dann können sie nur vor dem Vorprogramm um 11 Uhr starten, das ist eigentlich einem Wettbewerb mit etlichen 16-Meter-Springern unwürdig“, sagt dazu Meeting-Direktor Kurt Ring“, für unseren Top-Mann Manuel Ziegler ist das alles mehr als bedauerlich. Wir kennen die genauen Gründe der Absage in Wesel nicht, halten aber das ganze Hickhack im unmittelbaren Vorfeld des Wettkampfs extrem Athleten unfreundlich. Nach Koblenz und dem 5000m-Durcheinander ist das nun schon wieder ein Grundsatzgemetzel, das auf dem Rücken der Athleten ausgetragen wird. Unnötig, unwürdig und nicht verständlich, wer auch immer daran schuld sein mag. Die Athleten/Innen sind es ganz sicher nicht.“</p>

<?php require("../_footer.dir1.inc.php"); ?>