<?php $title = "Was läuft Covergirl Coco Harrer bei der Sparkassen Gala?	";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2>Was läuft Covergirl Coco Harrer bei der Sparkassen Gala?</h2>

<p><strong>Die für die EM bereits qualifizierte Regensburgerin hat ein breites Streckenrepertoire</strong></p>

<p><img src="http://lg-telis-finanz.de/images/stories/2013/Harrer_c2_hem13_foto_chai.jpg" class="float_left" width="150px">Regensburg, 15. Mai 2014 (orv) –  „Hans Dampf der Regensburger Leichtathletik“, hat Stadion-Moderator Bert Hörhold einmal Telis-Teamchef Kurt Ring auf Grund seiner vielfältigen Betätigungsfelder in der Leichtathletik der Donaustadt genannt. Eine „Coco Dampf“ ist wohl auch dessen erfolgreichster Schützling Corinna Harrer auf Grund ihres großen Spektrums an gelaufenen Strecken. Von 800m bis Halbmarathon, den Cross eingeschlossen, nimmt sie so ziemlich alles unter die Füße, was angeboten wird. Lediglich um die Hindernisse macht die Regensburgerin einen großen Bogen, obwohl sie schon als B-Jugendliche einmal versprochen hatte, die auch zu probieren. Nun geht’s auf die Europameisterschaften 2014 zu und keiner weiß so recht, was „die Mittelstrecklerin im Langstreckenkader“ in Zürich denn wirklich laufen wird – außer eben sie selbst und ihr Coach Kurt Ring.</p>


<p>Die schweigen sich aber beharrlich aus, haben wohl mit Teamleiter Wolfgang Heinig den Fahrplan in die Schweiz abgesprochen. Doch der schweigt auch. Was die Regensburgerin aber in den nächsten Wochen laufen wird, steht fest. In Regensburg, beim Heimspiel am 7. Juni werden es ganz sicher die 800m sein. Da wurmt sie die Niederlage des letzten Jahres, auf Grund einer katastrophalen gesundheitlichen Verfassung im unmittelbaren Vorfeld zustande gekommen, doch noch sehr. Doch auch heuer wird es schwer werden. „Der Saisonaufbau mit dem einzig wirklichen Höhepunkt Europameisterschaften Mitte August war ein ganz anderer. Nach der 10.000m DM ist nun ein letzter harter anaerober Grundlagenblock mit hohen Wiederholungszahlen bei den Tempoläufen abgelaufen und ich weiß eigentlich noch gar nicht, wie sich 800m anfühlen“, sagt Coco Harrer zum Rennen im Uni-Stadion.</p>

<p><img src="http://lg-telis-finanz.de/images/stories/2012/Harrer1-pulk_DM2012_kiefnerfoto.jpg" alt="Harrer1-pulk DM2012 kiefnerfoto" class="float_left" height="180" />Zuvor aber beginnt ein weiteres läuferisches Abenteuer für das Telis-Aushängeschild. Nach einem Aufgalopp bei der „Salzburg Leichtathletik Gala“ über 1500m (24. Mai) folgt ihr erster richtiger 5000m-Lauf beim Mini-Internationalen in Koblenz (28.5.). Dort trifft sie auf „Mocki nationale“ und ihre Teamkollegin Maren Kock, die auf dieser Strecke unbedingt erneut zu den Europameisterschaften will. „Es wird wohl Richtung 15:20 gehen, für den ersten Lauf über die zwölfeinhalb Runden genau das Richtige. Wenn’s klappt sind die Aussichten auf weitere 5000er bei Coco durchaus möglich“, sagt Harrer-Coach Ring dazu. Die beiden Telis-Mädels jedenfalls scheinen derzeit gut in Form zu sein, wobei Maren Kock in Salzburg die 3000m als Auftakt präferiert.<br /><br />Natürlich ist Corinna Harrer schon mehrmals die 5000m gelaufen. „Das sind Kindergartenzeiten, mit denen ich zwei Mal den Titel bei den Deutschen U20-Meisterschaften geholt habe“, sagt sie und meint damit jene Zeiten knapp über 16:45min aus den Jahren 2009/10. 2012/13 ist sie dann diese Strecke jeweils zum Jahreswechsel beim Silvesterlauf in Trier als strahlende Siegerin auf der Straße gelaufen, wobei man die 15:53 aus dem vergangenen Jahr nur schwer einschätzen kann. Da hat sie über 800m schon ein ganz anderes Leistungsbild vorzuweisen. 2009 wurde sie in Novi Sad über die zwei Stadionrunden Vize-Europameisterin der U20 und unmittelbar nach den Olympischen Spielen zauberte sie im französischen Albi nahe Toulouse ihren bisherigen Hausrekord von 2:00,34min auf die Bahn.</p>

<p>Seither wurde viel über die erste deutsche Mittelstrecklerin der letzten zehn Jahre unter zwei Minuten spekuliert. Corinna Harrer war bei solchen Spekulationen nie dabei. Nach der Ära Monika Gratzki-Sperl und Claudia Gesell um die Jahre 2003 bis 2005 war die Regensburgerin am nächsten an dieser deutschen Traummarke dran. In Regensburg wird Corinna Harrer wohl auf die amtierende Deutsche Meisterin Fabienne Kohlmann treffen, die auch schon mal 2:00,72min gelaufen ist und auf die letztjährige deutsche Senkrechtstarterin Christina Hering von der LG Stadtwerke München. Und wie immer wird Coco Harrer auf der ersten Runde alle Hände voll zu tun haben, um überhaupt an den Spezialistinnen dran bleiben zu können. Doch je länger das Rennen dauert, desto mehr kommt ihre Zeit, ähnlich dem Halbfinale bei den Olympischen Spielen, als sie über 1500m auf der Zielgeraden Vize-Weltmeisterin Hannah England einfach stehen ließ. Die Sparkassen Gala ist eben „viel“ Corinna Harrer und Corinna Harrer ist „viel“ Regensburg. „Bei der Sparkassen Gala vor meinem Publikum gut zu sein, ist mir immer eine Herzensangelegenheit“, sagt sie und meint es auch so.</p>

<?php require("../_footer.dir1.inc.php"); ?>