<?php $title = "News - Das Unmögliche möglich machen";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2> Das Unmögliche möglich machen </h2>
<strong>Die ganz besonderen kleinen und größeren Herausforderungen eines Meetings</strong>
<br />
<br />

<p>  <img src="../photos/Mockenhaupt_Ring1-Gala06-kiefner.jpg" width="160" height="228" class="float_left" />Regensburg, 2. Juni 2008 (orv) – Eigentlich war ich im richtigen Sportleben Läufer und als mich meine Beine nicht mehr so trugen, wie ich wollte, entschloss ich mich Trainer zu werden. Und weil meine Athleten - in der Regel waren es immer mehr Athletinnen - auch Wettkämpfe brauchten, begann ich, welche zu organisieren. Und irgendwann ist man dann Meeting-Direktor. Ein großes Wort, das ich eigentlich gar nicht so gerne mag, für die vielen kleinen Dinge, die am Ende zusammen passen müssen. Es gilt eben häufig, Unmögliches doch noch möglich zu machen.</p>
<p>Da erreicht dich ein liebes Mail eines wahren Leichtathletik-Fans, der mit Leidenschaft Autogramme sammelt. Und weil jene von osteuropäischen Athleten/Innen nur schwer zu erhaschen sind, bittet er dich, doch für ihn jenes Potential, dass sich bei uns meldet, mit seinen Autogrammwünschen zu versorgen. Leidenschaft könnte man so etwas nennen und doch muss man dann irgendwo Grenzen setzen bei der Liebe zu seiner Leichtathletik, weil der Tag eben nur 24 Stunden hat.</p>
<p>Oder jener schon fast hektische Anruf eines professionelen Trainers, ich möge doch sofort im Meldeverzeichnis nachschauen, ob für seinen Nachwuchsathleten auch das richtige Zeitfenster vorhanden wäre, jene Läufer dann genau die gewünschte Zeit anlaufen würden und … ach,ja, er verzeiht mir dann auch, dass ich ganz vorsichtig anmerke, das Wetter immer nicht noch nicht im Griff zu haben.</p>
<p>Apropos, ich schlafe inzwischen vor der Nacht der Gala, jener ultimativen Nacht, in der sich für viele Leichtathleten dann wohl alles zu entscheiden scheint, immer inzwischen sehr gut. Ich kann doch viele Dinge nicht beeinflussen und wenn es in Strömen regnet, müssen wir auch durch. Die Dinge in der Hand zu behalten, haben wir inzwischen ganz passabel gelernt, weil hier in Regensburg viele kleine Hände immer wieder versuchen, Größeres zu schaffen.</p>
<p>Ein richtiges internationales Meeting ist inzwischen aus der Gala geworden mit Athleten/Innen aus 24 Nationen, zu dem – und darauf bin ich besonders stolz – jeder, der will, melden kann. Offen wird sie bleiben, die Gala, die heuer &quot;Sparkassen Gala&quot; heißt, dafür verbürge ich mich. Ich kenne jene Bettelei bei den Einladungssportfesten zu gut. Darf mein Schützling, oder darf er nicht, und nicht selten spielt die Leistung keine Rolle. Vitamin B, der richtige Leumund öffnet dann nur die Tür. So soll es bei uns nie werden, auch wenn die Gala im Kunterbunt der größeren Meetings ein Unikum bleiben wird.</p>
<p>Die kleinen Freuden eines Schülers, der gerade Bestleistung gelaufen ist, sind dabei genauso wichtig, wie jene Leistungen, die die Olympia-Qualifikation bedeuten. Bei aller Hektik bleiben dann immer noch Momente, wo du dich über die Glanztaten deiner eigenen Athleten/Innen freust, die beim Heimspiel von dir völlig allein gelassen und auf sich selbst gestellt dennoch fast immer Bestleistung bringen – und dafür nachher genauso beim Aufräumen Drecksarbeit verrichten müssen wie der kleine Helfer im Hintergrund. Natürlich muss ich mir dann oft von den Kollegen anhören, dass dies wohl in Richtung &quot;Internationalität&quot; vielleicht nicht der richtige Weg sei, mag dann aber entgegen halten, dass jene „Vernachlässigten“ in der Regel trotz Veranstaltungs-Frondienste gut mithalten können und so Leichtathletik zum Gemein-Erlebnis machen.</p>
<p>Die Manager letztendlich mögen mir verzeihen, dass hier in der Domstadt nicht eben die große Kohle zu holen ist und dennoch versichert sein, dass wir alle, aber auch alle Sponsorengelder wieder ins Meeting zurückfließen lassen. Der befürchtete Super- GAU jener aus der Macher-Gilde, die uns schon beim großen Coming-out 2006 Wettbewerbe mit jeweils nur zwei Teilnehmern prophezeit hatten, ist Gott sei Dank ausgeblieben, auch wenn der eine oder andere große Star nicht zu bekommen ist. Willkommen in Regensburg zur Sparkassen Gala 2008 - let's try it again!</p>
<p class="textnote">Foto: Veranstaltungsleiter Kurt Ring herzt Mocki bei der Gala 06 - Und wieder hat sich alle Mühe am Ende eines anstrengenden Tages gelohnt ... (Kiefner-Foto)</p>
<?php require("../_footer.dir1.inc.php"); ?>