<?php $title = "News - Rundumerdum herum";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2>Rundumerdum herum</h2>
<strong>Was wäre der Sport ohne seine in vielen Fällen aufwändige Infrastruktur</strong>
<br />
<br />

<p><img src="../photos/fressmeile-gala06_ziegler-foto.jpg" width="300" height="200" class="float_left" />Regensburg, 03. Juni 2008 (orv) – Zwei Tore, 22 Mann, ein Spielfeld und drei Schiedsrichter, schon kann angepfiffen werden. So einfach ist es nicht einmal beim Fußball, wo alle Akteure nur einer einzigen runden Lederkugel nachlaufen. Fußballspiele sind inzwischen richtige Wirtschaftsfaktoren geworden, mit einer mordsaufwendigen Infrastruktur im Hintergrund. Bei der Leichtathletik mit ihren 25 Einzeldisziplinen ist das noch viel schwieriger, nicht zuletzt deshalb weil der Fußball der alten Dame Leichtathletik in Sachen Marketing und Technik um Lichtjahre enteilt ist. Leichtathletik-Regensburg hat dies erkannt und versucht nun das “Rundumerdum“ eines Meetings kräftig nach vorne in die Moderne zu treiben. Nicht immer eine leichte Arbeit.</p>
<p>Da sich so eine Veranstaltung wie die Sparkassen Gala nicht ohne Ehrenamtlichkeit machen lässt, brauchen die Organisatoren zweimal zirka 160 hilfreiche Hände aus den eigenen Reihen der LG Telis Finanz Regensburg. Ob am am Wettkampfort selbst, im Wettkampfbüro oder in der Versorgungsmeile, es wuselt nur so von Helfern im schwarzen adidas-Organisationsshirt, die sich hier für einen „Appel und ein Ei“ die Füße wund laufen. Allein die kleinen Körbchenträger, die  die Bekleidungsstücke der beteiligten Athleten/Innen jeweils vom Start bis ins Ziel tragen, legen an so einem Tag satte zehn bis zwölf Kilometer zurück, ab und an ein Autogramm eines Stars so nebenbei haschend.</p>
<p><img src="../photos/koerbchentraeger_ziegler-fo.jpg" width="315" height="185" class="float_right" />Ein „Engelchen“ ist zuständig, dass keiner hungrig oder durstig von der Sparkassen Gala nach Hause gehen muss. Catering-Spezialistin Sybille Berr-Engel passt auf, dass nicht nur im Vip-Zelt die Verköstigung wie am Schnürchen klappt, nein, auch bis zu 160 Helfer müssen versorgt werden und auch gut zweitausend Zuschauer lassen die „Fressmeile“ sicher nicht aus. Also, das „Engelchen“ braucht an diesem Tage schnelle Flügel, um alle Gourmet-Wünsche erfüllen zu können. Keiner zweifelt im Umfeld aber an ihrer Professionalität und am erneuten guten Gelingen, wenn’s es darum geht, die edlen Getränke der Brauerei Bischofshof, die Bratwürste der Regensburger Wurstkuchl oder auch die süßen Köstlichkeiten der Bäckerei Ebner unter’s Volk zu bringen. Die Sportler/Innen selbst werden gleich nach der wilden Hatz um Sieg und Platz mit reinstem Regensburger Wasser frisch aus dem REWAG-Brunnen am gleichnamigen Stand hinterm Ziel gelabt.</p>
<p>Wer genau aufpasst, wird nicht nur die Asklepios Klinik Bad Abbach beim von ihr gesponserten Stabhochsprung bemerken, sondern auch gleich neben dem Kletterturm oberhalb der Tribüne. Dort steht dann ein größerer Pavillon mit der Aufschrift Physiobereich. Dies ist für alle Athleten/Innen ein ganz wichtiger Ort, wenn die Muskeln müde werden oder sich ein kleines Zipperlein einstellt. Die Asklepios Klinik hat auch für diesen Bereich mit ihren Physiotherapeuten Verantwortung übernommen.</p>
<p>Ach, da wäre auch die Sache „Doping“. Natürlich werden bei einem Meeting Dopingkontrollen gemacht. Wie viele und bei wem, ist einem strengen Reglement unterworfen und nicht für die Öffentlichkeit bestimmt. Erst recht, wenn ein Landesrekord fällt, der immer mit einer Kontrolle unmittelbar nach dem Erzielen verbunden sein muss. Ohne finanzielle Mittel geht natürlich bei einem Meeting dieser Größenordnung auch nicht viel. In Geldfragen ist aber die Sparkasse Regensburg kompetent und man schätzt es bei der veranstaltenden athletics SPORT GmbH über die Maßen, dass das hiesige Geldinstitut das Namenssponsoring übernommen hat.</p>
<p>Ohne Elekronik geht bei einem solchen Event überhaupt nichts mehr. Die elekronische Zeitmessung ist mit eben einer solchen bei der Auswertung oder bei den Anzeigentableaus vernetzt und auch die Moderatoren – vier Stück an der Zahl – holen sich ihre Informationen von mehrfach aufgestellten Monitoren im „Infield“, wie man das heute so schön neudeutsch nennt. Wer nicht im Stadion ist, kann sekundenschnell auf’s Geschehen über’s Internet auf der Seite <a href="http://www.sparkassen-gala.de/">www.sparkassen-gala.de</a> zugreifen. Der ständig abrufbare Liveticker übermittelt alle Resultate fast zeitgleich mit der Auswertung. Internationaler Standard eben, und da sind die Regensburger besonders stolz darauf.</p>
<p class="textnote">Fotos: „Fressmeile“ &amp; Körbchenträger bei der Gala 07 (Ziegler-Fotos) </p>
<?php require("../_footer.dir1.inc.php"); ?>