<?php $title = "News - Unger und Spiegelburg strahlen";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2>Unger und Spiegelburg strahlen </h2>
<strong>Sprinter mit Olympianorm, Stabhochspringerin mit Bestleistung, Hütters Unfall</strong>
<br />
<br />

<p>  <img src="../photos/spiegelburg_galao8_mz-lex.jpg" width="242" height="224" class="float_left" />Regensburg, 9. Juni 2008 (mz/wotruba) - Von Jahr zu Jahr etabliert sich die   Spitzen-Leichtathletik mehr in Regensburg. Die stimmungsvolle Sparkassen-Gala   der LG Telis Finanz sorgte gestern im Universitätsstadion vor 3500 Zuschauern   wieder für Leistungen von nationalem, ja internationalem Format. Die   bemerkenswertesten Auftritte legten Silke Spiegelburg und Tobias Unger hin. Die   Stabhochspringerin überwand mit 4,65 Metern eine neue persönliche Bestleistung   und wurde damit bisher weltweit 2008 nur von der Amerikanerin Jennifer   Stuczynski und der Russin Yuliya Golubchikova übertroffen. Der Sprinter stieg   mit 10,17 Sekunden über 100 Meter in die Saison ein und knackte damit auf Anhieb   die Norm für die Olympischen Spiele in Peking, die bei 10,20 Sekunden liegt. </p>
<p align="justify">„Das ist ein   Rundum-glücklich-Paket“ – so charakterisierte der Stadionmoderat Ungers   spektakulären Startschuss für das Meeting. Gleich im Vorlauf rannte der   28-Jährige so schnell los, wie er sich das gewünscht hatte. Der Schwabe staunte   selbst ein bisschen: „10,20 ist in Deutschland die letzten Jahre keiner   gelaufen. Und meine Bestzeit steht auch bei 10,16, aber mit viel mehr   Rückenwind.“ Gerade 0,1Meter pro Sekunde waren es diesmal. „Jetzt weiß ich, wo   ich stehe und kann das Fußballspiel am Abend genießen“, freute sich der   Sprinter. Dass er wegen diverser Verletzungen auf seine Spezialstrecke 200Meter   verzichten muss, damit hat er sich abgefunden. „Die 100 sind gleich vorbei und   strengen nicht so an“, meinte er launig und lehnte sich in Regensburg beim   200m-Start zurück: „Ich trinke ein Spezi und schaue mir das ganz ruhig an. Im   Ernst: Zwei, dreimal will ich die 200 heuer schon auch laufen.“</p>
<p align="justify">Auf den Finallauf über die 100 Meter   verzichtete Unger in Regensburg allerdings auch: „Das war vernünftig. Selbst,   wenn ich die Norm nochmal geschafft hätte, hätte es ja nur einmal gezählt. Mein   Trainer ist der vernünftige bei uns in der Beziehung“, kommentierte Unger   grinsend die Entscheidung Micky Corucles und konzentrierte sich zudem auf den   Staffelauftritt über 4x 100m, wo mit 38,71 Sekunden eine Leistung herauskam, die   Unger so sah: „Wir sind ordentlich durchgekommen. Bei Olympia brauchen wir eine   38,30 oder 38,40. Aber das ist machbar, weil wir momentan acht, neun Leute zur   Auswahl haben.“ </p>
<p align="justify">Ebenfalls Grund zu   jubeln hatte Silke Spiegelburg, die im zweiten Versuch die 4,65 meisterte und   Schritt für Schritt höhere Erwartungen weckt, über die sie sich aber nicht groß   auslassen will. „Was ich mir zutraue, das bleibt mein Geheimnis“, sagte die   Leverkusenerin verschmitzt, die sich um fünf Zentimeter gesteigert hatte. Auch   Fragen, ob sie denn langsam in Richtung Deutscher Rekord denke, wimmelte sie   konsequent ab: „Ich mache mein Ding, denke an meine Bestleistung und schaue   dann, was dabei rauskommt.“ </p>
<p align="justify">Vorjahressiegerin   Carolin Hingst übersprang als Zweite 4,55 Meter und erweiterte den Kreis derer,   die für Olympia in Peking in Frage kommen. Die endgültige Ausscheidung bei den   Deutschen Meisterschaften am 5./6. Juli wird damit immer spannender, zumal an   der Uni mit Kristina Gadschiew (Zweibrücken) eine weitere Athletin die Norm zum   zweiten Mal schaffte. Allerdings bot der Stabhochsprung der Frauen auch das   traurigste Ereignis des Tages: Julia Hütter aus Bruchköbel, die heuer bereits   4,50 übersprungen hatte, stürzte in den Einstichkasten, musste minutenlang   ärztlich versorgt werden und wurde dann mit Verdacht auf einen Fußbruch ins   Krankenhaus transportiert. </p>
<p align="justify">Auf sich   aufmerksam machte auch ein Bremer Duo: 100m-Hürden-Aufsteigerin Carolin Nytra   zeigte einen gelungenen Härtetest. Am Freitag hatte sie ihre Bestzeit in Kassel   auf 12,80 Sekunden gedrückt und war deswegen in Regensburg zumindest mit den   13,11 im Finale zufrieden. In Jonna Tilgner machte eine zweite Bremerin auf sich   aufmerksam: erst gewann sie über 400m Hürden, dann drückte sie über die flache   Distanz ihre Bestleistung von 53,44 auf die Siegerzeit von 51,90 Sekunden. </p>
<p class="textnote">von Claus-Dieter Wotruba, MZ vom 9.6.08 - Foto: Silke Spiegelburg nach den 4,65 m (Lex-Foto)</p>
<?php require("../_footer.dir1.inc.php"); ?>