<?php $title = "News - Nächster Höhepunkt wartet";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2>Nächster Höhepunkt wartet</h2>
<strong>Viel Lob für die Gala, am Samstag Bischofshof-Springen mit Lobinger</strong>
<br />
<br />

<p>  <img src="../photos/Lobinger2_marktspringen07_lutz-foto.jpg" width="185" height="276" class="float_left" /> Regensburg, 10. Juni 2008 (mz/wotruba) - Tobias Unger ist mittlerweile Stammgast in Regensburg und voll des Lobes über die Sparkassen-Gala der LG Telis Finanz. „Ich fühle mich wohl, der Veranstalter bemüht sich richtig gut, alles ist top organisiert“, sagt Deutschlands Topsprinter, der mit der Olympianorm über 100 Meter in 10,17 Sekunden für einen der Paukenschläge im Stadion an der Universität sorgte. Unger wirft ungefragt einen Blick voraus: „Wenn ich darf, würde ich 2009 gerne wiederkommen.“</p>
<p>Gestern berichtete Jochen Schweitzer, zusammen mit Kurt Ring Meeting-Direktor, auch von positiven Rückmeldungen von höchster Stelle im Deutschen Leichtathletik-Verband. „Bundestrainer Jürgen Mallow hat sich bedankt“, sagte Schweitzer auch mit dem Blick auf die zahlreichen Helfer und Kampfrichter, die für die Abwicklung von über zehn Stunden Wettkampf-Programm sorgten.</p>
<p>Auch die Stimmung unter den 3500 Zuschauern auf dem Gelände wirkte aufgeräumter als sonst und fiel auf. Dazu kam das Wetterglück. Als dunkle Wolken aufzogen, behielt das vor Ort bemühte Wetterradar recht: Die Regenfront zog weitgehend vorbei. Der böse Unfall von Julia Hütter blieb das einzig Negative. Dabei war gerade der Stabhochsprung der Frauen neben Ungers Sprint der Höhepunkt der Gala gewesen. Mit Silke Spiegelburg (4,65m), Carolin Hingst (4,55) sowie Lisa Rysich und Kristina Gadschiew (je 4,50) kassierte noch ein Quartett die Prämie für die Peking-Norm, die Regensburg-spezifisch ist: „Wir wollen die deutschen Athleten voranbringen und zahlen gerne.“ Insgesamt waren sieben deutsche Jahresbestleistungen zu sehen, die zum frühen Zeitpunkt der Saison zwar nicht übermäßig aussagekräftig sind, die Gala aber schmücken.</p>
<p>Eine hochkarätige Veranstaltung liegt hinter Regensburg, die nächste wartet. Nach städtischen Irrungen und Wirrungen findet das Bischofshof-Springen am Samstag (Frauen ab 10.30 Uhr, Männer ab ca. 12.30 Uhr) nun doch auf dem Regensburger Neupfarrplatz statt. Tim Lobinger kämpfte zwar bei der Gala mit Anlaufproblemen und blieb bei 5,40m hängen, schwang sich im Vorjahr aber bis auf 5,71m in die Höhe. Im britischen Gala-Sieger Steve Lewis (5,60 m) und seinem Landsmann Scott Simpson (Bestwert 5,42, Gala-Leistung 5,20) hat er starke Konkurrenz. Bei den Frauen sind Kate Denninson (4,40m) und Louise Butterworth (4,15) neben der deutschen U20-WM-Aspirantin Simone Langhirt (4,20) die Topkandidatinnen. Die Engländer blieben nach der Gala übrigens hier und absolvieren ein Trainingslager in Regensburg.</p>
<p class="textnote">von Claus-Dieter Wotruba, MZ vom 10.6.08 - Foto: Tim Lobinger (Lutz-Foto) </p>
<?php require("../_footer.dir1.inc.php"); ?>