<?php $title = "News - „Werden in der Welt wahrgenommen“";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2> „Werden in der Welt wahrgenommen“ </h2>
<strong>Tim Lobinger ist einer der Stars im Juni in Regensburg</strong>
<br />
<br />

<p>  <img src="../photos/Prinzing-Lindl-plakat1.jpg" alt="Franz-Xaver Lindl (Sparkasse Regensburg) und Otto Prinzing (athletics SPORT GmbH)" width="296" height="220" class="float_left" />Regensburg, 5. März 2008 (mz/wotruba) – Es ist ein Spagat, den die LG Telis Finanz in Regensburg vollführt. Ein Breitensport-Meeting soll es sein, aber auch Spitzensport bieten: Mit dieser Mixtur hat sich die Veranstaltung nach jahrelanger Aufbauarbeit ihren Stellenwert im Leichtathletik-Kalender erobert. „Es ist ein besonderes Sportfest, das 1000 Athleten bindet. Man hat uns in der Welt wahrgenommen“, kommentiert Telis-Teamchef Kurt Ring den Platz unter den Top 50 des Weltverbandes und nennt als Beispiel für den erworbenen Ruf den Weitsprung, in dem zuletzt zweimal Achtmeter-Sätze in Regensburg zu sehen waren. „Trotz der Wettbewerbe in Kassel und Langensalza an den beiden Tagen vorher, habe wir Signale bekommen, den Wettbewerb ja nicht aus dem Programm zu nehmen. Die Athleten kommen inzwischen von selbst auf uns zu.“</p>
<p>Heuer findet die deutsche Leichtathletik-Elite am Sonntag, den 8. Juni den Weg ins Universitätsstadion. Dann fungiert erstmals die Sparkasse als Titelsponsor der Gala. „Wir sind sehr an einer Vielfalt des Regensburger Sports interessiert“, sagte Sparkassen-Vorstandsvorsitzender Franz-Xaver Lindl bei der gestrigen Präsentations-Pressekonferenz und verwies darauf, dass der Finanzdienstleister-Verbund Olympia-Partner Deutschland und größter nicht-staatlicher Sportförderer (2006 rund 70 Millionen Euro) ist. Ein 10 Prozent höherer Etat sei durch das Sparkassen-Engagement möglich geworden, sagt Ring.</p>
<p>Es passt zur Gala, dass zur Eröffnung des Hauptprogramms, das von 14.30 bis 19 Uhr dauern soll, erstmals ein Sparkassen-Sprint-Cup für die Fünftklassen-Pennäler aus Stadt und Land in Regensburg ausgelobt wird. Lehrer aus Realschulen und Gymnasien sind bis zum 8. Mai aufgerufen, ihre schnellsten Läufer per Mail (ring@athletic-sport.com) zu melden. Der Nachwuchs als Klammer zur deutschen Spitze: Das sind Ideen, die Kurt Ring, seinem jungen Kompagnon Jochen Schweitzer und Otto Prinzing, dem Geschäftsführer der veranstaltenden Athletics-Sport-GmbH, gefallen.</p>
<p>Und die deutsche Spitze wird in vielen Disziplinen zu Gast sein im Vorfeld von Olympia in Peking. Die Sprinter um Tobias Unger, der gerade eine Achillessehnen-Verletzung erlitt und die Hallensaison beenden muss, absolvieren wie 2007 u.a. ihre Staffeltests. „Über 200 Meter können wir allerdings nur zwei, drei schnelle Bahnen anbieten“, sagt Ring und hofft auf den Ausbau. „Ich hoffe, wir werden in all dem Trubel von Wahlen, Jahn und EVR nicht vergessen.“ Mit der Verpflichtung von Stabhochspringer Tim Lobinger konnte Kurt Ring eine Zugnummer ankündigen und spekuliert auch auf Zwei-Meter-Hochspringerin Ariane Friedrich. „So eine Höhe hatten wir hier noch nicht“, sagt Ring. Bei den Frauen wird zudem die komplette Elite über die Stadionrunde anwesend sein. „Die Damen laufen die Qualifikation für die 4x400 Meter aus“, erklärt Kurt Ring den Hintergrund.</p>
<p class="textnote">Foto: athletics SPORT Geschäftsfüher Otto Prinzing und Sparkassen-Vorstandsvorsitzender Franz-Xaver Lindl vorm Galaplakat (Schweitzer-Fotos)</p>
<?php require("../_footer.dir1.inc.php"); ?>