<?php $title = "News - Spindlers Höhenflug geht weiter ";
 $menu['current'] = "news"; ?>
  <?php require("../_header.dir1.inc.php"); ?>

    <h2>Spindlers Höhenflug geht weiter </h2>
    <strong>Hürden-Sprinterin läuft persönliche Bestzeit. Pflieger siegt im Foto-Finish</strong>
    <br />
    <br />

    <p>
      <img src="../photos/Spindler_gala08_lexbild.jpg" width="244" height="247" class="float_left" />Regensburg, 9. Juni 2008 (mz/jung) - Das war heute sein Tag gewesen. Spitzbübisch lächelnd ließ sich Manuel Ziegler zu seinem 15,34 Meter-Satz gratulieren. „Ich bin zufrieden…“, kommentierte der 17-Jährige. So weit war der junge Dreispringer von der LG Telis Finanz Regensburg noch nie gesprungen – satte 28 Zentimeter mehr als bei seiner bisherigen Bestleistung. „Ich habe mich lange mit Verletzungen herumgeplagt und bin wegen Knieproblemen und eines Bänderrisses sehr spät in die Saison gestartet." Ziegler legte eine kleine Serie hin: Gleich bei seinem ersten Versuch überbot er mit 15,19 Metern knapp seine Bestweite, im dritten landete er bei 15,28 Metern, den er dann im vierten auf noch 15,34 Metern steigerte. </p>
    <p>Natürlich träumt der 17-Jährige von der Junioren-WM im polnischen Bydgoszcz. „DLV-Trainerin Elke Bartschat hat mir gesagt, es sei noch alles drin“, erzählt er mit feurigem Blick, der voller Überzeugung spricht. Noch fehlen rund 26 Zentimeter zur Nominierung. „Die schaffe ich auch noch“, sagt er, obwohl er sich bei der Sparkassen-Gala in Regensburg wohl eine Kapselverletzung im Zehenbereich zuzog. „Es war mein erster Wettkampf in diesem Jahr. Das geht heute in Ordnung“, stellt er ehrgeizig fest. </p>
    <p>Übrigens hat die deutsche Nachwuchshoffnung den Dreisprung-Star Charles Friedek genau besehen. Der 36-jährige Altmeister zog nach für ihn dürftigen 15,97 Meter, bei einem gültigen Versuch, schnell von dannen. Ob es für Ziegler dennoch etwas Nachahmenswertes gab? Seine Antwort: „Er hat sich barfuß eingesprungen – sehr interessant.“ </p>
    <p>Corinna Harrer strahlte über ihre Zeit von 2:07:48 Minuten bei den 800 Metern. „Drei Sekunden schneller als meine persönliche Bestzeit auf dieser ungewohnten Strecke. Was will ich mehr. Vielleicht bin ich ein bisschen zu schnell angelaufen“, erklärte die 17-Jährige. Sie sei freilich auch ein wenig müde gewesen nach dem Start vor zwei Tagen in Kassel über ihre Spezialstrecke, den 400 Metern. Ihrem nächsten großen Ziel, den deutschen Meisterschaften der B-Junioren in Berlin sieht Harrer optimistisch entgegen: Die Titelträgerin will dort Mitte Juli ihren ersten Platz im Olympiastadion unbedingt verteidigen. </p>
    <p>Über die 100 Meter Hürden stellte die Pamela Spindler erst im Vorlauf (13,76 Sekunden), dann im Finale (13,65 Sekunden) eine persönliche Bestmarke auf. „Obwohl ich zweimal fast hängen geblieben wäre“, sagte die bayerische Meisterin. Der Höhenflug der 26-Jährigen geht also weiter.</p>
    <p>Auf den 5000 Metern glückte Philipp Pflieger in einem Foto-Finish der Sieg. „Eigentlich habe ich mich gar nicht gut gefühlt, aber ich habe mir gedacht: Da muss ich durch.“ Seine Zeit: 14:08,44 Minuten. Trainer Kurt Ring war die Genugtuung anzusehen: „Recht viel mehr ist momentan nicht drinnen.“ </p>
    <p>Doch Rings Miene verfinsterte sich, als bei den 3000 Metern Hindernis die Zeit bei Susi Lutz erst bei 10:25,55 Minuten stehen blieb. Ziel, unter zehn Minuten zu bleiben, war klar verfehlt – nur Platz neun. Nachwuchsläuferin Julia Börner (10:05,16) stahl in diesem Rennen trotz eines Sturzes am Wassergraben allen ein bisschen die Show – auch der österreichische Siegerin Andreas Mayr (10:01,73 Minuten), die wie im Vorjahr ganz vorne lag.</p>
    <p class="textnote">von Felix Jung, MZ vom 9.6.08 - Foto: Pamela Spindler (Lex-Foto) </p>
    <?php require("../_footer.dir1.inc.php"); ?>
