<?php $title = "News -  Wie bei den ganz Großen ";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2> Wie bei den ganz Großen </h2>
<strong>Bei der Sparkassen Gala kommen erstmals elekronische Anzeigentafeln zum Einsatz</strong>
<br />
<br />

<p>  <img src="../photos/Anzeigentafel-klein.jpg" width="274" height="201" class="float_left" />Regensburg, 17. Mai 2008 (orv) – Leichtathletik „live“ bei der Regensburger Gala war schon immer in den letzten Jahren ein besonderes Erlebnis. Stabhochsprünge über 5,70, Sprints nahe der 10,00 und Acht-Meter-Sätze beim Weitsprung schauen eben hautnah ganz anders aus als auf der Mattscheibe. Wer jedoch nicht immer ganz aufgepasst hat, war ganz schnell „schlecht informiert“. Die Ergebnisübermittlung steckte nämlich bis letztes Jahr noch in den Kinderschuhen. Opas Anzeigetafeln mit Schiebezahlen mussten herhalten, wenn es um die Weitergabe von Topleistungen ging. Lediglich die Siegerzeit spuckte eine kleine Tafel im Ziel elekronisch blitzschnell aus. Nun halten in diesem Jahr erstmals elekronische Anzeigentafeln, zwei Meter lang und fast einen Meter hoch Einzug im Uni-Stadion und werden das Publikum über Zwischenstände, Ergebnisse und Startaufstellungen umfassend informieren – wie bei den ganz großen Meetings eben.</p>
<p>„Das ist für uns eine neue Meeting-Liga. Der Schritt ist uns nicht leicht gefallen. Unsere Sponsoren, die auf diesen neuen attraktiven Werbeflächen eine weitere Möglichkeit der Präsentation haben, sollen sehen, dass wir die finanziellen Mittel der Sparkassen Gala absolut sinnvoll investieren. Für die Zuschauer wird ein ganz anderer Informationsfluss möglich sein. Die Moderatoren profitieren über die neue technische Vernetzung ebenfalls“, so Meetingdirektor Kurt Ring zum Einsatz der elekronischen Anzeigetafeln im Stadion. „Damit haben wir bis auf die große Videowand den Standard von Deutschen Meisterschaften erreicht und der Schritt zu einer Fernseh-Direktübertragung wäre auch nur noch ein kleiner.“ Diese Videowall ersetzt ein ein 2,5 auf 3-Meter großes Kombielement im Zielbereich. Dort kann man dann die Startaufstellungen, die Zieleinläufe, aber auch die vollständigen Ergebnisse abrufen. Leichtathletikherz, was willst du mehr. In Verbindung mit dem attraktiven Veranstaltungsheft ergibt sich dann ein Gesamtbild, das sich sehen lassen kann.</p>
<p>Möglich gemacht hat das alles ein attraktives Angebot der österreichischen Firma Seltec, die seit letztem Jahr auch alle deutschen Meisterschaften technisch betreut. „Ich kann mich noch gut erinnern, wie stolz ich war, als erstmals mein Name auf so einer Anzeigentafel erschien“, so local heroe Susi Lutz zum neuen Stadion-Medium, „da bist du plötzlich wer!“ So und nicht anders werden sich auch die über 700 Akteure des Vorprogramms fühlen, allesamt Sportler, die seltenst die Möglichkeit haben, bei so einem Meeting zu starten. „Das macht das Besondere unserer Veranstaltung aus“, so Veranstaltungs-Jungmanager Jochen Schweitzer, „ es ist eben ein Familienfest der Leichtathletik, offen für alle, gespickt mit Topwettbewerben, präsentiert auf sehr hohem Niveau, eigentlich ziemlich einzigartig in ganz Europa“.</p>
<p>Trotz Bundesligafußball und hoffentlich auch bald wieder Eishockey solchen Ligenformats, bleibt die Sparkassen Gala ein ganz besonderes Sternchen im Regensburger Sportkalender.</p>
<?php require("../_footer.dir1.inc.php"); ?>