<?php $title = "News - Im Schatten der Großen";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2>Im Schatten der Großen </h2>
<strong>Erfüllte Träume, geplatzte Hoffnungen der Regensburger Jungstars bei der Sparkassen Gala</strong><br />
<br />

<p>  <img src="../photos/Kick_gala08_lutz-foto-klein.jpg" width="173" height="258" class="float_left" />Regensburg, 10. Juni 2008 (orv) – Normalerweise sind sie fester Bestandteil der regionalen Meetings, im Visier der Beobachtung durch die interessierte Öffentlichkeit, immer auf dem Sprung zu neuen Glanztaten und manchmal füllen sie sogar die Headlines der regionalen Presse. Die Rede ist von all den kleinen und etwas größeren Sternchen der Leichtathletik-Region Regensburg, die beim ganz großen Fest, der Sparkassen Gala 2008 doch ins zweite Glied zurücktreten mussten, obwohl sie - meist schon im Vorprogramm des größten bayerischen Meetings - für so manch gute Leistung sorgten.</p>
<p>Julia Kick (LG Telis Finanz) ist so eine, die schon auf der Zielgeraden des 3000 m Hindernislaufes Tränen der Enttäuschung vergoss, weil ihr Diana Sujew auf den letzten dreihundert Metern den JWM-Platz trotz erfüllter Normleistung wegnahm. Die 10:33,85 bedeuteten zwar eine Steigerung des persönlichen Rekords von über zwanzig Sekunden und brachten ihr so nebenbei auch Silber in der bayerischen Wertung der Juniorinnen ein, für Bydgozscs waren sie jedoch zu wenig. Die Kelheimerin mag sich trösten. Im nächsten Jahr sind U20-Europameisterschaften und bis dahin werden ihre Chancen steigen.</p>
<p><img src="../photos/Plinke_gala08_lutz-foto-klein.jpg" width="160" height="239" class="float_right" />Anna Plinke, ihre Clubkameradin freute sich im Ziel zunächst riesig über die neue 1500 m Bestzeit von 4:50,53, um sich kurz darauf gleich wieder tierisch zu ärgern. Genau jene 53 Hundertstel hinterm Komma waren zuviel, um sich ihren größten Traum, die Teilnahme bei den Deutschen Juniorenmeisterschaften zu sichern. Jenen Startplatz in Recklinghausen buchte indessen Teamkollegin Liesa Gläß direkt vor ihr mit einer 4:49,59. Langsam in Schwung kommt auch wieder die noch B-jugendliche Laura Biehler (LG Telis Finanz), die trotz zaghaftem Beginn in ihrer Klasse den 800 m Sieg mit 2:17,37 einfuhr und dazu gleich noch die Fahrkarte zu den Deutschen Jugendmeisterschaften nach Berlin. Eine Klasse drunter bei den Schülerinnen freuten sich die beiden Piendl-Schwestern Theresa (W15) und Maria (W13) über ihre tollen 800 m Steigerungen auf 2:21,77 und 2:26,59, während W15-Trainingspartnerin Christina Blößl (alle Telis Finanz) über 1500 m mit 5:00,10 nur hauchdünn eine 4er-Zeit verpasste.</p>
<p><img src="../photos/Ziegler,Lukas_gala08_lutz-foto-klein.jpg" width="161" height="240" class="float_left" />Heimlich, still und leise lief der bayerische Jugendhallen-Doppelmeister auf den Mittelstrecken Jonas Zweck (LG Telis) mit 3:58,45 erstmals unter vier Minuten und machte damit ebenfalls den Weg über 1500 m zur Jugend-DM klar. Einige Plätze dahinter markierte sein Teamkollege Lukas Kellner bei der B-Jugend mit 4:19,52 einen neuen Hausrekord und bei den Schülwern über 1000 m schaffte dasselbe Thomas Paßberger (LG Telis) mit einer 2:54,65. Einer der bereits um die Norm für die großen Deutschen Meisterschaften kämpft, ist der Vorjahresjugendliche Sebastian Zundler (LG Telis), im 800 m B-Lauf Zweiter und mit seinen 1:52,84 nur noch eine Sekunde von der Quali weg. „Nur auf Platz will ich heute laufen“, war die Ansage des neu gekürten bayerischen Vizemeisters über 3000 m Hindernis Max Bosse (LG Telis), nachdem er bereits am Vortag bei den Hochschulmeisterschaften auf der selben Strecke recht daneben lag. Am Ende kam mit 9:34,72 fast ein neuer Hausrekord heraus.</p>
<p><img src="../photos/Bosse_gala08_lutz-foto-klein.jpg" width="169" height="252" class="float_right" />Mit Amelie Garatva (SWC Regensburg) im Stabhochsprung (3,90) und Christina Muckenthaler (LG Telis – 100 m/12,42 – 100 m H/14,28) zeigten sich zwei weitere Regensburger Nachwuchshoffnungen tauglich für die Deutschen Jugendmeisterschaften und LG-Webmaster Lukas Ziegler freute sich tierisch über seinen ersten 800 m-Lauf (mJA) unter zwei Minuten, auch wenn es nur eine Hundertstel war. Mittelstrecklerin Christiane Danner (LG Telis Finanz) war zunächst ein wenig traurig über ihre Rückversetzung in den B-Lauf, konnte dann aber erneut mit 2:10,78 unter DM-Norm bleiben. Mit Julia Liedl (400 m wJB – 59,55) und Michelle Weitzel (Frauen Weitsprung – 5,81) meldeten sich nach längerer Verletzungspause zwei Telis-Hoffnungen wieder im Wettkampfgeschehen zurück.</p>
<p class="textnote">Fotos: Julia Kick, Anna Plinke, Lukas Ziegler, Max Bosse (Lutz-Fotos) </p>
<?php require("../_footer.dir1.inc.php"); ?>