<?php $title = "News - Als die Sparkassen Gala laufen lernte";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2>Als die Sparkassen Gala laufen lernte</h2>
<strong>Langsam und stetig seit 1997 vorangekommen, dann das Coming-out 2006</strong>
<br />
<br />

<p>  <img src="../photos/gala06_ziegler-foto.jpg" width="307" height="205" class="float_left" />Regensburg, 05. Juni 2008 (orv) – Irgendwann einmal Mitte der neunziger Jahre des letzten Jahrhunderts stellte der Leiter des damaligen Uni-Sportzentrum Hans-Jörg Held fest, dass sein Uni-Stadion eigentlich nun schon seit zwanzig Jahren einen Dornröschenschlaf vollzieht. Dies war ihm ein unangenehmer Gedanke, deshalb nahm er Kontakt zur hiesigen Leichtathletik Gemeinschaft auf mit der Zielsetzung, „da muss Leben rein“. Ein anfängliches Uni-Abendsportfest mit vielleicht einmal hundert Teilnehmern bei eisiger Kälte und unangenehmen Wind war dann nicht gerade der Hit, aber dennoch einmal schon ein Anfang. Zum jetzigen „Gala-Standard“ mit german Meeting-Status und internationalem Zuschnitt war es dann aber noch ein langer Weg, geprägt von vielen günstigen Umständen und auch kleinen Rückschlägen.</p>
<p>Helds Vorhaben profitierte zunächst in erster Linie vom damals stark aufkeimenden Veranstaltungsschwung der LG Regensburg, die dann auch schnell eine LG Domspitzmilch wurde. Seitdem gehören bayerische und süddeutsche Meisterschaften auf dem Unihügel zum immerwährenden Standardprogramm und ganz Süddeutschland konnte sich überzeugen, welche prächtige Leichtathletikstätte sich dort befindet. Ausgestattet mit dem neuen Namenssponsor wagten sich nun die Regensburger Leichtathletikmacher an eine Gala heran, zuerst in Zusammenarbeit mit dem Landesverband als „Bayern Gala“ tituliert, dann in Eigenregie als Domspitzmilch Gala. An ein großes internationales Meeting konnte und wollte man zu diesem Zeitpunkt einfach noch nicht denken, wenn auch der eine oder andere Topstar mal in Regensburg vorbeischaute. Vielleicht wär’s auch mit der Entwicklung der Gala schneller vorangegangen, wenn es nicht regelmäßig bei den ersten drei oder vier Meetings wie aus Kübeln gegossen hätte. „Regensburg eben, wie der Name schon sagt“, so die Unkenrufe all jener, die die Stadt nur vom Event her kannten. Was nützt es dann schon, als Einheimischer zu wissen, dass deine Heimatstadt eigentlich eine regenarme Stadt ist.</p>
<p><img src="../photos/rundenzaehler_gala07_ziegler-foto.jpg" width="301" height="200" class="float_right" />Das Gala-Glück schneite es dann 2006 herein. Fußball-Weltmeisterschaften waren angesagt und jeder deutsche Kopf schien zum runden Leder zu mutieren. Kein nationaler Veranstalter traute sich in jenen Junitagen an ein Meeting heran. Der DLV brauchte aber genau so eines, um seine Ausscheidungen für den Europacup durchführen zu können. Regensburg stand Gewehr bei Fuß, und es war eben nur Regensburg, respektive der Tatsache, dass die Wurf-und Stoßwettbewerbe bei einem kleinen Spezialmeeting in Schönebeck abgehalten werden konnten. Der leitende Bundestrainer Jürgen Mallow kannte die glänzenden organisatorischen Voraussetzungen in der Domstadt aus seiner Zeit als leitender Landestrainer von Bayern. „Das ist ein Steilpass für die Zukunft“. Die damalige Gala mit den integrierten Europacup-Ausscheidungen wurde ein Volltreffer. 19 Jahresbestleistungen deutscher Athleten/Innen blieben stehen, genauso viele, wie die deutsche Mannschaft dann bei den Europamisterschaften zwei Monate später in Göteborg erzielte. Im Meeting-Ranking katapultierte sich Regensburg in die Spitze der deutschen Veranstaltungen und an die 52. Stelle der Welt, nicht zuletzt dank des großen finanziellen Einsatzes speziell auch durch den Verband.</p>
<p>Die jetzige LG Telis Finanz Regensburg nahm im nächsten Jahr diesen Ball auf, schulterte die Nachfolge- und damit auch letzte Domspitzmilch Gala ganz allein und konnte sein hohes Niveau auch ohne Verbandsunterstützung halten. Zudem war man in die Vereinigung der german Meetings aufgenommen worden, sozusagen als Veranstalter geadelt worden. Einer der Garanten war die Sparkasse Regensburg als Hauptsponsor. Die Gala wurde erneut ein ganz großer Erfolg. Logische Folge: Nachdem die LG aus wirtschaftspolitischen Gründen nicht mehr LG Domspitzmilch hieß, der Name der Gala also frei wurde, heißt sie nun Sparkassen Gala und man wünscht ihr schon aus leichtathletischer Raison ein langes Leben. Als einziges offenes Großmeeting im europäischen Bereich hat es zudem einen ganz besonderen, aber auch wichtigen Integrationsfaktor vom Nachwuchsathleten bis hin zum Top-Sportler.</p>
<p class="textnote">Fotos:  Domspitzmilch Gala 06 und die Rundenzähler beim 10.000 m Lauf (Ziegler-Fotos) </p>
<?php require("../_footer.dir1.inc.php"); ?>