<?php $title = "News - Regensburger Top-Meeting nun eine Sparkassen Gala";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2> Regensburger Top-Meeting nun eine Sparkassen Gala </h2>
<strong>Athletics SPORT GmbH und Sparkasse Regensburg unterzeichnen Vertag über Namenssponsoring</strong>
<br />
<br />

<p>  <img src="../photos/Prinzing-vertragsunterzeichnung1.jpg" alt="Vertragsunterzeichnung" width="274" height="205" class="float_left" />Regensburg, 3. März 2008 (orv) – Seit gestern ist das diesjährige Regensburger Top-Meeting wirtschaftlich in trockenen Tüchern. In der Zentrale der Sparkasse Regensburg unterzeichneten Sparkassen Vorstandsvorsitzender Franz-Xaver Lindl und der Geschäftsführer der veranstaltenden athletics SPORT GmbH Otto Prinzing einen Sponsorenvertrag, der die Namensrechte für die Sparkasse Regensburg beinhaltet. Damit sind die finanziellen Mittel für die am Sonntag, den 8. Juni 2008 im Regensburger Uni-Stadion stattfindende Sparkassen Gala im Großen und Ganzen gesichert. Das Meeting, das zu Deutschland Top-Serie &quot;german meetings&quot; gehört, wird also auch in diesem Jahr in der Domstadt Spitzen-Leichtathletik anbieten können.</p>
<p>Meeting-Direktor Kurt Ring bedankte sich nochmals herzlich beim Geschäftsführer der athletics SPORT GmbH, Herrn Otto Prinzing, für seine aufwändige Arbeit in Sachen Geldbeschaffung. &quot;Es ist in unserer Region kein Pappenstiel, so eine Veranstaltung finanziell zu heben.&quot; Mit sichtlicher Freude konnte er zudem verkünden, dass Athletenmanager Jochen Schweitzer inzwischen schon Publikumsmagnet Tim Lobinger verpflichten konnte. Highlights, wie der gesamte deutsche Sprintbereich, die Europacupausscheidung der 400 m Läuferinnen für die Staffel, die letzten Leistungstests der Sprintstaffeln, spannende Kurzhürdenentscheidungen, die versammelte deutsche Elite im Frauen-Hochsprung und Stabhochsprung, ein angedachter Klasse-1500 m Lauf und die U20-WM-Ausscheidungen über 3000 m Hindernis werden den 8. Juni zum Leichtathletik-Erlebis machen.</p>
<p><img src="../photos/Prinzing-Lindl-plakat1.jpg" alt="Franz-Xaver Lindl (Sparkasse Regensburg) und Otto Prinzing (athletics SPORT GmbH)" width="260" height="195" class="float_right" />Sparkassen Vorstandsvorsitzender Franz-Xaver Lindl verband das Sparkassen-Engagement als &quot;Olympia Partner Deutschland&quot; mit seinem regionalen Einsatz für die Regensburger Gala und ließ Hoffnung aufkommen, dass auch jener, wie die Olympiapartnerschaft (bis 2012), in Regensburg langanhaltend sein wird. Augenscheinlich entspricht jene Philosophie der Gala, Breite und Spitze innerhalb eines riesigen Familienfestes mit tausend Athleten/Innen, den Vorstellungen des Geldinstitutes.</p>
<p>Der Regensburger Nachwuchs soll bei der diesjährigen Gala auch nicht zu kurz kommen. In Windeseile wurde der Sprint-Cup der Sparkasse Regensburg kreiert. Regensburgs schnellste Fünftklass-Pennäler werden vom Veranstalter eingeladen und dürfen innerhalb des Meetings über jeweils vier Vorläufe (männlich und weiblich) und den beiden Finals den/die Meister/In von morgen suchen.</p>
<p class="textnote">Fotos: Meeting-Direktor Kurt Ring, athletics SPORT Geschäftsfüher Otto Prinzing und Sparkassen-Vorstandsvorsitzender Franz-Xaver Lindl bei der Vertragsunterzeichnung, Händeschütteln vorm Galaplakat (Schweitzer-Fotos)</p>
<?php require("../_footer.dir1.inc.php"); ?>