<?php $title = "Deutschlands Männer wollen in Regensburg an die 10,00 ran";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2>Deutschlands Männer wollen in Regensburg an die 10,00 ran</h2>
<p><strong>Ganz egal, woher der Wind kommt, in Regensburg wird es immer Rückenwind sein</strong></p>
<p><img class="float_left" title="Gittens vor Blum (Foto:Kiefner)" src="http://sparkassen-gala.de/images/inhalt/Gittens_Ramon-vor-Blum_Gala14-100m_Kiefnerfoto.jpg" alt="Gittens vor Blum (Foto:Kiefner)" width="150" />Regensburg, 21. Mai 2015 (orv) – Regensburg erwartet am 6. Juni wieder Deutschlands beste Sprinter bei der Sparkassen Gala. Für die im Sprint so wichtigen Sommertemperaturen können die Veranstalter noch keine Garantie geben. Dass die für Sprinter aber so elementare Windunterstützung von hinten kommt, dafür garantieren sie. Je nach dem die Windverhältnisse sind, wird die Richtung der 100m Läufe und der für die 100m Hürden der Damen ausgelegt – entweder von West nach Ost oder eben umgekehrt. Das wollen der Dritte der diesjährigen Hallen-Europameisterschaften Christian Blum (TV Wattenscheid), seine Teamkollegen Robin Erewa und Alexander Kosenkow, die drei Leipziger Robert Hering, Martin Keller und Roy Schmidt, Aleixo Platini Menga (TSV Bayer 04 Leverkusen), sowie Sven Knipphals vom VfL Wolfsburg nutzen, um möglichst nahe an die imaginären 10,00sec heranzustürmen. Mit Martin Keller ist 2013 in Amerika schon einer drunter geblieben – allerdings damals mit zuviel Rückenwind. Seine regulären 10,07sec weisen ihn auch als Schnellsten der acht Topsprinter aus. Außer Blum und Keller wollen alle anderen auch die 200m angehen. Bisher schnellster ist hier Aleixo Platini Menga mit seinen 20,33sec. Es müsste schon mit dem Teufel zugehen, wenn beim Staffeltest der Nationalmannschaft, gleich, wer dann das Quartett stellt, nicht wieder, wie schon in den letzten Jahren eine 38er-Zeit herausspringt. Natürlich wird Deutschlands Elite auch wieder auf den einen oder anderen internationalen Star treffen. 2014 gewann Ramon Gittins aus Barbados mit 10,06sec vor den beiden Briten Sean Safo-Antwi und Deji Tobais (10,14/10,18sec). Der Deutsche Meister Julian Reus – in diesem Jahr muss er verletzungsbedingt passen – überzeugte dort mit 10,12sec im Vorlauf. Schnellster über die 200m war Deji Tobais mit 21,01sec, allerdings bei Gegenwind. Die deutsche 4x100m Staffel schaffte eine 38,71sec.</p>
<br />

<?php require("../_footer.dir1.inc.php"); ?>
