<?php $title = "Verena Sailer sagt in Regensburg „hello again“";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2>Deutschlands Sprint-Lady Nummer eins bei der Sparkassen Gala dabei</h2>
<p><strong>Ganz egal, woher der Wind kommt, in Regensburg wird es immer Rückenwind sein</strong></p>
<p><img class="float_left" title="Rebekka Haase (Foto:Kiefner)" src="../images/inhalt/Haase_Rebekka4_Kiefnerfoto.jpg" alt="Rebekka Haase (Foto:Kiefner)" width="180" />Regensburg, 22. Mai 2015 (orv) – Deutschlands beste Sprinterinnen waren bei den letzten Sparkassen Galen mal mehr mal weniger vertreten. Mal waren die Bedingungen sehr gut, mal waren sie weniger gut. Immer dann, wenn die Temperaturen sehr gut waren, waren bis 2014 die Windbedingungen alles andere als gut, weil dann meistens eine Brise den schnellen Mädels ins Gesicht blies. Das ist nun seit 2014 anders. Für Verena Sailers Entscheidung, diesmal in Regensburg wieder anzutreten, sollte der Wind keine Rolle gespielt haben. Ronald Stein, Bundestrainer für den Sprint, hat sie in der Staffel angekündigt, weil die in Nassau bei der diesjährigen Staffel-WM gepatzt hat und nun in der Domstadt die fällige WM-Norm (43,45sec) abliefern soll. Damit geht die Deutsche Meisterin Tatjana Pinto von der LG Brillux Münster in die Pole-Position über 100m. Die Münsteranerin lief 2014 eine 11,20sec. Ihre ärgste Gegnerin könnte die Französin Celine Distel werden, im letzten Jahr hier in Regensburg mit einer 11,39 erfolgreich. In diesen Breitengraden bewegen sich auch Deutschlands weitere Top-Sprinterinnen Yasmin Kwadwo (MTG Mannheim/11,28sec), Rebekka Haase (LG Erzgebirge/11,32sec), Josefina Elsler (LC Paderborn/11,33sec) und  Ina Weit (LC Paderborn/11,39sec). Vorjahressiegerin Jodie Williams (Großbritannien/11,14sec bei 2,8m/s RW) ist diesmal nicht am Start, weil gleichzeitig in Birmingham ein Diamond league Meeting stattfindet. Über 200m werden vor allem Rebekka Haase und Ina Weit versuchen unter den imaginären 23,00sec zu bleiben. Im vorigen Jahr hat das Bianca Williams (Großbritannien) mit dem derzeitigen Meeting-Rekord von 22,93sec geschafft.</p>
<br />

<?php require("../_footer.dir1.inc.php"); ?>
