<?php $title = "News - Wenn die Gala Bilder laufen lernen";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2>Wenn die Gala Bilder laufen lernen </h2>
<strong>Livestream heißt das Zauberwort für alle die am Sonntag nicht ins Uni-Stadion kommen können</strong>
<br />
<br />

<p>  <img src="../photos/gala-moderatoren08_kiefnerfoto.jpg" width="227" height="151" class="float_left" />Regensburg, 27. Mai 2009 (orv) – Die heutige Technikentwicklung ist  in Teilen schneller als die Polizei erlaubt. Ach, was waren die  Gala-Macher stolz, als sie 2006 das Internet-Radio präsentieren konnten  und geneigte „User“, wie man jene Teilnehmer im Internet neudeutsch  nennt, hautnah mit bekamen, was da so am Regensburger Eisbuckel  passierte. Der lieferte an diesem Tag absolut heiße Leichtathletikware  im Vorfeld der Europameisterschaften von Göteborg. Heiß her gehen  wird’s natürlich auch heuer wieder bei der Sparkassen Gala am 7. Juni.  Doch das Internet-Radio ist längst schon wieder out. Nach einem kurzen  Intermezzo mit Videoeinspielungen folgt der livestream, eigentlich  nichts anderes als eine Fernsehliveübertragung via Internet.</p>
<p> „Im letzten Jahr die elekronischen Anzeigentafeln, heuer der  livestream, wir sind im Trend“, so Meetingdirektor Kurt Ring zu einer  ganz spannenden Sache, die nur möglich war, weil der örtliche  Fernsehsender TVaktuell sich äußerst kulant zeigte. Der Aufwand ist  enorm, die Kosten entsprechend und wäre da das Team von  leichtathletik.de um Christian Fuchs nicht noch mit eingesprungen, die  Sache wäre nicht zu schultern gewesen. Ein Ü-Wagen mit Personal, vier  Kameras mit dem entsprechenden Fachpersonal, fast ein Kilometer  Verkabelung, drei weitere Moderatoren zum eh schon hohen Besatz von  vier Stadionsprechern, einer am Bildschnitt und letztendlich ein  Regisseur werden versuchen, die Sparkassen Gala letztendlich der ganzen  Welt zu präsentieren und das vier volle Stunden lang.</p>
<p>Wer selbst im Stadion ist, verpasst den livestream natürlich. Das  Team von leichtathletik.de und die LG Telis Finanz werden sich aber  bemühen, die Entscheidungen in den einzelnen Disziplinen via  Videoaufzeichnungen so schnell wie möglich ins Netz zu stellen. Den  besten Eindruck von beidem – Liveveranstaltung im Stadion und  livestream – bekommen die Gäste im Vip-Zelt. Dort hängen dann große  Flachbildschirme, die direkt mit dem livestream verkabelt sind. Wir  hoffen natürlich, dass alles technischerseits so klappt, wie es geplant  ist. Jedenfalls freuen wir uns in Regensburg alle schon auf dieses  multimediale Abenteuer.</p>
<p class="textnote">Foto: Gala-Moderatoren 2008 (Kiefner-Foto)</p>
<?php require("../_footer.dir1.inc.php"); ?>