<?php $title = "News - Die große Vorschau";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2>Sparkassen Gala: Die große Vorschau</h2>
<strong>Ein Kaleidoskop von großen Leichtathletiknamen querbeet durch alle Disziplinen</strong><br />
<br />

<br />
<a name="1"></a>
<h3>100 m – 4x100 m</h3>
<p><strong>Die Sprints: Das „who is who des deutschen Sprints“ bei den Männer, bei den Frauen Verena Sailer, wer sonst?</strong></p>
<p>  <img src="../photos/Kosenkow-100m-maenner-int.jpg" width="146" height="218" class="float_left" />Regensburg, 4. Juni 2009 (orv) – Der Stadionrekordler Tobias Unger wird in Regensburg die 200 m vorziehen. Das muss aber nicht heißen, dass seine 10,17 des Vorjahres als Rekord überleben werden. Das „who is who“ des deutschen Sprints steht an der Startlinie. Stefan Schwab hat mit 10,22 die Richtung schon vorgegeben. Christian Blum steht mit seinen bescheidenen 10,49 vom Vorjahr in der Meldeliste, was nun gleich mal nichts zu bedeuten hat. Der wird richtig aufdrehen in Richtung WM-Norm.. Dazu die 200 m Protagonisten Aleixo Menga Platini, Alexander Kosenkow, Till Helmke und Daniel Schnelting. Kommt der Wind von hinten und alles deutet für Sonntag darauf hin, fallen über 100 m die 10,20.<br />
  Bei den Damen wird Verena Sailer die Richtung angeben. Der ehemaligen Kemptnerin kann man durchaus eine Zeit unter 11,30 zutrauen. So schnell ist in Regensburg auch noch keine Dame gelaufen. <img src="../photos/Sailer,Verena2_100m-frauen-int.jpg" width="234" height="156" class="float_right" />Die ärgsten Konkurrentinnen sollten Cathleen Tschirch, Anne Möllinger und Marion Wagner sein. Die bayerischen Asse Franziska Berchtenbreiter und Anja Wurm wollen ebenfalls mitmischen. Mal schau’n, was geht.<br />
  Für die beiden Staffeln sind für die WM eine 38,80 und eine 43,55 gefordert. Die Männer sind heuer schon knapp herangelaufen (38,89), den Frauen fehlt mit ihren bisherigen 43,89 noch ein bisschen mehr. Vielleicht klappt es mit der Normerfüllung bereits am Sonntag in Regensburg.</p>
<br />
<h3>200 m</h3>
<p><strong>Der Langsprint: Noch nie zuvor sind Deutschlands 200 m Läufer so gut in die Saison gestartet</strong></p>
<p>  <img src="../photos/Menga_Mancini1-int.jpg" width="220" height="144" class="float_left" />Die deutsche Bestenliste zeigt sich mit vier Zeiten unter 21 Sekunden schon recht beachtlich. Aleixo Menga Platini hat zudem mit seinen 20,57 bereits einmal die WM-Norm geknackt. Vorjahressieger Alexander Kosenkow ist genau diese Zeit in Regensburg gelaufen und auch am Start. Till Helmke, Sebastian Ernst und Daniel Schnelting sind ebenso in der Lage, so schnell zu laufen. <img src="../photos/Tschirch-200m-frauen-int.jpg" width="157" height="235" class="float_right" />Richtig, da fehlt auch noch der deutsche Marktführer. Tobias Unger wird in Regensburg nach zwei Jahren sein Comeback genau dort feiern, wo er sein letztes schnelles Rennen hatte. Eine 20,48 ist er damals im Uni-Stadion gelaufen. </p>
<p>Bei den Damen tun sich Deutschlands 200 m Läuferinnen mit jener ominösen 23,00 Barriere sehr schwer. Gabi Rockmeier lief bei der Gala 2006 eine 22,96, eine 23,44 hat die Vorjahressiegerin Cathleen Tschirch in diesem Jahr bisher zu Buche stehen. So kann nur Devise „immer ein Stückchen näher an die 23 Sekunden“ heißen, für alle deutschen Sprinterinnen, die in Berlin auf dieser Strecke starten wollen.</p>
<br />
<h3>400 m</h3>
<p><strong>Die Stadionrunde: Geballte Frauenpower in der Domstadt</strong></p>
<p><img src="../photos/Hoffmann,Claudia1-400m-frauen-int.jpg" width="147" height="219" class="float_left" />Claudia Hofmann ist in Regensburg schon unter 52 Sekunden gelaufen, Jonna Tilgner auch. Beide werden am Sonntag nicht laufen. Claudia Hofmann exprimentiert derzeit mit den 800 m, wird dort aber wegen den nahenden Militär-Weltmeisterschaften auch nicht antreten, Jonna Tilgner hat einen internationalen Start vorgesehen. So liegen die Hoffnungen Richtung 52,00 bei Florence Ekpo-Umoh und Sorina Nwachukwu, die trotz ihrer afrikanischen Namen in Berlin anlässlich der 4x400 m Staffel das deutsche Nationaltrikot anziehen wollen. Diese Staffel muss sich erst bei der Mannschafts-EM in Portugal bewähren. Bundestrainer Tobias Kofferschläger hat für seine Staffelbesetzung die Sparkassen Gala als Quali-Wettkampf auserkoren. Die Algerierin Zahra Bouras mit einer gemeldeten 52,56 wird den deutschen Viertelmeilerinnen Beine machen.<br />
  Bei den Männern steht mit dem Amerikaner Michael Matthieu ein ganz schneller am Start (pers. Bestleistung 45,17/ 2009 46,06). Der sollte genau das richtige Zugpferd für Thomas Schneider und Eric Krüger für Zeiten in Richtung 46,00 und drunter sein. Der Stadionrekord liegt übrigens bei 45,91.</p>
<br />
<a name="2"></a>
<h3>800 m</h3>
<p><strong>Die Mittelstrecken: Kompakte Felder und interessante Entscheidungen</strong></p>
<p><img src="../photos/Harrer-800m-frauen-int.jpg" width="162" height="243" class="float_right" />Thomas Matthys heißt der Mann aus Belgien, den alle jagen wollen. Sein Hausrekord steht bei 1:45,75. Ihm am nächsten kommen sollten der Südtiroler Lukas Rifesser (1:46,12) und der Erfurter Stephan Eberhardt, der in diesem Jahr die 1500 m schon in 3:37 gelaufen ist. Steffen Co aus München und Brahim Mahfoud sind zwei weitere Asse, die 1:47er Zeiten stehen haben. Dafür, dass nicht gebummelt wird, sorgt der jüngere Eberhardt-Bruder Georg.<br />
  Bei den Frauen sah anfangs alles nach einem DM-Endlauffeld aus. Nun hat Claudia Hofmann nach dem Rehlinger 2:06-Rennen wohl die Reißleine gezogen und tendiert nun doch wieder zu den 400 m. Die Deutsche Meisterin Jana Hartmann hat ein internationales Rennen im griechischen Thessaloniki bekommen. So bleiben noch Anja Clausnitzer (2:03,83) und das Telis Ass Corinna Harrer. Mit Hilfe von Tempomacherinnen will die nach ihrem B-Lauf-Sieg in Rehlingen (2:05,19) erneut schneller rennen. „Bei einer 04er-Zeit muss mein Papa mein Zimmer aufräumen, das will ich mir nicht entgehen lassen“, so ihr Motivationsschub für die erneute Leistungssteigerung. Ganz Regensburg wird sie nach vorne brüllen.</p>
<br />
<h3>1500 m, 3000 m</h3>
<p><img src="../photos/pflieger_philipp_dlvgala08_foto_gantenberg-foto.jpg" width="160" height="240" class="float_left" />Fangen wir diesmal mit den Frauen an. Was sich anfangs recht träge anließ, entpuppt sich inzwischen zum beachtlichen Rennen. Die Ungarin Livia Toth nimmt mit einer 4:09 die Pole-Position ein, dahinter die Italienerin Agnes Tschurtschenthaler mit einer gemeldeten 4:14 und die Schweizerin Monika Augustin mit einer 4:16. Simret Restle aus Frankfurt kann das auch laufen und die derzeitig in Deutschland auf Platz vier stehende Lokalmatadorin Christiane Danner will im Verbund mit der Württembergerin Kristina Schadt auch unter 4:20 laufen. Ebenso traut sich das Anja Reinhardt aus Weinstadt zu.<br />
  Bei den Männern werden der Belgier Mario van Waeyenberge, der Algerier Hani Menguelati und der Südtiroler Christian Neunhäuserer mit gemeldeten Zeiten knapp unter 3:40 den Ton angeben. Die deutschen Protagonisten Simon Huckestein und Ricardo Giehl werden sich sputen müssen, um da mitzukommen.<br />
  Über 3000 m steigt der gefeierte 5000 m Vorjahressieger und Telis-Lokalmatador Philipp Pflieger nach sechswöchiger Verletzungspause wiederins Renngeschehen ein. Eigentlich sollte es nur ein Testlauf für sein EM-Qualirennen fünf Tage später in Lugano sein, doch die beiden Konkurrenten Hidajet Bulic (8:04,55) und Markus Ploner (8:09,66) sind auch nicht ohne.</p>
<br />
<a name="3"></a>
<h3>3000 m Hindernis</h3>
<p><strong>Die Hindernisse: Deutschlands Asse zieren sich ein wenig</strong></p>
<p><img src="../photos/Lutz-Dreier-3000hindernis-frauen-int.jpg" width="142" height="200" class="float_right" />Obwohl Regensburg sowohl bei den Damen als auch bei den Herren WM-Norm-Wettkampf und zudem Qualifikationsrennen für die U20-EM ist, zieren sich Deutschlands Asse ein wenig. 
  Bei den Damen ist dies auf Grund des Rekordrennens von Antje Möldner in Rehlingen verständlich. Die Fürtherin Julia Hiller zieht es zu einem Auslandsstart nach Bydgoszcz. Bleiben immerhin die mehrfache Deutsche Meisterin Verena Dreier, 2006 EM-Teilnehmerin und natürlich Telis-Lokalmatadorin Susi Lutz, die inzwischen durchaus mit der Siegenerin mithalten kann, um endlich die heiß ersehnte 10-Minuten-Barriere zu durchbrechen. In Rehlingen fehlten ihr dazu nur noch lumpige 2,57 Sekunden. <img src="../photos/Nowill,Peter2-3000hindernis-maenner-int.jpg" width="130" height="193" class="float_left" />In die gleichen Regionen will die Hildenerin Saana Koubaa vorstoßen. Für Sarah Cornelsen und Telis-Nachwuchs Julia Kick geht es um die Qualifikation für Novi Sad. Eine 10:35 müssten die beiden aber dazu schon anbieten.<br />
  Bei den Männern trifft der Vorjahressieger Peter Novill (pB 8:26) auf den Italiener Angelo Iannelli, der mit einer 8:22,06 gemeldet ist. Von Deutschlands Assen steht nur Jan Förster an der Startlinie, der in den Händen des württembergischen Landestrainers Jens Boyde derzeit so richtig aufblüht. Vom deutschen Nachwuchs ist den bayerischen U23-Startern Daniel Götz und Felix Henschel durchaus der Sprung zur EM nach Kaunas zuzutrauen. Bei der U20 sind die beiden Schwaben Julia Kreibich und Benedikt Karus die EM-Kandidaten für Novi Sad.</p>
<br />
<h3>110 m Hürden Männer</h3>
<p><strong>110 m Hürden: Erst draußen dann wieder drin</strong></p>
<p>Bundestrainer Idriss Gonschinska war schier von den Socken, als er seine 110 m Hürden nicht im Gala Programm fand. In Regensburg ist man aber flexibel. Ein paar Telefonate hin und ein paar her. Nun steht das Feld und die geledeten Maximilian Bühler, Marlon Odom, Martin Hoffmann, David Filipowski und Jens Werrmann können sogar in Richtung der WM-Norm von 13,55 laufen. Was heißt schon „in Richtung“. Maxi Bühler hat dies bereits mit seinen 13,48 erledigt und Jens Werrmann war 2006 immerhin im EM-Endlauf von Göteborg.</p>
<br />
<h3>400 m Hürden Männer</h3>
<p><strong>400 m Hürden: Nicht die ganz Großen, aber doch keine schlechten sind am Start</strong></p>
<p>Es sind vielleicht nicht die ganz großen deutschen Namen wie Thomas Goller oder Christian Duma am Start. Aber die zeigten in Rehlingen auch nur Durchschnittliches, Zeiten, die Regensburgs Starterfeld durchaus auch bringen kann. Beachtenswert wird vor allem der Auftritt des bayerischen Junioren David Gollnow (pB 51,48), Sivio Schirrmeister aus Dresden ist nur ein Jahr älter und hat ebenfalls eine 51,37 stehen und auch Oliver Scheer ist schon unter 52 Sekunden geblieben. Das will auch der Südtiroler Markus Crepaz anbieten (bisher 52,06).</p>
<br />
<a name="4"></a>
<h3>10.000 m Frauen</h3>
<p><strong>10.000 m: Mocki will den Rekord</strong></p>
<p><img src="../photos/mockenhaupt-sabrina1-gala06.jpg" width="153" height="220" class="float_right" />Eigentlich waren die 10.000 m kein Gala Wettbewerb. Doch Mocki macht’s möglich. Sie will in Regensburg laufen und sie soll laufen, notfalls um Mitternacht, wenn die Bedingungen ideal sind für einen Rekord, für eine Dreißiger-Zeit und für ihren treuen Tempomacher Oliver Mintzlaff. Da ist es schon fast Beiwerk, dass die Deutsche Halbmarathonmeisterin Melanie Schulz auch mit von der Partie ist und etliche Männer, die mit ihren 30er Zeiten durchaus national inzwischen auch bei den Männern mithalten können. Mocki wird sicher die Kleinste im Feld sein, im Ziel aber todsicher die Allergrößte. Telis-Lokalmatadorin Mikki Heiß, Marathon-DM-Fünfte wird ebenso mitlaufen.</p>
<br />
<h3>Stabhochsprung</h3>
<p><strong>Die Sprünge: Die Stabishow der Höhenjäger/Innen</strong></p>
<p><img src="../photos/Lobinger,Tim1-stabhoch-maenner-int.jpg" width="148" height="220" class="float_left" />Jung gegen alt, Erfahrung gegen Himmelsstürmerei. Bei den Männern heißt das Duell Tim Lobinger gegen Alexander Straub, dass vor Tagen pari bei 5,60 ausging. Wieder ein paar Tage vorher hat sich der Altmeister beim Bischofshofsspringen, ebenfalls in der Domstadt, mit seinen 5,63 an die zweite Stelle der deutschen Bestenliste geschoben. Nun soll die WM-Norm von 5,70 her, die WM-Plätze werden bei der Güte der deutschen Stabis eh erst in Ulm ausgesprungen. Mit von der Partie keine Schlechten: Jurij Rovan, am Samstag sprang er eine 5,53, Jason Wurster – der Kanadier überquerte in Rehlingen eine 5,50 -, der wieder genesene Michael Frauen mit einer pB von 5,51 und die beiden Nachwuchsspringer Nico Dieckmann und Thorsten Müller. Das Ganze komplettiert der Schweizer 5,35 Springer Patrick Schütz und der wieder in die Szene einsteigende Marvin Osei-Tutu.</p>
<p>Bei den Frauen fehlt die Winter-Königin Silke Spiegelburg. Aber was heißt das schon. Auch Caro Hingst und Anna Battke sind in der Lage Höhen über 4,70 anzugreifen und Kristina Gadschiew, Martina Strutz und Elisaveta Ryzih sind mit Bestleistungen um die 4,50 auch keine Schlechten. Für die beiden Lokalmatdorinnen Elena Horn und Amelie Garatva geht es um den ersten Vier-Meter-Sprung der Saison. Das würde für Erstere für die DM-Quali reichen, zweitere wäre damit auf einem guten Weg Richtung U20-EM Novi Sad.</p>
<br />
<a name="5"></a>
<h3>Weitsprung</h3>
<p><strong>Die Weitsprünge: Nicht die absolute Klasse aber zwei Klasse Regensburger</strong></p>
<p><strong><img src="../photos/Ziegler,Manuel1_dmjun08_gantenberg-foto.jpg" width="164" height="230" class="float_right" /></strong>Mario Kral, der hoffnungsvolle Zehnkampf-Junior aus Halle, will seine persönliche Bestleistung von 7,68 verbessern. Manuel Ziegler, der U20-EM-Kandidat der LG Telis Finanz will seine 7,15 steigern, damit er in seiner Spezialdisziplin, dem Dreisrung, endlich die 16 Meter knacken kann, Wunschziel Junioren-EM Novi Sad. Matthias Esser (7,48), Kevin Korona (7,45) und Marcel Kirtges (7,42) werden auch mitmischen.</p>
<p>Die in diesem Jahr konstant über sechs Meter springende Telis-Athletin Michelle Weitzel hat sich für die Gala nichts mehr gewünschen, als im Hauptprogramm vor voller Tribüne zu springen. Ihr Wunsch ist uns Befehl gewesen. Ihre stärksten Herausforderinen sind die Münchnerin Katharina Naumann (6,31), und Katharina Franke (6,13).</p>
<br />
<h3>Hochsprung</h3>
<p><strong>Die Hochsprünge: Es könnte über die 2,20 und 1,90 gehen</strong></p>
<p> 2006 ist Melanie Skotnik, damals im Trikot der LG Domspitzmilch Regensburg, über 1,91 gesprungen. Nachdem Julia Wanner nach iher phänomenalen Steigerung auf 1,93 nun in Kassel startet, hatte Regensburg den schwarzen Peter in der Hand., aber nicht lange. Jetzt soll Lavern Spencer aus Saint Lucia, in diesem Jahr bereits 1,90 gesprungen bei einer persönlichen Bestleistung von 1,94, die Lücke auffüllen. Mit von der Partie auch Meike Kröger. Sie hat bisher eine 1,92 stehen. Die aus Bayern stammende Anja Saumweber ist mit ihren 1,82 Kandidatin für die U20-EM in Novi Sad.</p>
<p>Bei den Männern hat sich Sebastina Kneifel mit einer 2,21 angekündigt. Dahinter sind Markus Rehak und Marko Wühler für Höhen um die 2,10 gut. Auch der Kötztinger Christopher Irlbeck will dort hin (bisher 2,08).</p>
<br />
<h3>Speerwurf</h3>
<p><strong>Die Würfe: Die Frauen werfen in Regensburg wieder Speer</strong></p>
<p> Früher warfen Deutschlands beste Frauen regelmäßig in Regensburg. Steffi Nerius war schon da und auch Christina Obergföll – zu einem Zeitpunkt, als noch niemand mit diesem Namen etwas anfangen konnte. Der Stadionrekord liegt bei etwas mehr als 64 Meter. Da kommen die wackeren Juniorinnen des U20/U18-C-Kaders natürlich noch nicht hin. Nachdem uns Schönebeck in all den vergangenen Jahren regelmäßig die besten Werferinnen „geklaut“ hat, freuen wir uns dennoch, dass uns Bundestrainerin Maria Ritschel zumindest den Nachwuchs schickt und Regensburg nicht vergessen hat. Sabine Kopplin aus Jena sollte in der Lage sein, die 50 Meter zu übertreffen. Das kann auch die wesentlich ältere Augsburgerin Susanne Rosenbauer, ständiger Gast in der Domstadt mit einer Bestleistung von 54,62. Bei den Männern ist die bayerische Nachwuchshoffnung Vinzenz Taufratshofer mit einer Bestleistung von 72,63 knapp in der Poleposition vor dem Dresdner Lars Hamann (71,74).</p>
<br />
<?php require("../_footer.dir1.inc.php"); ?>