<?php $title = "News - Der Weg nach Berlin geht über Regensburg";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2>Der Weg nach Berlin geht über Regensburg </h2>
<strong>DLV hat Reihe von WM-Normwettkämpfen zur Sparkassen Gala nach Regensburg vergeben</strong>
<br />
<br />

<p>  <img src="../photos/gala06_ziegler-foto.jpg" width="309" height="206" class="float_left" />Regensburg, 24. März 2009 (orv) – Der Bundesausschuss Leistungssport des Deutschen Leichtathletik-Verbandes (DLV) hat WM-Testwettkämpfe für eine Nominierung für die Weltmeisterschaften in Berlin (15. bis 23. August) bzw. Normwettkämpfe für die U20-Europameisterschaften in Novi-Sad (Serbien; 23. bis 26. Juli) festgelegt. Die Nominierung für den Jahreshöhepunkt in der deutschen Hauptstadt erfolgt in vier Etappen. Nachdem am 25. Mai die Marathonläufer und am 22. Juni die Mehrkämpfer nominiert werden, fällt die Entscheidung für alle anderen Disziplinen am 6. Juli nach den Deutschen Meisterschaften. Freie Plätze können danach noch bis zum 3. August vergeben werden. Pro Disziplin wurden zwei bis vier Meetings benannt, bei denen erzielte Leistungen ab dem 1. April (sowie beim EAA Winterwurf-Cup am 14./15. März in Los Realejos/Spanien) als Norm für die Weltmeisterschaften anerkannt werden. Die Regensburger Sparkassen Gala am 7. Juni ist dabei ein zentrales Meeting mit Normwettkämpfen im Sprint (100 m/200m – Mä/Frauen), über 400 m (Mä/Fr.), 800 m und 1500 m (Mä/Fr.), 400 m Hürden (Mä/Fr.), 3000 m Hindernis (Mä/Fr) und im Stabhochsprung (Mä/Fr.). Inklusive der 4x100 m Tests sind dies 18 WM-Normwettkämpfe. Dazu kommen noch einige Normwettbewerbe für die U20-EM in Novi-Sad und für die U23-EM in Kaunas.</p>
<p>„Das ist natürlich eine frohe Botschaft für unsere diesjährige Sparkassen Gala. Besonders freut uns die Aufwertung mit dem Stabhochsprung der Männer. Regensburg hat in den letzten Jahren eben gezeigt, dass es Leichtathletik organisieren kann und die Macher von der LG Telis Finanz werden sich auch dieses Jahr alle erdenkliche Mühe geben, das Meeting mustergültig auszurichten. Bereits fest gebucht sind wieder die großen elekronischen Anzeigentafeln und das Moderatorenteam um Frank Möckel und Bert Hörhold. Außerdem plant leichtathletik.de einen live-stream aller Wettbewerbe. Das heißt, sie sind live im Internet ähnlich einer Fernsehübertragung zu verfolgen“, so Meetingdirektor Kurt Ring zur derzeitigen Lage.</p>
<p>Es lohnt sich also, am Sonntagnachmittag des 7. Juni auf dem Uni-Hügel vorbeizuschauen. Zirka dreitausend Zuschauer waren es im letzten Jahr, ein paar mehr würden die schon hervorragende Stimmung sicher nochmals heben. Die Eintrittspreise von moderaten fünf Euro sind ein Schnäppchen und dienen der Nachwuchsarbeit der LG Telis Finanz als willkommene Fördermittel. Die veranstaltende athletics SPORT GmbH mit ihrem allgegenwärtigen Geschäftsführer Otto Prinzing kann schon jetzt berichten: „Es ist angerichtet für Deutschlands Elite auf dem Weg zu den Weltmeisterschaften nach Berlin.“</p>
<p align="justify"><a href="http://www.leichtathletik.de/image.php?AID=20766&amp;VID=0" target="_blank">WM-Testwettkämpfe 2009</a> </p>
<p align="justify"><a href="http://www.leichtathletik.de/image.php?AID=20765&amp;VID=0" target="_blank">Normwettkämpfe U20-EM 2009</a></p>
<p class="textnote">Foto der Sparkassen-Gala 2006 (Ziegler-Foto) </p>
<?php require("../_footer.dir1.inc.php"); ?>