<?php $title = "News - Telis Talente im Schatten der Gala-Stars ganz groß";
 $menu['current'] = "news"; ?>
<?php require("../_header.dir1.inc.php"); ?>

<h2>Telis Talente im Schatten der Gala-Stars ganz groß </h2>
<strong>Der Regensburger Leichtathletik-Nachwuchs sprengt bei der Sparkassen Gala auch eigene Grenzen</strong>
<br />
<br />

<p>  <img src="../photos/stelkens_gala09_lutzfoto.jpg" width="169" height="253" class="float_left" />Regensburg, 9. Juni 2009 (orv) - Sie schufteten von Freitag bis spät in den Sonntagabend wie die Besessenen, damit die Stars der Sparkassen Gala auch ins rechte Licht gerückt werden konnten. Ihre eigenen sportlichen Ziele mussten sie an diesem Wochenende hintan stellen. Lediglich die Stunde vor ihrem Start im Vorprogramm gehörte ihnen, reichlich wenig für neue Bestleistungen. Und dennoch schafften sie es immer wieder, genau an diesem Regensburger Gala-Tag über sich hinauszuwachsen. Die Rede ist vom Telis-Nachwuchs, der auch in diesem Jahr bei der Gala für viel Erfreuliches sorgte.</p>
<div></div>
<p>Müde  aber völlig entrückt streckte Junior Johannes Graf nach seiner  Stadionrunde die Arme in die Höhe. Er hatte soeben vom Coach erfahren,  dass er seine bisherige Bestzeit von 49,95 mit einer 49,13 geradezu  pulverisiert hatte. Nach überstandenen Abitur nun also die kaum für  möglich gehaltene Quali für die Deutschen Juniorenmeisterschaften. Wie  ein Berserker biss sich der Jugendliche Dominik Jakob im Endspurt des  B-Laufes bis an die Spitze. Nach zwei vergeblichen Anläufen, unter den  für die Deutschen Jugendmeisterschaften nötigen 1:56,70 zu bleiben,  stand nun eine 1:55,65 auf der Großbildanzeige. <img src="../photos/liedljohannes_gala09_lutzfoto.jpg" width="167" height="238" class="float_right" />Auch sein  Trainingskumpel Stephan Werner ließ sich nicht lumpen. Die Frage nach  seiner Leistung konnte er mit „Bestzeit 1:57,30“ beantworten. Eine  Runde weniger bis ins Ziel brauchte der B-Jugendliche Lukas Zweck zu  laufen. Dies tat er mit 51,17 erheblich schneller als sonst, was ihm  nun auch „flach“ wie schon bei den Langhürden die Möglichkeit gibt, bei  den „Deutschen“ dabei zu sein. Sein Bruder Jonas, heuer schon in der  U23 startend, lieferte über 1500 m eine ganz vorzügliche 3:53,97 ab,  stürmte im letzten Moment auch noch am höher eingeschätzten und ein  Jahr älteren Teamkollegen Sebastian Zundler (3:54,08) vorbei und darf  sich nun bei den Deutschen Juniorenmeisterschaften in Göttingen genauso  wie Zundler an die Startlinie stellen. </p>
<p>Das hatte 400 m Läuferin Vera Stelkens für alle Deutschen  Meisterschaften schon in Schwandorf abgehakt. Die bei der Gala  abgelieferten 55,38 waren dennoch wieder eine feine Nummer. Erneut noch  vergeblich kämpfte Stabifrau Elena Horn gegen die DM-Norm (4,00) an.  Die 3,90 waren dennoch ein deutlicher Fortschritt, nun soll es kommende  Woche in Gräfelfing klappen. Bestzeiten konnten Phillipp Sellack über  100 m mit 10,97 – damit erstmals unter elf Sekunden -, der Jugendliche  Johannes Liedl (1500 m/4:12,12), Max Meingast über die 3000 m  (8:45,59), der noch B-Jugendliche 200 m Sprinter Kevin Urbanek (22,88)  und der Schüler Johannes Donhauser (1000 m/2:53,42) vermelden.  Erstaunlich auch die Steigerung der erst 17-jährigen Maximiliane  Fleischer im Weitsprung mit sehr guten 5,50.</p>
<p>Last but noch least der formidable Doppelpack von Nesthäkchen Anna  Lotter (W14). Seit Samstagmittag immer im Schlepptau des hart  arbeitenden Vaters Andreas durfte sie über 100 m und im Weitsprung ran.  Herausgekommen sind zwei Premieren: Erstmals unter 13 Sekunden (12,89)  und erstmals über die fünf Meter (5,11).</p>
<p class="textnote">Fotos: Vera Stelkens und Johannes Liedl (Lutz-Fotos)</p>
<?php require("../_footer.dir1.inc.php"); ?>