<?php require("_header.inc.php"); ?>
              <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr> 
                  <td><img src="images/kreis.gif" height="20" alt="" /></td>
                  <td width="83%" class="newsTitle">Die 
          stillen Helden einer Gala</td>
                  <td width="17%" class="newsDate">22. Juni 2006</td>
                  <td><img src="images/kreis-rechts.gif" height="20" alt="" /></td>
                </tr>
                <tr> 
                  <td height="579" colspan="4" class="news"><b>Ohne die vielen namenlosen Helfer geht bei Groﬂveranstaltungen gar nichts</b> <br />
                    <p>Regensburg,               22. Juni 2006 (orv) - Du sitzt ergriffen im Kinosessel, gefangen noch               von dem, was du in den letzten eineinhalb Stunden gesehen und geh&ouml;rt               hast. Musik rieselt aus den Lautsprechern, der Abspann l&auml;uft,               das Verzeichnis all jener, die das Produkt erst m&ouml;glich gemacht               haben, vom Regisseur bis zum Kameraassistenten. Bei Gro&szlig;veranstaltungen               im Sport ist das ganz anders. Ein Live-Event kennt keinen Abspann.               Wenn im Stadion die Lichter ausgehen, die Athleten mit ihren Betreuern               nach Hause gefahren sind, kein Zuschauer mehr am Platz sitzt, dann               ist noch lange nicht Ruh, dann geht es erst wieder richtig los, bei               all den stillen Helden, die eine Gala braucht. So geschehen auch bei               der Domspitzmilch Gala letzten Samstag im Regensburger Uni-Stadion.<br />
Viel Lob wurde mir als Veranstaltungsleiter schon w&auml;hrend des               Meetings zugetragen, die Sprecher nannten meinen Namen, die Presse               w&uuml;rdigte &quot;meine&quot; Leistung, das Bild mit &quot;Mocki&quot;               zierte trotz Fu&szlig;ball-WM einige Zeitungsseiten. Die weit &uuml;ber               hundert Helfer und Kampfrichter sind aber nirgends zu finden, die               diesen &quot;meinen&quot; Erfolg erst m&ouml;glich gemacht haben.               Ohne sie w&uuml;rde kein Ergebnis die Sprecher erreichen, keine H&uuml;rde               am richtigen Platz stehen. Von ihnen zu erz&auml;hlen ist daher meine               Pflicht, ihnen von ganzem Herzen zu danken mir ein tiefes Bed&uuml;rfnis.<br />
Zu allererst jenen, die durchaus an ihren &quot;Stabstellen&quot;               hohe F&uuml;hrungsqualit&auml;ten zeigen. Am Ziel, wo mein Dr&auml;ngen               auf Grund meiner oft &quot;aberwitzigen&quot;, aber dennoch durchf&uuml;hrbaren               und dadurch f&uuml;r den Zuschauer kurzweiligen Zeitpl&auml;ne, inzwischen               klaglos hingenommen wird und auch am Start, wo Starter, Startordner               und Laufnummernverteiler inzwischen eine ganz besondere Qualit&auml;t               erreicht haben. Im Wettkampfb&uuml;ro, wo absolute Topleute, die besten               die Bayern derzeit hat, an drei PC's pausenlos Listen auswerfen, L&auml;ufe               einteilen, Stellpatzkarten verarbeiten, Ergebnisse eintippen und Urkunden               ausdrucken, dabei noch so manchen Kram der von au&szlig;en kommt,               still und leise gl&auml;tten, fast immer ein Ohr haben, wenn Adrenalin               geschw&auml;ngerte Trainer ihre Sch&uuml;tzlinge nun doch nicht auf               der vorgesehenen Bahn, sondern auf einer anderen haben wollen.<br />
Die &Uuml;bersicht in diesem Papierwahnsinn zu behalten ist keine               leichte, was Bundestrainer Werner Klein dann so ausdr&uuml;ckt: &quot;Toll,               mit welcher Ruhe bzw. Kompetenz und mit welchem Fach- und Sachverstand               das Wettkampfb&uuml;ro gef&uuml;hrt wurde.&quot;<br />
Mehr als Lob und Ehr bekommen sie nicht, die Helfer/Innen an der Ausgabe               der Wettkampfunterlagen, am Einlass, am Stellplatz, bei der Ger&auml;tekontrolle,               beim Kaffeezelt, beim Getr&auml;nkeausschank, im VIP-Zelt und bei               allen anderen n&ouml;tigen Arbeitsstellen. Das ist aber nur das Herzst&uuml;ck               dieser Gala, die Ouvert&uuml;re mit dem Aufbau frisst &auml;hnlich               viel &quot;menpower&quot; und der Abbau sp&auml;t abends um elf Uhr               und am darauf folgenden Sonntag erfordert eiserne Disziplin der Beteiligten,               wenn all schon &quot;etwas angeknockt in den Seilen h&auml;ngen.&quot;<br />
An der Gala beteiligte &quot;Heimathleten/Innen&quot; werden in aller               Regel davon nicht ausgenommen, schon gar nicht der Nachwuchs. Der               schuftet bereits am Vortag beim Aufbau stundenlang, um sich dann bei               untergehender Sonne todm&uuml;de eine halbst&uuml;ndige &quot;Rennanpassung&quot;               f&uuml;r den folgenden Tag zu g&ouml;nnen. Dort sind sie dann trainerlos,               weil der oder die Betreuungsperson in andere Rollen schl&uuml;pfen               musste, von ihnen ein hohes Ma&szlig; an Selbstst&auml;ndigkeit verlangt,               f&uuml;r die, ihre Stunde des Wettkampfes, bei ihren Heimveranstaltungen.               Anwesend ist diese Nachwuchsmannschaft am Tage der Gala fast zw&ouml;lf               Stunden, eingebunden in tausend kleine Aufgaben, die es vor ihrem               Wettkampf und auch danach zu erledigen gilt. Ausgenommen wird da selbst               das Sternchen der Truppe nicht, die sich just an diesem Tag f&uuml;r               die Junioren-WM qualifizieren soll, dies dann auch mit Bravour erledigt.               Zehn Kuchen hat auch sie am Vortag zu produzieren, Worauf sie jetzt               &quot;vier Wochen keine Eier mehr sehen kann&quot;. Im langsam aufsteigenden               Mitternachtsnebel des immer noch glei&szlig;enden Flutlichts sammelt               sie dann ganz alleine die letzten Flaschen in der Veranstaltungswiese               ein und schleppt tags darauf am Morgen schwere Polizeigitter, wie               all die anderen. Einziges Privileg der &quot;Qualifizierten&quot;:               Sie brauchte am Wettkampftag vor dem entscheidenden Rennen nicht zur               Arbeit antreten. Sie ist keine Ausnahme, sie sind alle so, mit sanfter               &Uuml;berzeugungskraft und Disziplin zum &quot;Dienen am Ganzen&quot;               erzogen. Manchmal wundert man sich dennoch. Trotz dieser Belastungen               geben die meisten dann auch noch Bestleistungen ab. Sie holen weit               mehr aus sich heraus, was sie vorher von sich angenommen haben.<br />
Die Veranstaltung f&uuml;r die Athleten machen, hei&szlig;t unsere               Devise und unsere Kampfrichter/Innen haben diese Botschaft aufgenommen.               Dieses Gemisch aus Freiwilligen, Athleteneltern und Leichtathletik-Verr&uuml;ckten               soll und wird immer wieder im Zweifelsfall f&uuml;r den/die Athleten/In               entscheiden, fern jeglichen Dirigismus.<br />
Und wenn es euch gefallen hat in unserer kleinen Stadt, in der nur               ganz vereinzelt Top-Athleten das &quot;internationale Flair&quot;               vermisst haben, kommt wieder zur n&auml;chsten Domspitzmilch Gala               2007. Wir werden euch mit offenen Armen aufnehmen. Irgendwie haben               wir das alles immer noch geschafft, auch wenn wir uns jetzt tierisch               auf fremde Stadien freuen.</p>
                  <p><strong><strong>Nachbetrachtung von Kurt Ring</strong></strong></p></td>
                </tr>
              </table>
              <?php require("_footer.inc.php"); ?>