<?php $title = "Aktuelles";
 $menu['current'] = "aktuelles"; ?>
   <?php require("_header.inc.php"); ?>

<h2>10,07 – Julian Reus dreht auf</h2>

<p><strong>Perfekte Bedingungen im Regensburger Uni-Stadion</strong></p>
<p><img src="http://lg-telis-finanz.de/images/stories/2016/Reus_KiefnerFoto.jpg" alt="Reus KiefnerFoto" class="float_left" title="Julian Reus (Foto: Kiefner)" width="241" height="160">Regensburg, 5. Juni 2016 (leichtathletik.de) - Der deutsche Rekordhalter Julian Reus präsentierte sich am Sonntag bei der Sparkassen-Gala in Regensburg in herausragender Form. Der Wattenscheider nutzte die guten Bedingungen im Vorlauf bei einem idealen Rückenwind von 1,8 Metern pro Sekunde zu einer Zeit von 10,07 Sekunden. Nur einmal war er unter regulären Bedingungen bisher schneller, bei seinem deutschen Rekord vor zwei Jahren in Ulm (10,05 sec). „ich bin natürlich zufrieden, dass ich das zeigen konnte, was ich letzte Woche in Dessau schon angedeutet hatte. Ich habe die doch guten Bedingungen genutzt. Die Olympia-Norm abgehakt, wieder unter 10,10 gelaufen, das ist schon sehr ordentlich“, sagte der schnellste Deutsche, der auf das Finale verzichtete, um noch weitere Starts mit der Staffel und über 200 Meter anzupeilen. <a href="http://www.leichtathletik.de/news/news/detail/nadine-hildebrand-wieder-unter-13-sekunden/" target="_blank">Hier</a> geht's weiter auf leichtathletik.de</p>


<h2>Die Regensburger und ihr Wetterglück</h2>

<p><strong>Unwetter zog am Uni-Stadion vorbei</strong></p>
<p>Regensburg, 4. Juni 2016 (orv) - Das Gerücht, das Meeting-Direktor Kurt Ring mit Petrus einen hochdotierten Vertrag abgeschlossen hätte, stimmt natürlich nicht. Während in vielen Gegenden Bayerns Unwetter ihr Unwesen trieben, blieb es während der ganzen Veranstaltung im Uni-Stadion trocken und es herrschten sogar ideale Verhältnisse für die Leichtathletik. Lediglich am Ende eilte es dann doch ein wenig. Von Osten zog eine mächtige Gewitterfront auf und die beiden 5.000m Läufe hatten mit dem aufkommenden Wind schon starke Probleme. Die Zeiten blieben unter den Erwartungen und so manche angepeilte DM-Normerfüllung wurde bei den Damen sprichwörtlich verblasen.</p>

<h2>Die Regensburger und ihr Wetterglück</h2>

<p><strong>Unwetter zog am Uni-Stadion vorbei</strong></p>
<p>Regensburg, 4. Juni 2016 (orv) - Das Gerücht, das Meeting-Direktor Kurt Ring mit Petrus einen hochdotierten Vertrag abgeschlossen hätte, stimmt natürlich nicht. Während in vielen Gegenden Bayerns Unwetter ihr Unwesen trieben, blieb es während der ganzen Veranstaltung im Uni-Stadion trocken und es herrschten sogar ideale Verhältnisse für die Leichtathletik. Lediglich am Ende eilte es dann doch ein wenig. Von Osten zog eine mächtige Gewitterfront auf und die beiden 5.000m Läufe hatten mit dem aufkommenden Wind schon starke Probleme. Die Zeiten blieben unter den Erwartungen und so manche angepeilte DM-Normerfüllung wurde bei den Damen sprichwörtlich verblasen.</p>

<h2>Klasse Nachwuchsrennen auf der Mittelstrecke</h2>

<p><strong>Drei deutsche U20-Läufer unter 1:49 über 800m und 3:46 über 1500m</strong></p>
<p><img src="http://sparkassen-gala.de/2016/images/inhalt/Abele_Williamson_Beinlich_KiefnerFoto.jpg" alt="" class="float_left" title="(Foto: Kiefner)" width="293" height="192">Regensburg, 4. Juni 2016 (orv) - Faszinierende Duelle verzeichneten die U20-WM-Ausscheidungsrennen über 800m und 1500m. Lokalmatador Beni Huber brauchte auf der ersten Runde der 800m Deutschlands Jugendliche so richtig in Schwung. Am Ende kämpften vier Jungtalente verbissen um den Sie und das mit Klassezeiten. Ganz vorne landete Pascal Kleyer aus der Karlsruher Talentschmiede mit 1:48,50, knapp dahinter Dennis Biederbick (1:48,53), Robert Farken (1:48,87) und Christian von Eitzen (1:49,37). Jetzt haben die Bundestrainer ein Besetzungsproblem für die U20 WM, weil der bisherige Saisonbeste zwar sehr gut war, aber nicht auf einem der zwei vorderen Plätze ankam. Ein weiteres Rennen tags darauf bei der Sparkassen Gala soll nun für Klarheit sorgen.</p>
<p>Das von den Regensburgern Felix Plinke und Tim Ramdane Cherif mustergültig angezogene 1500m Rennen sorgte für ähnliche erfreuliche Unklarheiten. Am Ende lagen gleich drei deutsche Jugendliche mit erheblichen Steigerungen unter 3:46 auf Kurs für die beiden WM-Plätze. Lukas Abele hieß schließlich der strahlende Sieger bei 3:45,12. Knapp dahinter stürmten Marvin Heinrich (3:45,40), Jamie Williamson (3:45,45) und Männer-Sieger Moritz Beinlich (3:45,55) über den Zielstrich, allesamt mit persönlichen Hausrekorden. Den konnte auch noch Pacemaker Tim Ramdane Cherif mit 3:50,84 verzeichnen.</p>


<h2>Erste Höhepunkte durch die Viertelmeiler</h2>

<p><strong>Newcomer Patrick Schneider sorgt fast für eine Sensation - Alexander Gladitz bleibt unter 46 Sekunden - Ruth Sophia Spelmeyer knackt mit 51,92sec Olympianorm</strong></p>
<p><img src="http://sparkassen-gala.de/2016/images/inhalt/Spelmeyer_Lieske_PremruFoto.jpg" alt="" class="float_left" title="Spelmeyer und LG-Präsident Lieske (Premru-Foto)" width="331" height="220">Regensburg, 4. Juni 2016 (orv) - Fast hätte ein Nobody den Arrivierten über 400m die Show geklaut. Patrick Schneider stürmte jedenfalls in den untergradigen Zeitläufen die Bahn herunter, als wolle er die Welt auf der Stadionrunde auf den Kopf stellen. Am Ende standen unglaubliche 46,22 an der Anzeigentafel, fast zwei Sekunden schneller als er bisher gelaufen war. Im eigentlichen A-Lauf liefen denn auch nur noch Alexander Gladitz, der mit 45,94 die EM-Norm unterbot und erstmals in diesem Jahr unter den 46 Sekunden blieb, sowie der diesjährige deutsche Jahresbeste Johannes Trefz mit 46,02 nur schneller.</p>
<p>Bei den Damen gab's dann das hochwertigste Rennen der gesamten Laufnacht. Die Britin Emily Diamond und Kabange Mupopo aus Sambia lieferten sich ein heißes Duell, das mit 51,23 zu 51,35 zu Gunsten der Britin endete. So schnell waren im Uni-Stadion noch nie Frauen die Stadionrunde gelaufen. In deren Sog knackte Ruth Sophia Spelmeyer die ersehnte Olympianorm mit sehr guten 51,92. Für JWM-Normerfüllungen sorgten Hannah Mergenthaler und Hendrikje Richter mit 53,52 und 53,61sec.</p>

<h2>Zäher Beginn der Laufnacht</h2>

<p><strong>Wind dezimiert 200m Felder</strong></p>
<p>Regensburg, 5. Juni 2016 (orv) - Regensburg, 4. Juni 2016 (orv) - Die Laufnacht der LG Telis Finanz, die ihrem Namen bei einem Beginn um 12.45 Uhr so gar nicht gerecht werden wollte, hatte im Regensburger Uni-Stadion einen zähen Anfang. Schuld daran war der Wind, der zwar schönes Wetter brachte, den Sprintern über die halbe Stadionrunde permanent entgegen stand und somit bestleistungsfeindlich war. Tatsächlich fehlte dann auch gut ein Drittel der gemeldeten 200m-Läufer/innen, was zu gehörigen Pausen im sonst enggefassten Zeitplan sorgte. "So etwas ist in Regensburg ein Novum. Das bin ich gar nicht gewohnt", meinte denn auch Moderator Florian Weber, der die Zwischenräume aber charmant mit der einen oder anderen Anekdote zur zehnjährigen Geschichte der Veranstaltung füllen konnte.</p>

<h2>Erste Impressionen online</h2>

<p>Die ersten Impressionen von <a href="http://www.sportmomente-premru.de/fotos/sparkassengala-1-tag/" target="_blank">Timo Premru</a>, <a href="http://www.lg-telis-finanz.de/kiefner/laufnacht16/" target="_blank">Theo Kiefner</a> und <a href="https://www.pictrs.com/sportlich-belichtet/8183346/laufnacht-zur-sparkassen-gala-2016-in-regensburg?l=de" target="_blank">Christian Göstl</a> sind online.</p>

<h2>Ruth Sophia Spelmeyer erstmals unter 52 Sekunden</h2>

<p><strong>Ruth Sophia Spelmeyer hat am Samstag in Regensburg den nächsten Meilenstein ihrer Karriere erreicht</strong></p>
<p><img src="http://sparkassen-gala.de/2016/images/inhalt/Spelmeyer_KiefnerFoto.jpg" alt="" class="float_left" title="Ruth Sophia Spelmeyer (Foto: Kiefner)" width="292" height="194">Regensburg, 4. Juni 2016 (leichtathletik.de) - Die Oldenburger 400 Meter-Läuferin blieb zum ersten Mal überhaupt unter 52 Sekunden. Mit einer Zeit von 51,92 Sekunden unterbot die Deutsche Meisterin auch die Olympia-Norm von 52,20 Sekunden deutlich. Als Drittplatzierte hinter Emily Diamond (Großbritannien; 51,23 sec) und Mupopo Kabange (Sambia; 51,35 sec) musste sie zunächst noch bange Sekunden überstehen, ehe ihre Zeit offiziell war. Dann schickte Ruth Sophia Spelmeyer erst einmal einen lauten Jubelschrei in Richtung Oberpfälzer Himmel. „Endlich die 51 vor dem Komma, endlich die Norm abgehakt. Das bedeutet mir alles. Olympia war das große Ziel, das ich von Anfang an hatte“, sagte sie nach dem Lauf. <a href="http://www.leichtathletik.de/news/news/detail/ruth-sophia-spelmeyer-erstmals-unter-52-sekunden/" target="_blank">Hier</a> geht's weiter auf leichtathletik.de ...</p>

<h2>Olympianorm für Ruth Sophia Spelmeyer über 400m</h2>

<p>
  <strong>Vierteilmeilerin nutzt die Regensburger Laufnacht</strong>
</p>

<p>Regensburg, 4. Juni 2016 - Ruth Sophia Spelmeyer hat die guten Bedinungen auf der Regensburger Bahn genutzt und sich für die Spiele in Rio qualifiziert. Bei ihrem Lauf profitierte sie von Emily Diamond und Kabange Mupopo, die ein schnelles Tempo vorlegten. Am Ende standen für Spelmeyer 51.92s und damit die Qualifikationsnorm für die Olympischen Spiele zu Buche. "Eine Riesen-Erleichterung", sagte die Oldenburgerin im anschließenden Interview. Nächste Station auf dem Weg nach Rio sind die Deutschen Meisterschaften in Kassel.
</p>


<h2>Franzis Gala-Geflüster #9 – Die jungen Wilden setzen Ausrufezeichen</h2>

<p><strong>Alina Reh und Konstanze Klosterhalfen</strong></p>
<p><img src="http://sparkassen-gala.de/2016/images/inhalt/Klosterhalfen_Reh_KiefnerFoto.jpg" alt="" class="float_left" title="Klosterhalfen und Reh (Foto: Kiefner)" width="251" height="167">Regensburg, 4. Juni 2016 (Reng) - Am liebsten hätten wir die beiden natürlich zusammen im Rennen über 1500 Meter gesehen – Alina Reh und Konstanze Klosterhalfen, die jungen Wilden der deutschen Laufszene. Nun hat sich Konstanze allerdings dazu entschieden, in Regensburg die 800 Meter in Angriff zu nehmen. Doch einmal abgesehen davon, sind sie und Alina jenseits der Laufbahn unzertrennlich: „Alina hat so eine fröhliche Art, sie kann einen auch noch kurz vor der Startlinie zum Lachen bringen“, meint Konstanze. „Vor dem Startschuss ist sie immer sehr nervös, aber sobald es losgeht ist sie mental und körperlich voll da und zaubert ihre Leistung auf die Bahn“, meint Alina dagegen anerkennend, „außerdem stellt sie sich niemals in den Vordergrund!“ Das stimmt nicht ganz, denn mit ihrer phänomenalen Rio-Qualifikation setzte Konstanze in den letzten Wochen ein dickes Ausrufezeichen. Und da Alina ihr in dieser Art des sportlichen Ausrufezeichens in nichts nachsteht, freuen wir uns schon jetzt auf zwei strahlende Gesichter im Unistadion – beim Zieleinlauf, genauso wie jenseits der Laufbahn.</p>

<h2>Franzis Gala-Geflüster #8 – Ein wichtiger Test auf hohem Niveau</h2>

<p><strong>Christian Blum</strong></p>
<p><img src="http://sparkassen-gala.de/2016/images/inhalt/Blum_FotoKiefner.jpg" alt="" class="float_left" title="Christian Blum (Foto: Kiefner)" height="150">Regensburg, 4. Juli 2016 (Reng) - Dass am Sonntag alle deutschen Top-Sprinter über die 100 Meter-Distanz in Regensburg an den Start gehen, steht fest. Dass auch die internationale Konkurrenz ein Wörtchen mitreden will, ist ebenfalls gewiss. Was dagegen noch völlig offen ist: In welche Richtung eigentlich gelaufen wird. „Die Rückenwindgarantie ist sehr wichtig für uns“, bestätigt Christian Blum, der nicht zuletzt deswegen die Bedingungen der Sparkassen-Gala zu schätzen weiß: „Das Rennen wird so ein wirklicher Test auf sehr hohem Niveau und es macht natürlich Spaß, sich gegen alle zu messen.“ Nicht zuletzt auch gegen Julian Reus, dem zuletzt kein deutscher Sprinter das Wasser reichen konnte und der bereits in der Vorwoche mit einer Zeit von 10,18s überzeugen konnte. „Mein erster Testwettkampf in Clermont war mit einer Zeit von 10,31s auch gut, ich kann mich nicht beschweren“, erklärt Christian Blum, „am ehesten kann Julian Reus aber wahrscheinlich noch Roy Schmidt gefährlich werden. Mein Fokus liegt dagegen ganz bei mir.“</p>

<h2>Franzis Gala-Geflüster #7 – Der Youngster trifft sein Vorbild</h2>

<p><strong>Tobias Potye</strong></p>
<p><img src="http://sparkassen-gala.de/2016/images/inhalt/Potye_KiefnerFoto.jpg" alt="" class="float_left" title="Tobias Potye (Foto: Kiefner)" height="150">Regensburg, 3. Juni 2016 (Reng) - „Ich hoffe, Eike kommt am Sonntag!“ Die Vorfreude ist Tobias Potye anzuhören. Schon seit er vor vielen Jahren mit der Leichtathletik begonnen hat, ist ihm der Hochspringer Eike Onnen bestens bekannt. Mittlerweile ist Tobias 21 Jahre alt und selbst in der deutschen Hochsprung-Elite angekommen. „Ich vermute, Eike kennt mich seit den vergangenen Jahren auch“, lacht er. In den letzten Monaten hatte Tobias allerdings mit Verletzungspech zu kämpfen und konnte erst im März wieder ins Training einsteigen: „Vermutlich werde ich Eike im Kampf um den Sieg noch nichts entgegensetzen können“, befürchtet er - der Vorfreude auf ein erneutes Treffen mit seinem großen Vorbild tut dies aber selbstverständlich keinen Abbruch.</p>

<h2>Franzis Gala-Geflüster #6 – Mit Lady Gaga Richtung Rio</h2>
<p><strong>Denise Krebs</strong></p>
<p><img src="http://sparkassen-gala.de/2016/images/inhalt/Krebs_KiefnerFoto.jpg" alt="" class="float_left" title="Denise Krebs (Foto: Kiefner)" height="160">Regensburg, 3. Juni 2016 (Reng) - „Ich fühle mich super fit und würde gerne die EM-Norm, wenn nicht gar schon die Olympia-Norm schaffen!“ – wenn man Denise Krebs so sprechen hört, bleibt einem nichts anderes übrig, als sich auf ihren Start über 1500 Meter bei der Sparkassen-Gala zu freuen. Auch sie fiebert dem Rennen schon entgegen, denn dort stößt sie auf geradezu alle deutschen Läuferinnen, die auf dieser Distanz Rang und Namen haben. Da ist eine optimale Vorbereitung natürlich das A und O: „Ich höre vor dem Wettkampf gerne Musik, um mich zu pushen“, erklärt sie. Am besten funktioniert das bei ihr übrigens mit „Born this way“ von Lady Gaga. Vielleicht kann unser Stadion-DJ da ja mithelfen…</p>

<h2>Franzis Gala-Geflüster #5 – Gala-Wetter für die Hürdensprinterin</h2>

<p><strong>Nadine Hildebrand</strong></p>
<p><img src="http://sparkassen-gala.de/images/inhalt/Hildebrand_KiefnerFoto.jpg" alt="" class="float_left" title="Nadine Hildebrand (Foto: Kiefner)" height="180" >Regensburg, 2. Juni 2016 (Reng) - 12,79 Sekunden dauerte es, bis Nadine Hildebrand bei ihrer Saison-Eröffnung in Weinheim über 110 Meter Hürden im Ziel war – also nicht sehr lange. „Ich hatte ehrlich gesagt nicht mit einer so schnellen Zeit gerechnet“, gesteht sie. Nach einer etwas holprigen Wintersaison, halfen ihr zwei Trainingslager, um rechtzeitig für den Sommer in Form zu kommen. „Wenn in Regensburg die Bedingungen so gut sind wie in Weinheim, möchte ich meine Leistung bestätigen“, erklärt sie. Und die Chancen stehen nicht schlecht: Wer regelmäßig in Regensburg zu Gast ist, weiß, dass Nadine sich auf das traditionelle Gala-Wetter verlassen kann – und dann steht ihrem Vorhaben wahrlich nichts mehr im Wege!</p>

<h2>Franzis Gala-Geflüster #4 – Mit Lockerheit und Spaß nach Rio</h2>

<p><strong>Sebastian Keiner</strong></p>
<p><img src="http://www.sparkassen-gala.de/images/inhalt/Keiner_Orth_KiefnerFoto.jpg" alt="" class="float_left" title="Sebastian Keiner (Foto: Kiefner)" width="180">Regensburg, 2. Juni 2016 (Reng) - Dass in diesem Jahr die Uhren ein wenig anders ticken, weiß auch Sebastian Keiner: Olympia steht vor der Tür und damit die altbekannte Jagd nach den Normen, um sich für eine Teilnahme bei den Spielen in Rio zu qualifizieren: „Das zehrt nach einiger Zeit natürlich an den Kräften“, gesteht der 1500 Meter-Läufer, „gerade deswegen stehen für mich am Anfang dieser Saison definitiv Lockerheit und Spaß im Vordergrund!“ Bei der Sparkassen-Gala wird er deshalb einen ersten Versuch in Richtung der geforderten Zeit von 3:35,50min starten, will sich aber auch nicht zu stark unter Druck setzen: „Ich bin fit“, erklärt er, „und zufrieden bin ich, wenn ich am Sonntag alles geben konnte und mit einem cleveren sowie entspannten Lauf überzeuge.“</p>

<h2>Franzis Gala-Geflüster #3 – Wiederholung eines Kunststücks</h2>

<p><strong>Benedikt Huber – 800m</strong></p>
<p><img src="http://lg-telis-finanz.de/images/stories/2015/Huber1_Mannheim15_Kiefnerfoto.jpg" alt="Huber1 Mannheim15 Kiefnerfoto" class="float_left" title="Benedikt Huber (Foto: Kiefner)" height="180" width="123">Regensburg, 1. Juni 2016 (Reng) - Es ist gerade einmal drei Wochen her, dass sich Benedikt Huber beim Regensburger Rolf-Watter-Sportfest in einer Zeit von 1:52,89min den Siegerpokal über die 800 Meter gesichert hat. Dieses Kunststück möchte er nun bei der Gala an selber Stelle wiederholen - nur diesmal noch schneller und vor noch größerem Publikum. Mutig erklärt er: „Das Ziel ist eine 1:46er-Zeit, also Bestzeit. Das Rennen zu gewinnen wird diesmal sicher schwierig, es ist ja starke Konkurrenz am Start“. Dann fügt „Bene“ aber noch lachend hinzu: „Seit meinem Vereinswechsel zur LG Telis Finanz ist die Gala für mich ja ein Heimrennen. Da werde ich natürlich alles für einen Sieg geben!“</p>

<h2>Franzis Gala-Geflüster #2 – Ein Comeback in Regensburg</h2>

<p><strong>Tina Donder – 3000m Hindernis</strong></p>

<p><img src="http://www.lg-telis-finanz.de/images/stories/2014/Donder_Tina_rostock13_foto_gantenberg_8f7469c3a9.jpg" alt="Donder Tina rostock13 foto gantenberg 8f7469c3a9" class="float_left" title="Tina Donder (Foto: Gantenberg)" height="120">Regensburg, 1. Juni 2016 (Reng) - Die erst 20-jährige Tina Donder gehört zu den größten Hindernis-Talenten Deutschlands. Aufgrund von Verletzungspech konnte sie allerdings innerhalb der letzten eineinhalb Jahre kaum Bahnwettkämpfe absolvieren. In Regensburg möchte sie nun endlich wieder ins Geschehen eingreifen: „Das fühlt sich an wie mein erstes Rennen über 3000m Hindernis“, meint sie, „aber jetzt geht es endlich wieder los! Ich denke, dass ich vor allem mental wieder Kraft gesammelt habe und freue mich riesig wieder einzusteigen!“ Für ihr Comeback hat sie sich zunächst einmal die Norm für die Deutschen Meisterschaften als Ziel gesetzt, aber mithilfe der Unterstützung der Zuschauer geht da bestimmt noch ein bisschen mehr!</p>

<h2>Franzis Gala-Geflüster #1</h2>

<p><img src="http://lg-telis-finanz.de/images/stories/2015/Reng-Ring1_Laufnacht15_Bruesselfoto.jpg" alt="Reng Ring1 Laufnacht15 Bruesselfoto" class="float_left" title="Franzi Reng und Kurt Ring (Foto: Brüssel)" height="190">Regensburg, 31. Mai 2016 (Reng) - Hallo liebe Fans, Freunde und Unterstützer der Leichtathletik! Ich bin Franzi Reng und für mich geht gerade ein großer Traum in Erfüllung: Ich darf als Nachwuchs-Journalistin für „die Gala“ schreiben! Damit meine ich allerdings gar nicht die kunterbunte Klatsch-Zeitschrift, sondern die „Sparkassen Gala“: Denn am kommenden Wochenende wird das Regensburger Unistadion wieder zum „Place to be“ für internationale Sportgrößen! Statt von Hollywood-VIPs oder Royals berichte ich also viel lieber von den Stars der Leichtathletik-Szene: Ich werde euch einige Top-Favoriten vorstellen und ihnen ein wenig auf den Zahn fühlen. Die meisten von ihnen absolvieren derzeit noch die letzten intensiven Trainingseinheiten vor ihrem Start. Doch nicht nur bei den Athleten laufen die Wettkampf-Vorbereitungen auf Hochtouren, auch Meeting-Direktor Kurt Ring ist mittlerweile im alljährlichen Gala-Stress. Trotz aller Organisationsarbeit freut er dennoch schon jetzt auf das Event: „Unsere Gala wird immer beliebter. Wir haben hier mit 1100 Teilnehmern alles dabei von den jüngsten Nachwuchs-Talenten bis zu Elite-Sportlern. Die Kleinen können von den Großen lernen, die Großen profitieren von der grandiosen Zuschauerkulisse – das ist einmalig in Deutschland!“</p>

<h2>Sparkassen Gala und Laufnacht mit einigen Superlativen</h2>

<p><strong>Regensburg wird am kommenden Wochenende zum Mittelpunkt Leichtathletik-Deutschlands</strong></p>

<p><img class="float_left" title="Tatjana Pinto (Kiefner-Foto)" alt="PintoTatjana1 Gala15 Kiefnerfoto" src="http://lg-telis-finanz.de/images/stories/2016/PintoTatjana1_Gala15_Kiefnerfoto.jpg" width="174" height="177">Regensburg, 30. Mai 2016 (orv) – Rechtzeitig, wenn Deutschlands Leichtathleten wieder in Fahrt kommen, wird erneut angerichtet sein im Regensburger Uni-Stadion, am kommenden Wochenende, wenn bei der Laufnacht der LG Telis Finanz (Samstag) und der Sparkassen Gala (Sonntag) ein Highlight das andere jagen wird. „In vielen Disziplinen ist die gesamte deutsche Spitze da. Sie trifft auf internationale Konkurrenz aus über 20 Nationen. Es geht um die begehrten Tickets für die in Amsterdam stattfindenden Europameisterschaften (6-10. Juli) und jene zu den Olympischen Spielen nach Rio (12.-21. August – Leichtathletikwettbewerbe). Masse und Klasse trifft in der in diesen Landen einmaligen Ausführung beim zahlenstärksten Meeting überhaupt aufeinander. Wir verzeichnen ein Teilnehmerplus von über 50 Prozent und sind momentan bei der Startnummer 1200 angelangt“, berichtet Meeting-Direktor Kurt Ring. Selbstverständlich wird die LG Telis Finanz im eigenen Wohnzimmer auch ihre bisher drei für Olympia qualifizierten Athleten Anja Scherl, Philipp Pflieger (beide Marathon) und Florian Orth (5000m) vorstellen. Neben den Dreien haben sich von den „Blauen“ auch Franziska Reng (Halbmarathon) und Maren Kock (5000m) für die Europameisterschaften qualifiziert und sie werden alle da sein. <a href="http://sparkassen-gala.de/news/05-30-Hauptvorschau.php">Hier</a> geht's weiter ...</p>

<?php require("_footer.inc.php"); ?>
